; compressor recipes
;
;---

; Compressed Plant Ball
ic2:plant_ball = ic2:compressed_plants
; Compressed Hydrated Coal Dust
ic2:coal_fuel_dust = ic2:compressed_hydrated_coal
; Nether Brick
minecraft:netherrack*3 = minecraft:nether_brick
; Sandstone
minecraft:sand = minecraft:sandstone
; Ice
minecraft:snowball = minecraft:ice
; Snow Ball
ic2:water_cell = minecraft:snowball
; Advanced Alloy
ic2:alloy_ingot = ic2:alloy
; Carbon Plate
ic2:carbon_mesh = ic2:carbon_plate
; Coal Chunk
ic2:coal_ball = ic2:coal_block
; Diamond
ic2:coal_chunk = minecraft:diamond
; CF Pellet
ic2:foam = ic2:pellet
; Compressed Air Cell
ic2:empty_cell = ic2:air_cell

; Dense Copper Plate
OreDict:ingotCopper*8 = ic2:dense_copper
; Uranium Ingot
OreDict:dropUranium = ic2:uranium_ingot
OreDict:oreUranium = ic2:uranium_ingot