// 
// Decompiled by Procyon v0.6.0
// 

package ic2.shades.org.ejml.alg.block;

import java.io.FileNotFoundException;
import java.io.PrintStream;

public class GeneratorBlockInnerMultiplication
{
    String className;
    PrintStream stream;
    
    public GeneratorBlockInnerMultiplication(final String className) throws FileNotFoundException {
        this.className = className;
        this.stream = new PrintStream(className + ".java");
    }
    
    public void createClass() {
        this.printTop();
        for (int i = 0; i < 2; ++i) {
            final boolean hasAlpha = i == 1;
            for (final Operation o : Operation.values()) {
                if (!hasAlpha || o != Operation.MINUS) {
                    this.print_mult(hasAlpha, o);
                    this.print_multTransA(hasAlpha, o);
                    this.print_multTransB(hasAlpha, o);
                }
            }
        }
        this.stream.print("}\n");
    }
    
    private void printTop() {
        final String foo = "/*\n * Copyright (c) 2009-2013, Peter Abeles. All Rights Reserved.\n *\n * This file is part of Efficient Java Matrix Library (EJML).\n *\n * Licensed under the Apache License, Version 2.0 (the \"License\");\n * you may not use this file except in compliance with the License.\n * You may obtain a copy of the License at\n *\n *   http://www.apache.org/licenses/LICENSE-2.0\n *\n * Unless required by applicable law or agreed to in writing, software\n * distributed under the License is distributed on an \"AS IS\" BASIS,\n * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.\n * See the License for the specific language governing permissions and\n * limitations under the License.\n */\n\npackage org.ejml.alg.block;\n\n/**\n * <p>\n * Matrix multiplication for the inner row major blocks, typically inside of a {@link org.ejml.data.BlockMatrix64F}.\n * </p>\n *\n * <p>\n * This code was auto generated by {@link GeneratorBlockInnerMultiplication} and should not be modified directly.\n * </p>\n *\n * @author Peter Abeles\n */\npublic class " + this.className + " {\n";
        this.stream.print(foo);
    }
    
    private void print_mult(final boolean hasAlpha, final Operation opType) {
        this.createHeader(hasAlpha, opType, false, false);
        this.stream.print("//        for( int i = 0; i < heightA; i++ ) {\n//            for( int k = 0; k < widthA; k++ ) {\n//                for( int j = 0; j < widthC; j++ ) {\n//                    dataC[ i*widthC + j + indexC ] += dataA[i*widthA + k + indexA] * dataB[k*widthC + j + indexB];\n//                }\n//            }\n//        }\n");
        this.stream.println();
        final String o = (opType == Operation.MINUS) ? "-=" : "+=";
        final String m = hasAlpha ? "alpha*" : "";
        this.stream.print("        int a = indexA;\n        int rowC = indexC;\n        for( int i = 0; i < heightA; i++ , rowC += widthC ) {\n            int b = indexB;\n\n            final int endC = rowC + widthC;\n            final int endA = a + widthA;\n            while( a != endA ) {//for( int k = 0; k < widthA; k++ ) {\n                double valA = " + m + "dataA[a++];\n" + "\n" + "                int c = rowC;\n" + "\n");
        if (opType == Operation.SET) {
            this.stream.print("                if( b == indexB ) {\n                    while( c != endC  ) {//for( int j = 0; j < widthC; j++ ) {\n                        dataC[ c++ ] = valA * dataB[ b++ ];\n                    }\n                } else {\n                    while( c != endC  ) {//for( int j = 0; j < widthC; j++ ) {\n                        dataC[ c++ ] " + o + " valA * dataB[ b++ ];\n" + "                    }\n" + "                }\n");
        }
        else {
            this.stream.print("                while( c != endC  ) {//for( int j = 0; j < widthC; j++ ) {\n                    dataC[ c++ ] " + o + " valA * dataB[ b++ ];\n" + "                }\n");
        }
        this.stream.println("            }\n        }");
        this.stream.println("    }");
    }
    
    private String createOpString(final boolean hasAlpha, final Operation opType) {
        String o = this.opString(opType);
        if (hasAlpha) {
            o += " alpha * ";
        }
        return o;
    }
    
    private void print_multTransA(final boolean hasAlpha, final Operation opType) {
        this.createHeader(hasAlpha, opType, true, false);
        final String o = (opType == Operation.MINUS) ? "-=" : "+=";
        final String m = hasAlpha ? "alpha*" : "";
        this.stream.print("//        for( int i = 0; i < widthA; i++ ) {\n//            for( int k = 0; k < heightA; k++ ) {\n//                double valA = dataA[k*widthA + i + indexA];\n//                for( int j = 0; j < widthC; j++ ) {\n//                    dataC[ i*widthC + j + indexC ] += valA * dataB[k*widthC + j + indexB];\n//                }\n//            }\n//        }\n");
        this.stream.println();
        this.stream.print("        int rowC = indexC;\n        for( int i = 0; i < widthA; i++ , rowC += widthC) {\n            int colA = i + indexA;\n            int endA = colA + widthA*heightA;\n            int b = indexB;\n\n            // for( int k = 0; k < heightA; k++ ) {\n            while(colA != endA ) {\n                double valA = " + m + "dataA[colA];\n" + "\n" + "                int c = rowC;\n" + "                final int endB = b + widthC;\n" + "\n" + "                //for( int j = 0; j < widthC; j++ ) {\n");
        if (opType == Operation.SET) {
            this.stream.print("                if( b == indexB ) {\n                    while( b != endB ) {\n                        dataC[ c++ ] = valA * dataB[b++];\n                    } \n                } else {\n                    while( b != endB ) {\n                        dataC[ c++ ] " + o + " valA * dataB[b++];\n" + "                    }\n" + "                }\n");
        }
        else {
            this.stream.print("                while( b != endB ) {\n                    dataC[ c++ ] " + o + " valA * dataB[b++];\n" + "                }\n");
        }
        this.stream.print("                colA += widthA;\n            }\n        }\n");
        this.stream.println("    }");
    }
    
    private void print_multTransB(final boolean hasAlpha, final Operation opType) {
        this.createHeader(hasAlpha, opType, false, true);
        final String o = this.createOpString(hasAlpha, opType);
        this.stream.println("        for( int i = 0; i < heightA; i++ ) {\n            for( int j = 0; j < widthC; j++ ) {\n                double val = 0;\n\n                for( int k = 0; k < widthA; k++ ) {\n                    val += dataA[i*widthA + k + indexA] * dataB[j*widthA + k + indexB];\n                }\n\n                dataC[ i*widthC + j + indexC ] " + o + " val;\n" + "            }\n" + "        }");
        this.stream.println("    }");
    }
    
    private void createHeader(final boolean hasAlpha, final Operation opType, final boolean transA, final boolean transB) {
        final String alphaString = hasAlpha ? " &alpha; " : "";
        final String alphaParam = hasAlpha ? " double alpha ," : "";
        final String transAString = transA ? "<sup>T</sup>" : "";
        final String transBString = transB ? "<sup>T</sup>" : "";
        String opTypeString = null;
        switch (opType) {
            case MINUS: {
                opTypeString = "C - ";
                break;
            }
            case PLUS: {
                opTypeString = "C + ";
                break;
            }
            case SET: {
                opTypeString = "";
                break;
            }
            default: {
                throw new RuntimeException("Unknown optype");
            }
        }
        String funcName = "blockMult" + this.opName(opType);
        if (transA && transB) {
            funcName += "TransAB";
        }
        else if (transA) {
            funcName += "TransA";
        }
        else if (transB) {
            funcName += "TransB";
        }
        this.stream.println();
        this.stream.print("    /**\n     * <p>\n     * Performs the follow operation on individual inner blocks:<br>\n     * <br>\n");
        this.stream.print("     * C = " + opTypeString + alphaString + "A" + transAString + " * B" + transBString + "\n");
        this.stream.print("     * </p>\n     */\n    public static void " + funcName + "(" + alphaParam + " final double[] dataA, final double []dataB, final double []dataC,\n" + "                                     int indexA, int indexB, int indexC,\n" + "                                     final int heightA, final int widthA, final int widthC) {\n");
    }
    
    private String opString(final Operation opType) {
        switch (opType) {
            case MINUS: {
                return "-=";
            }
            case PLUS: {
                return "+=";
            }
            case SET: {
                return "=";
            }
            default: {
                throw new RuntimeException("Unknown opType " + opType);
            }
        }
    }
    
    private String opName(final Operation opType) {
        switch (opType) {
            case MINUS: {
                return "Minus";
            }
            case PLUS: {
                return "Plus";
            }
            case SET: {
                return "Set";
            }
            default: {
                throw new RuntimeException("Unknown opType " + opType);
            }
        }
    }
    
    public static void main(final String[] args) throws FileNotFoundException {
        final GeneratorBlockInnerMultiplication app = new GeneratorBlockInnerMultiplication("BlockInnerMultiplication");
        app.createClass();
        System.out.println("Done generating class");
    }
    
    private enum Operation
    {
        PLUS, 
        MINUS, 
        SET;
    }
}
