package me.halfcooler.ic2r.core.ref.items;

import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.Item.Properties;
import net.minecraft.world.item.Rarity;
import net.minecraft.world.item.ShovelItem;
import net.minecraft.world.item.SwordItem;
import net.minecraft.world.item.Tiers;
import me.halfcooler.ic2r.core.IC2R;
import me.halfcooler.ic2r.core.entity.boat.CarbonBoatEntity;
import me.halfcooler.ic2r.core.entity.boat.ElectricBoatEntity;
import me.halfcooler.ic2r.core.entity.boat.RubberBoatEntity;
import me.halfcooler.ic2r.core.item.ItemBattery;
import me.halfcooler.ic2r.core.item.ItemBatteryChargeHotbar;
import me.halfcooler.ic2r.core.item.ItemBatterySU;
import me.halfcooler.ic2r.core.item.boat.BoatItem;
import me.halfcooler.ic2r.core.item.resources.ItemWindRotor;
import me.halfcooler.ic2r.core.item.tool.Ic2rAxe;
import me.halfcooler.ic2r.core.item.tool.Ic2rHoe;
import me.halfcooler.ic2r.core.item.tool.Ic2rPickaxe;
import me.halfcooler.ic2r.core.item.tool.ItemContainmentbox;
import me.halfcooler.ic2r.core.item.tool.ItemDebug;
import me.halfcooler.ic2r.core.item.tool.ItemDrill;
import me.halfcooler.ic2r.core.item.tool.ItemDrillIridium;
import me.halfcooler.ic2r.core.item.tool.ItemElectricToolChainsaw;
import me.halfcooler.ic2r.core.item.tool.ItemFrequencyTransmitter;
import me.halfcooler.ic2r.core.item.tool.ItemMiningFilterCard;
import me.halfcooler.ic2r.core.item.tool.ItemObscurator;
import me.halfcooler.ic2r.core.item.tool.ItemRemote;
import me.halfcooler.ic2r.core.item.tool.ItemScanner;
import me.halfcooler.ic2r.core.item.tool.ItemScannerAdv;
import me.halfcooler.ic2r.core.item.tool.ItemToolCrafting;
import me.halfcooler.ic2r.core.item.tool.ItemToolCrowbar;
import me.halfcooler.ic2r.core.item.tool.ItemToolCutter;
import me.halfcooler.ic2r.core.item.tool.ItemToolMeter;
import me.halfcooler.ic2r.core.item.tool.ItemToolMiningLaser;
import me.halfcooler.ic2r.core.item.tool.ItemToolPainter;
import me.halfcooler.ic2r.core.item.tool.ItemToolWrench;
import me.halfcooler.ic2r.core.item.tool.ItemToolWrenchElectric;
import me.halfcooler.ic2r.core.item.tool.ItemToolbox;
import me.halfcooler.ic2r.core.item.tool.ItemTreetap;
import me.halfcooler.ic2r.core.item.tool.ItemTreetapElectric;
import me.halfcooler.ic2r.core.item.tool.ItemWindMeter;
import me.halfcooler.ic2r.core.ref.Ic2rEntities;
import me.halfcooler.ic2r.core.ref.Ic2rItems;
import me.halfcooler.ic2r.core.ref.Ic2rToolMaterials;
import me.halfcooler.ic2r.core.util.Ic2rColor;

/** Domain item registrations: Tools, painters, boats, batteries, rotors */
public final class Ic2rItemsTools
{
	private Ic2rItemsTools()
	{
	}

	public static final Item CUTTER = Ic2rItems.register("cutter", new ItemToolCutter(new Properties().durability(60)));
	public static final Item DEBUG_ITEM = Ic2rItems.register("debug_item", new ItemDebug(new Properties().stacksTo(1)));
	public static final Item FORGE_HAMMER = Ic2rItems.register("forge_hammer", new ItemToolCrafting(new Properties().durability(80)));
	public static final Item TOOL_BOX = Ic2rItems.register("tool_box", new ItemToolbox(new Properties().stacksTo(1)));
	public static final Item CONTAINMENT_BOX = Ic2rItems.register("containment_box", new ItemContainmentbox(new Properties().stacksTo(1)));
	public static final Item METER = Ic2rItems.register("meter", new ItemToolMeter(new Properties().stacksTo(1)));
	public static final Item TREETAP = Ic2rItems.register("treetap", new ItemTreetap(new Properties().durability(16)));
	public static final Item WRENCH = Ic2rItems.register("wrench", new ItemToolWrench(new Properties().durability(120)));
	public static final Item BRONZE_AXE = Ic2rItems.register("bronze_axe", new Ic2rAxe(Ic2rToolMaterials.BRONZE, 6.0F, -3.1F, new Properties()));
	public static final Item BRONZE_HOE = Ic2rItems.register("bronze_hoe", new Ic2rHoe(Ic2rToolMaterials.BRONZE, -2, -1.0F, new Properties()));
	public static final Item BRONZE_SWORD = Ic2rItems.register("bronze_sword", new SwordItem(Ic2rToolMaterials.BRONZE, 3, -2.4F, new Properties()));
	public static final Item BRONZE_SHOVEL = Ic2rItems.register("bronze_shovel", new ShovelItem(Ic2rToolMaterials.BRONZE, 1.5F, -3.0F, new Properties()));
	public static final Item BRONZE_PICKAXE = Ic2rItems.register("bronze_pickaxe", new Ic2rPickaxe(Ic2rToolMaterials.BRONZE, 1, -2.8F, new Properties()));
	public static final Item FREQUENCY_TRANSMITTER = Ic2rItems.register("frequency_transmitter", new ItemFrequencyTransmitter(new Properties().stacksTo(1)));
	public static final Item REMOTE = Ic2rItems.register("remote", new ItemRemote(new Properties()));
	public static final Item MINING_FILTER_CARD = Ic2rItems.register("mining_filter_card", new ItemMiningFilterCard(new Properties().stacksTo(1)));
	public static final Item CROWBAR = Ic2rItems.register("crowbar", new ItemToolCrowbar(Tiers.IRON, new Properties().durability(250)));
	public static final Item ADVANCED_SCANNER = Ic2rItems.register("advanced_scanner", new ItemScannerAdv(new Properties().stacksTo(1)));
	public static final Item CHAINSAW = Ic2rItems.register("chainsaw", new ItemElectricToolChainsaw(new Properties().stacksTo(1)));
	public static final Item DIAMOND_DRILL = Ic2rItems.register("diamond_drill", new ItemDrill(new Properties().stacksTo(1), 80, Tiers.DIAMOND, 30000, 100, 1, 16.0F));
	public static final Item DRILL = Ic2rItems.register("drill", new ItemDrill(new Properties().stacksTo(1), 50, Tiers.IRON, 30000, 100, 1, 8.0F));
	public static final Item MINING_LASER = Ic2rItems.register("mining_laser", new ItemToolMiningLaser(new Properties().stacksTo(1)));
	public static final Item ELECTRIC_TREETAP = Ic2rItems.register("electric_treetap", new ItemTreetapElectric(new Properties().stacksTo(1)));
	public static final Item ELECTRIC_WRENCH = Ic2rItems.register("electric_wrench", new ItemToolWrenchElectric(new Properties().stacksTo(1)));
	public static final Item IRIDIUM_DRILL = Ic2rItems.register("iridium_drill", new ItemDrillIridium(new Properties().stacksTo(1)));
	public static final Item OBSCURATOR = Ic2rItems.register("obscurator", new ItemObscurator(new Properties().stacksTo(1)));
	public static final Item SCANNER = Ic2rItems.register("scanner", new ItemScanner(new Properties().stacksTo(1), 100000.0, 128.0, 1));
	public static final Item WIND_METER = Ic2rItems.register("wind_meter", new ItemWindMeter(new Properties().stacksTo(1)));
	public static final Item PAINTER = Ic2rItems.register("painter", new ItemToolPainter(new Properties().stacksTo(1).durability(32), null));
	public static final Item BLACK_PAINTER = Ic2rItems.register("black_painter", new ItemToolPainter(new Properties().stacksTo(1).durability(32), Ic2rColor.BLACK));
	public static final Item BLUE_PAINTER = Ic2rItems.register("blue_painter", new ItemToolPainter(new Properties().stacksTo(1).durability(32), Ic2rColor.BLUE));
	public static final Item BROWN_PAINTER = Ic2rItems.register("brown_painter", new ItemToolPainter(new Properties().stacksTo(1).durability(32), Ic2rColor.BROWN));
	public static final Item CYAN_PAINTER = Ic2rItems.register("cyan_painter", new ItemToolPainter(new Properties().stacksTo(1).durability(32), Ic2rColor.CYAN));
	public static final Item GRAY_PAINTER = Ic2rItems.register("gray_painter", new ItemToolPainter(new Properties().stacksTo(1).durability(32), Ic2rColor.GRAY));
	public static final Item GREEN_PAINTER = Ic2rItems.register("green_painter", new ItemToolPainter(new Properties().stacksTo(1).durability(32), Ic2rColor.GREEN));
	public static final Item LIGHT_BLUE_PAINTER = Ic2rItems.register("light_blue_painter", new ItemToolPainter(new Properties().stacksTo(1).durability(32), Ic2rColor.LIGHT_BLUE));
	public static final Item LIGHT_GRAY_PAINTER = Ic2rItems.register("light_gray_painter", new ItemToolPainter(new Properties().stacksTo(1).durability(32), Ic2rColor.LIGHT_GRAY));
	public static final Item LIME_PAINTER = Ic2rItems.register("lime_painter", new ItemToolPainter(new Properties().stacksTo(1).durability(32), Ic2rColor.LIME));
	public static final Item MAGENTA_PAINTER = Ic2rItems.register("magenta_painter", new ItemToolPainter(new Properties().stacksTo(1).durability(32), Ic2rColor.MAGENTA));
	public static final Item ORANGE_PAINTER = Ic2rItems.register("orange_painter", new ItemToolPainter(new Properties().stacksTo(1).durability(32), Ic2rColor.ORANGE));
	public static final Item PINK_PAINTER = Ic2rItems.register("pink_painter", new ItemToolPainter(new Properties().stacksTo(1).durability(32), Ic2rColor.PINK));
	public static final Item PURPLE_PAINTER = Ic2rItems.register("purple_painter", new ItemToolPainter(new Properties().stacksTo(1).durability(32), Ic2rColor.PURPLE));
	public static final Item RED_PAINTER = Ic2rItems.register("red_painter", new ItemToolPainter(new Properties().stacksTo(1).durability(32), Ic2rColor.RED));
	public static final Item WHITE_PAINTER = Ic2rItems.register("white_painter", new ItemToolPainter(new Properties().stacksTo(1).durability(32), Ic2rColor.WHITE));
	public static final Item YELLOW_PAINTER = Ic2rItems.register("yellow_painter", new ItemToolPainter(new Properties().stacksTo(1).durability(32), Ic2rColor.YELLOW));
	public static final Item BROKEN_RUBBER_BOAT = Ic2rItems.register("broken_rubber_boat", new Item(new Properties().stacksTo(1)));
	public static final Item RUBBER_BOAT = Ic2rItems.register("rubber_boat", new BoatItem(RubberBoatEntity.class, Ic2rEntities.RUBBER_BOAT, new Properties().stacksTo(1)));
	public static final Item ELECTRIC_BOAT = Ic2rItems.register("electric_boat", new BoatItem(ElectricBoatEntity.class, Ic2rEntities.ELECTRIC_BOAT, new Properties().stacksTo(1)));
	public static final Item CARBON_BOAT = Ic2rItems.register("carbon_boat", new BoatItem(CarbonBoatEntity.class, Ic2rEntities.CARBON_BOAT, new Properties().stacksTo(1)));
	public static final Item RE_BATTERY = Ic2rItems.register("re_battery", new ItemBattery(new Properties(), 10000.0, 100.0, 1));
	public static final Item ADVANCED_RE_BATTERY = Ic2rItems.register("advanced_re_battery", new ItemBattery(new Properties().stacksTo(16), 100000.0, 256.0, 2));
	public static final Item ENERGY_CRYSTAL = Ic2rItems.register("energy_crystal", new ItemBattery(new Properties().stacksTo(16), 1000000.0, 2048.0, 3));
	public static final Item LAPOTRON_CRYSTAL = Ic2rItems.register("lapotron_crystal", new ItemBattery(new Properties().stacksTo(16).rarity(Rarity.UNCOMMON), 1.0E7, 8092.0, 4));
	public static final Item SINGLE_USE_BATTERY = Ic2rItems.register("single_use_battery", new ItemBatterySU(new Properties(), 1200, 1));
	public static final Item CHARGING_RE_BATTERY = Ic2rItems.register("charging_re_battery", new ItemBatteryChargeHotbar(new Properties().stacksTo(16), 40000.0, 128.0, 1));
	public static final Item ADVANCED_CHARGING_RE_BATTERY = Ic2rItems.register("advanced_charging_re_battery", new ItemBatteryChargeHotbar(new Properties().stacksTo(16), 400000.0, 1024.0, 2));
	public static final Item CHARGING_ENERGY_CRYSTAL = Ic2rItems.register("charging_energy_crystal", new ItemBatteryChargeHotbar(new Properties().stacksTo(16), 4000000.0, 8192.0, 3));
	public static final Item CHARGING_LAPOTRON_CRYSTAL = Ic2rItems.register("charging_lapotron_crystal", new ItemBatteryChargeHotbar(new Properties().stacksTo(16).rarity(Rarity.UNCOMMON), 4.0E7, 32768.0, 4));
	public static final Item WOODEN_ROTOR = Ic2rItems.register("wooden_rotor", new ItemWindRotor(new Properties().durability(10800), 5, false, 0.25F, 10, 60, IC2R.getIdentifier("textures/item/rotor/wood_rotor_model.png")));
	public static final Item BRONZE_ROTOR = Ic2rItems.register("bronze_rotor", new ItemWindRotor(new Properties().durability(86400), 7, true, 0.5F, 14, 75, ResourceLocation.fromNamespaceAndPath("ic2r", "textures/item/rotor/bronze_rotor_model.png")));
	public static final Item IRON_ROTOR = Ic2rItems.register("iron_rotor", new ItemWindRotor(new Properties().durability(86400), 7, true, 0.5F, 14, 75, ResourceLocation.fromNamespaceAndPath("ic2r", "textures/item/rotor/iron_rotor_model.png")));
	public static final Item STEEL_ROTOR = Ic2rItems.register("steel_rotor", new ItemWindRotor(new Properties().durability(172800), 9, true, 0.75F, 17, 90, ResourceLocation.fromNamespaceAndPath("ic2r", "textures/item/rotor/steel_rotor_model.png")));
	public static final Item CARBON_ROTOR = Ic2rItems.register("carbon_rotor", new ItemWindRotor(new Properties().durability(604800), 11, true, 1.0F, 20, 110, ResourceLocation.fromNamespaceAndPath("ic2r", "textures/item/rotor/carbon_rotor_model.png")));
}
