package me.halfcooler.ic2r.core.ref.items;

import java.util.List;
import javax.annotation.Nullable;
import org.jetbrains.annotations.NotNull;
import net.minecraft.network.chat.Component;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.Item.Properties;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.item.Rarity;
import net.minecraft.world.item.TooltipFlag;
import net.minecraft.world.level.Level;
import me.halfcooler.ic2r.core.item.ItemCoke;
import me.halfcooler.ic2r.core.item.ItemCrystalMemory;
import me.halfcooler.ic2r.core.item.ItemNuclearResource;
import me.halfcooler.ic2r.core.item.crafting.BlockCuttingBlade;
import me.halfcooler.ic2r.core.item.type.BlockCuttingBladeType;
import me.halfcooler.ic2r.core.ref.Ic2rItems;
import me.halfcooler.ic2r.core.util.Ic2rTooltip;

/** Domain item registrations: Resources and crafting materials */
public final class Ic2rItemsMaterials
{
	private Ic2rItemsMaterials()
	{
	}

	public static final Item RAW_LEAD = Ic2rItems.register("raw_lead", new Item(new Properties()));
	public static final Item RAW_TIN = Ic2rItems.register("raw_tin", new Item(new Properties()));
	public static final Item RAW_URANIUM = Ic2rItems.register("raw_uranium", new Item(new Properties()));
	public static final Item CRUSHED_COPPER = Ic2rItems.register("crushed_copper", new Item(new Properties()));
	public static final Item CRUSHED_GOLD = Ic2rItems.register("crushed_gold", new Item(new Properties()));
	public static final Item CRUSHED_IRON = Ic2rItems.register("crushed_iron", new Item(new Properties()));
	public static final Item CRUSHED_LEAD = Ic2rItems.register("crushed_lead", new Item(new Properties()));
	public static final Item CRUSHED_SILVER = Ic2rItems.register("crushed_silver", new Item(new Properties()));
	public static final Item CRUSHED_TIN = Ic2rItems.register("crushed_tin", new Item(new Properties()));
	public static final Item CRUSHED_URANIUM = Ic2rItems.register("crushed_uranium", new Item(new Properties()));
	public static final Item PURIFIED_COPPER = Ic2rItems.register("purified_copper", new Item(new Properties()));
	public static final Item PURIFIED_GOLD = Ic2rItems.register("purified_gold", new Item(new Properties()));
	public static final Item PURIFIED_IRON = Ic2rItems.register("purified_iron", new Item(new Properties()));
	public static final Item PURIFIED_LEAD = Ic2rItems.register("purified_lead", new Item(new Properties()));
	public static final Item PURIFIED_SILVER = Ic2rItems.register("purified_silver", new Item(new Properties()));
	public static final Item PURIFIED_TIN = Ic2rItems.register("purified_tin", new Item(new Properties()));
	public static final Item PURIFIED_URANIUM = Ic2rItems.register("purified_uranium", new Item(new Properties()));
	public static final Item BRONZE_DUST = Ic2rItems.register("bronze_dust", new Item(new Properties()));
	public static final Item CLAY_DUST = Ic2rItems.register("clay_dust", new Item(new Properties()));
	public static final Item COAL_DUST = Ic2rItems.register("coal_dust", new Item(new Properties()));
	public static final Item COAL_FUEL_DUST = Ic2rItems.register("coal_fuel_dust", new Item(new Properties()));
	public static final Item COPPER_DUST = Ic2rItems.register("copper_dust", new Item(new Properties()));
	public static final Item DIAMOND_DUST = Ic2rItems.register("diamond_dust", new Item(new Properties()));
	public static final Item ENERGIUM_DUST = Ic2rItems.register("energium_dust", new Item(new Properties()));
	public static final Item GOLD_DUST = Ic2rItems.register("gold_dust", new Item(new Properties()));
	public static final Item IRON_DUST = Ic2rItems.register("iron_dust", new Item(new Properties()));
	public static final Item LAPIS_DUST = Ic2rItems.register("lapis_dust", new Item(new Properties()));
	public static final Item LEAD_DUST = Ic2rItems.register("lead_dust", new Item(new Properties()));
	public static final Item LITHIUM_DUST = Ic2rItems.register("lithium_dust", new Item(new Properties()));
	public static final Item OBSIDIAN_DUST = Ic2rItems.register("obsidian_dust", new Item(new Properties()));
	public static final Item SILICON_DIOXIDE_DUST = Ic2rItems.register("silicon_dioxide_dust", new Item(new Properties()));
	public static final Item SILVER_DUST = Ic2rItems.register("silver_dust", new Item(new Properties()));
	public static final Item STONE_DUST = Ic2rItems.register("stone_dust", new Item(new Properties()));
	public static final Item SULFUR_DUST = Ic2rItems.register("sulfur_dust", new Item(new Properties()));
	public static final Item TIN_DUST = Ic2rItems.register("tin_dust", new Item(new Properties()));
	public static final Item SMALL_BRONZE_DUST = Ic2rItems.register("small_bronze_dust", new Item(new Properties()));
	public static final Item SMALL_COPPER_DUST = Ic2rItems.register("small_copper_dust", new Item(new Properties()));
	public static final Item SMALL_GOLD_DUST = Ic2rItems.register("small_gold_dust", new Item(new Properties()));
	public static final Item SMALL_IRON_DUST = Ic2rItems.register("small_iron_dust", new Item(new Properties()));
	public static final Item SMALL_LAPIS_DUST = Ic2rItems.register("small_lapis_dust", new Item(new Properties()));
	public static final Item SMALL_LEAD_DUST = Ic2rItems.register("small_lead_dust", new Item(new Properties()));
	public static final Item SMALL_LITHIUM_DUST = Ic2rItems.register("small_lithium_dust", new Item(new Properties()));
	public static final Item SMALL_OBSIDIAN_DUST = Ic2rItems.register("small_obsidian_dust", new Item(new Properties()));
	public static final Item SMALL_SILVER_DUST = Ic2rItems.register("small_silver_dust", new Item(new Properties()));
	public static final Item SMALL_SULFUR_DUST = Ic2rItems.register("small_sulfur_dust", new Item(new Properties()));
	public static final Item SMALL_TIN_DUST = Ic2rItems.register("small_tin_dust", new Item(new Properties()));
	public static final Item HYDRATED_TIN_DUST = Ic2rItems.register("hydrated_tin_dust", new Item(new Properties()));
	public static final Item NETHERRACK_DUST = Ic2rItems.register("netherrack_dust", new Item(new Properties()));
	public static final Item MIXED_METAL_INGOT = Ic2rItems.register("mixed_metal_ingot", new Item(new Properties()));
	public static final Item BRONZE_INGOT = Ic2rItems.register("bronze_ingot", new Item(new Properties()));
	public static final Item LEAD_INGOT = Ic2rItems.register("lead_ingot", new Item(new Properties()));
	public static final Item SILVER_INGOT = Ic2rItems.register("silver_ingot", new Item(new Properties()));
	public static final Item STEEL_INGOT = Ic2rItems.register("steel_ingot", new Item(new Properties()));
	public static final Item TIN_INGOT = Ic2rItems.register("tin_ingot", new Item(new Properties()));
	public static final Item URANIUM_INGOT = Ic2rItems.register("uranium_ingot", new Item(new Properties()));
	public static final Item BRONZE_PLATE = Ic2rItems.register("bronze_plate", new Item(new Properties()));
	public static final Item COPPER_PLATE = Ic2rItems.register("copper_plate", new Item(new Properties()));
	public static final Item GOLD_PLATE = Ic2rItems.register("gold_plate", new Item(new Properties()));
	public static final Item IRON_PLATE = Ic2rItems.register("iron_plate", new Item(new Properties()));
	public static final Item LAPIS_PLATE = Ic2rItems.register("lapis_plate", new Item(new Properties()));
	public static final Item LEAD_PLATE = Ic2rItems.register("lead_plate", new Item(new Properties()));
	public static final Item OBSIDIAN_PLATE = Ic2rItems.register("obsidian_plate", new Item(new Properties()));
	public static final Item STEEL_PLATE = Ic2rItems.register("steel_plate", new Item(new Properties()));
	public static final Item TIN_PLATE = Ic2rItems.register("tin_plate", new Item(new Properties()));
	public static final Item DENSE_BRONZE_PLATE = Ic2rItems.register("dense_bronze_plate", new Item(new Properties()));
	public static final Item DENSE_COPPER_PLATE = Ic2rItems.register("dense_copper_plate", new Item(new Properties()));
	public static final Item DENSE_GOLD_PLATE = Ic2rItems.register("dense_gold_plate", new Item(new Properties()));
	public static final Item DENSE_IRON_PLATE = Ic2rItems.register("dense_iron_plate", new Item(new Properties()));
	public static final Item DENSE_LAPIS_PLATE = Ic2rItems.register("dense_lapis_plate", new Item(new Properties()));
	public static final Item DENSE_LEAD_PLATE = Ic2rItems.register("dense_lead_plate", new Item(new Properties()));
	public static final Item DENSE_OBSIDIAN_PLATE = Ic2rItems.register("dense_obsidian_plate", new Item(new Properties()));
	public static final Item DENSE_STEEL_PLATE = Ic2rItems.register("dense_steel_plate", new Item(new Properties()));
	public static final Item DENSE_TIN_PLATE = Ic2rItems.register("dense_tin_plate", new Item(new Properties()));
	public static final Item BRONZE_CASING = Ic2rItems.register("bronze_casing", new Item(new Properties()));
	public static final Item COPPER_CASING = Ic2rItems.register("copper_casing", new Item(new Properties()));
	public static final Item GOLD_CASING = Ic2rItems.register("gold_casing", new Item(new Properties()));
	public static final Item IRON_CASING = Ic2rItems.register("iron_casing", new Item(new Properties()));
	public static final Item LEAD_CASING = Ic2rItems.register("lead_casing", new Item(new Properties()));
	public static final Item STEEL_CASING = Ic2rItems.register("steel_casing", new Item(new Properties()));
	public static final Item TIN_CASING = Ic2rItems.register("tin_casing", new Item(new Properties()));
	public static final Item URANIUM = Ic2rItems.register("uranium", new ItemNuclearResource(new Properties(), 60, 100));
	public static final Item URANIUM_235 = Ic2rItems.register("uranium_235", new ItemNuclearResource(new Properties(), 150, 100));
	public static final Item URANIUM_238 = Ic2rItems.register("uranium_238", new ItemNuclearResource(new Properties(), 10, 90));
	public static final Item PLUTONIUM = Ic2rItems.register("plutonium", new ItemNuclearResource(new Properties(), 150, 100));
	public static final Item MOX = Ic2rItems.register("mox", new ItemNuclearResource(new Properties(), 300, 100));
	public static final Item SMALL_URANIUM_235 = Ic2rItems.register("small_uranium_235", new ItemNuclearResource(new Properties(), 150, 100));
	public static final Item SMALL_URANIUM_238 = Ic2rItems.register("small_uranium_238", new ItemNuclearResource(new Properties(), 10, 90));
	public static final Item SMALL_PLUTONIUM = Ic2rItems.register("small_plutonium", new ItemNuclearResource(new Properties(), 150, 100));
	public static final Item URANIUM_PELLET = Ic2rItems.register("uranium_pellet", new ItemNuclearResource(new Properties(), 60, 100));
	public static final Item RTG_PELLET = Ic2rItems.register("rtg_pellet", new ItemNuclearResource(new Properties().stacksTo(1), 2, 90));
	public static final Item DEPLETED_URANIUM_FUEL_ROD = Ic2rItems.register("depleted_uranium_fuel_rod", new ItemNuclearResource(new Properties(), 10, 100));
	public static final Item DEPLETED_DUAL_URANIUM_FUEL_ROD = Ic2rItems.register("depleted_dual_uranium_fuel_rod", new ItemNuclearResource(new Properties(), 10, 100));
	public static final Item DEPLETED_QUAD_URANIUM_FUEL_ROD = Ic2rItems.register("depleted_quad_uranium_fuel_rod", new ItemNuclearResource(new Properties(), 10, 100));
	public static final Item DEPLETED_MOX_FUEL_ROD = Ic2rItems.register("depleted_mox_fuel_rod", new ItemNuclearResource(new Properties(), 10, 100));
	public static final Item DEPLETED_DUAL_MOX_FUEL_ROD = Ic2rItems.register("depleted_dual_mox_fuel_rod", new ItemNuclearResource(new Properties(), 10, 100));
	public static final Item DEPLETED_QUAD_MOX_FUEL_ROD = Ic2rItems.register("depleted_quad_mox_fuel_rod", new ItemNuclearResource(new Properties(), 10, 100));
	public static final Item NEAR_DEPLETED_URANIUM = Ic2rItems.register("near_depleted_uranium", new ItemNuclearResource(new Properties(), 15, 100));
	public static final Item RE_ENRICHED_URANIUM = Ic2rItems.register("re_enriched_uranium", new ItemNuclearResource(new Properties(), 30, 100));
	public static final Item ASHES = Ic2rItems.register("ashes", new Item(new Properties()));
	public static final Item IRIDIUM_ORE = Ic2rItems.register("iridium_ore", new Item(new Properties().rarity(Rarity.RARE)));
	public static final Item IRIDIUM_SHARD = Ic2rItems.register("iridium_shard", new Item(new Properties().rarity(Rarity.UNCOMMON)));
	public static final Item RESIN = Ic2rItems.register("resin", new Item(new Properties()));
	public static final Item SLAG = Ic2rItems.register("slag", new Item(new Properties()));
	public static final Item COKE = Ic2rItems.register("coke", new ItemCoke());
	public static final Item IODINE = Ic2rItems.register("iodine", new Item(new Properties()));
	public static final Item WATER_SHEET = Ic2rItems.register("water_sheet", new Item(new Properties()));
	public static final Item LAVA_SHEET = Ic2rItems.register("lava_sheet", new Item(new Properties()));
	public static final Item RUBBER = Ic2rItems.register("rubber", new Item(new Properties()));
	public static final Item CIRCUIT = Ic2rItems.register("circuit", new Item(new Properties()));
	public static final Item ADVANCED_CIRCUIT = Ic2rItems.register("advanced_circuit", new Item(new Properties().rarity(Rarity.UNCOMMON)));
	public static final Item ALLOY = Ic2rItems.register("alloy", new Item(new Properties()));
	public static final Item IRIDIUM = Ic2rItems.register("iridium", new Item(new Properties().rarity(Rarity.RARE)));
	public static final Item COIL = Ic2rItems.register("coil", new Item(new Properties()));
	public static final Item ELECTRIC_MOTOR = Ic2rItems.register("electric_motor", new Item(new Properties()));
	public static final Item HEAT_CONDUCTOR = Ic2rItems.register("heat_conductor", new Item(new Properties()));
	public static final Item COPPER_BOILER = Ic2rItems.register("copper_boiler", new Item(new Properties()));
	public static final Item FUEL_ROD = Ic2rItems.register("fuel_rod", new Item(new Properties()));
	public static final Item TIN_CAN = Ic2rItems.register("tin_can", new Item(new Properties()));
	public static final Item IRON_CUTTING_BLADE = Ic2rItems.register("iron_cutting_blade", new BlockCuttingBlade(new Properties(), BlockCuttingBladeType.iron));
	public static final Item DIAMOND_CUTTING_BLADE = Ic2rItems.register("diamond_cutting_blade", new BlockCuttingBlade(new Properties(), BlockCuttingBladeType.diamond));
	public static final Item STEEL_CUTTING_BLADE = Ic2rItems.register("steel_cutting_blade", new BlockCuttingBlade(new Properties(), BlockCuttingBladeType.steel));
	public static final Item SMALL_POWER_UNIT = Ic2rItems.register("small_power_unit", new Item(new Properties()));
	public static final Item POWER_UNIT = Ic2rItems.register("power_unit", new Item(new Properties()));
	public static final Item CARBON_FIBRE = Ic2rItems.register("carbon_fibre", new Item(new Properties()));
	public static final Item CARBON_MESH = Ic2rItems.register("carbon_mesh", new Item(new Properties()));
	public static final Item CARBON_PLATE = Ic2rItems.register("carbon_plate", new Item(new Properties()));
	public static final Item COAL_BALL = Ic2rItems.register("coal_ball", new Item(new Properties()));
	public static final Item COAL_BLOCK = Ic2rItems.register("coal_block", new Item(new Properties()));
	public static final Item COAL_CHUNK = Ic2rItems.register("coal_chunk", new Item(new Properties()));
	public static final Item INDUTRIAL_DIAMOND = Ic2rItems.register("industrial_diamond", new Item(new Properties()));
	public static final Item PLANT_BALL = Ic2rItems.register("plant_ball", new Item(new Properties()));
	public static final Item BIO_CHAFF = Ic2rItems.register("bio_chaff", new Item(new Properties()));
	public static final Item SCRAP = Ic2rItems.register("scrap", new Item(new Properties()));
	public static final Item SCRAP_BOX = Ic2rItems.register("scrap_box", new Item(new Properties()));
	public static final Item CF_POWDER = Ic2rItems.register("cf_powder", new Item(new Properties()));
	public static final Item PELLET = Ic2rItems.register("pellet", new Item(new Properties()));
	public static final Item RAW_CRYSTAL_MEMORY = Ic2rItems.register("raw_crystal_memory", new Item(new Properties()));
	public static final Item CRYSTAL_MEMORY = Ic2rItems.register("crystal_memory", new ItemCrystalMemory(new Properties().stacksTo(1)));
	public static final Item IRON_SHAFT = Ic2rItems.register("iron_shaft", new Item(new Properties()));
	public static final Item STEEL_SHAFT = Ic2rItems.register("steel_shaft", new Item(new Properties()));
	public static final Item WOODEN_ROTOR_BLADE = Ic2rItems.register("wooden_rotor_blade", new Item(new Properties()));
	public static final Item IRON_ROTOR_BLADE = Ic2rItems.register("iron_rotor_blade", new Item(new Properties()));
	public static final Item STEEL_ROTOR_BLADE = Ic2rItems.register("steel_rotor_blade", new Item(new Properties()));
	public static final Item CARBON_ROTOR_BLADE = Ic2rItems.register("carbon_rotor_blade", new Item(new Properties()));
	public static final Item STEAM_TURBINE_BLADE = Ic2rItems.register("steam_turbine_blade", new Item(new Properties()));
	public static final Item STEAM_TURBINE = Ic2rItems.register("steam_turbine", new Item(new Properties()));
	public static final Item JETPACK_ATTACHMENT_PLATE = Ic2rItems.register("jetpack_attachment_plate", new Item(new Properties())
	{
		@Override
		public void appendHoverText(@NotNull ItemStack item, @Nullable Level level, @NotNull List<Component> components, @NotNull TooltipFlag flag)
		{
			Ic2rTooltip.add(components, Component.translatable("ic2r.tooltip.jetpack_attachment.craft"));
			Ic2rTooltip.add(components, Component.translatable("ic2r.tooltip.jetpack_attachment.attach"));
			Ic2rTooltip.add(components, Component.translatable("ic2r.tooltip.jetpack_attachment.warning"));
		}
	});
	public static final Item COIN = Ic2rItems.register("coin", new Item(new Properties()));
	public static final Item BRONZE_ROTOR_BLADE = Ic2rItems.register("bronze_rotor_blade", new Item(new Properties()));
	public static final Item BRONZE_SHAFT = Ic2rItems.register("bronze_shaft", new Item(new Properties()));
}
