package me.halfcooler.ic2r.core.ref.items;

import net.minecraft.world.item.DoubleHighBlockItem;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.Item.Properties;
import net.minecraft.world.item.Rarity;
import net.minecraft.world.item.SignItem;
import me.halfcooler.ic2r.core.item.BlockItemEnergyStorage;
import me.halfcooler.ic2r.core.item.ItemBlockIc2r;
import me.halfcooler.ic2r.core.item.ItemCable;
import me.halfcooler.ic2r.core.item.block.ItemDynamite;
import me.halfcooler.ic2r.core.ref.Ic2rBlocks;
import me.halfcooler.ic2r.core.ref.Ic2rItems;

/** Domain item registrations: Block items (ores, machines, cables, generators, etc.) */
public final class Ic2rItemsBlockItems
{
	private Ic2rItemsBlockItems()
	{
	}

	public static final Item LEAD_ORE = Ic2rItems.register("lead_ore", new ItemBlockIc2r(Ic2rBlocks.LEAD_ORE.get(), new Properties()));
	public static final Item TIN_ORE = Ic2rItems.register("tin_ore", new ItemBlockIc2r(Ic2rBlocks.TIN_ORE.get(), new Properties()));
	public static final Item URANIUM_ORE = Ic2rItems.register("uranium_ore", new ItemBlockIc2r(Ic2rBlocks.URANIUM_ORE.get(), new Properties()));
	public static final Item DEEPSLATE_URANIUM_ORE = Ic2rItems.register("deepslate_uranium_ore", new ItemBlockIc2r(Ic2rBlocks.DEEPSLATE_URANIUM_ORE.get(), new Properties()));
	public static final Item DEEPSLATE_TIN_ORE = Ic2rItems.register("deepslate_tin_ore", new ItemBlockIc2r(Ic2rBlocks.DEEPSLATE_TIN_ORE.get(), new Properties()));
	public static final Item DEEPSLATE_LEAD_ORE = Ic2rItems.register("deepslate_lead_ore", new ItemBlockIc2r(Ic2rBlocks.DEEPSLATE_LEAD_ORE.get(), new Properties()));
	public static final Item RAW_LEAD_BLOCK = Ic2rItems.register("raw_lead_block", new ItemBlockIc2r(Ic2rBlocks.RAW_LEAD_BLOCK.get(), new Properties()));
	public static final Item RAW_TIN_BLOCK = Ic2rItems.register("raw_tin_block", new ItemBlockIc2r(Ic2rBlocks.RAW_TIN_BLOCK.get(), new Properties()));
	public static final Item RAW_URANIUM_BLOCK = Ic2rItems.register("raw_uranium_block", new ItemBlockIc2r(Ic2rBlocks.RAW_URANIUM_BLOCK.get(), new Properties()));
	public static final Item BRONZE_BLOCK = Ic2rItems.register("bronze_block", new ItemBlockIc2r(Ic2rBlocks.BRONZE_BLOCK.get(), new Properties()));
	public static final Item LEAD_BLOCK = Ic2rItems.register("lead_block", new ItemBlockIc2r(Ic2rBlocks.LEAD_BLOCK.get(), new Properties()));
	public static final Item STEEL_BLOCK = Ic2rItems.register("steel_block", new ItemBlockIc2r(Ic2rBlocks.STEEL_BLOCK.get(), new Properties()));
	public static final Item TIN_BLOCK = Ic2rItems.register("tin_block", new ItemBlockIc2r(Ic2rBlocks.TIN_BLOCK.get(), new Properties()));
	public static final Item URANIUM_BLOCK = Ic2rItems.register("uranium_block", new ItemBlockIc2r(Ic2rBlocks.URANIUM_BLOCK.get(), new Properties()));
	public static final Item REINFORCED_STONE = Ic2rItems.register("reinforced_stone", new ItemBlockIc2r(Ic2rBlocks.REINFORCED_STONE.get(), new Properties()));
	public static final Item REFRACTORY_BRICKS = Ic2rItems.register("refractory_bricks", new ItemBlockIc2r(Ic2rBlocks.REFRACTORY_BRICKS.get(), new Properties()));
	public static final Item MACHINE = Ic2rItems.register("machine", new ItemBlockIc2r(Ic2rBlocks.MACHINE.get(), new Properties()));
	public static final Item ADVANCED_MACHINE = Ic2rItems.register("advanced_machine", new ItemBlockIc2r(Ic2rBlocks.ADVANCED_MACHINE.get(), new Properties()));
	public static final Item SILVER_BLOCK = Ic2rItems.register("silver_block", new ItemBlockIc2r(Ic2rBlocks.SILVER_BLOCK.get(), new Properties()));
	public static final Item RUBBER_LEAVES = Ic2rItems.register("rubber_leaves", new ItemBlockIc2r(Ic2rBlocks.RUBBER_LEAVES.get(), new Properties()));
	public static final Item RUBBER_LOG = Ic2rItems.register("rubber_log", new ItemBlockIc2r(Ic2rBlocks.RUBBER_LOG.get(), new Properties()));
	public static final Item STRIPPED_RUBBER_LOG = Ic2rItems.register("stripped_rubber_log", new ItemBlockIc2r(Ic2rBlocks.STRIPPED_RUBBER_LOG.get(), new Properties()));
	public static final Item RUBBER_WOOD = Ic2rItems.register("rubber_wood", new ItemBlockIc2r(Ic2rBlocks.RUBBER_WOOD.get(), new Properties()));
	public static final Item STRIPPED_RUBBER_WOOD = Ic2rItems.register("stripped_rubber_wood", new ItemBlockIc2r(Ic2rBlocks.STRIPPED_RUBBER_WOOD.get(), new Properties()));
	public static final Item RUBBER_PLANKS = Ic2rItems.register("rubber_planks", new ItemBlockIc2r(Ic2rBlocks.RUBBER_PLANKS.get(), new Properties()));
	public static final Item RUBBER_SAPLING = Ic2rItems.register("rubber_sapling", new ItemBlockIc2r(Ic2rBlocks.RUBBER_SAPLING.get(), new Properties()));
	public static final Item RUBBER_BUTTON = Ic2rItems.register("rubber_button", new ItemBlockIc2r(Ic2rBlocks.RUBBER_BUTTON.get(), new Properties()));
	public static final Item RUBBER_DOOR = Ic2rItems.register("rubber_door", new ItemBlockIc2r(Ic2rBlocks.RUBBER_DOOR.get(), new Properties()));
	public static final Item RUBBER_FENCE = Ic2rItems.register("rubber_fence", new ItemBlockIc2r(Ic2rBlocks.RUBBER_FENCE.get(), new Properties()));
	public static final Item RUBBER_FENCE_GATE = Ic2rItems.register("rubber_fence_gate", new ItemBlockIc2r(Ic2rBlocks.RUBBER_FENCE_GATE.get(), new Properties()));
	public static final Item RUBBER_PRESSURE_PLATE = Ic2rItems.register("rubber_pressure_plate", new ItemBlockIc2r(Ic2rBlocks.RUBBER_PRESSURE_PLATE.get(), new Properties()));
	public static final Item RUBBER_SIGN = Ic2rItems.register("rubber_sign", new SignItem(new Properties(), Ic2rBlocks.RUBBER_SIGN.get(), Ic2rBlocks.RUBBER_WALL_SIGN.get()));
	public static final Item RUBBER_SLAB = Ic2rItems.register("rubber_slab", new ItemBlockIc2r(Ic2rBlocks.RUBBER_SLAB.get(), new Properties()));
	public static final Item RUBBER_STAIRS = Ic2rItems.register("rubber_stairs", new ItemBlockIc2r(Ic2rBlocks.RUBBER_STAIRS.get(), new Properties()));
	public static final Item RUBBER_TRAPDOOR = Ic2rItems.register("rubber_trapdoor", new ItemBlockIc2r(Ic2rBlocks.RUBBER_TRAPDOOR.get(), new Properties()));
	public static final Item MINING_PIPE = Ic2rItems.register("mining_pipe", new ItemBlockIc2r(Ic2rBlocks.MINING_PIPE.get(), new Properties()));
	public static final Item IRON_FENCE = Ic2rItems.register("iron_fence", new ItemBlockIc2r(Ic2rBlocks.IRON_FENCE.get(), new Properties()));
	public static final Item RESIN_SHEET = Ic2rItems.register("resin_sheet", new ItemBlockIc2r(Ic2rBlocks.RESIN_SHEET.get(), new Properties()));
	public static final Item RUBBER_SHEET = Ic2rItems.register("rubber_sheet", new ItemBlockIc2r(Ic2rBlocks.RUBBER_SHEET.get(), new Properties()));
	public static final Item WOOL_SHEET = Ic2rItems.register("wool_sheet", new ItemBlockIc2r(Ic2rBlocks.WOOL_SHEET.get(), new Properties()));
	public static final Item REINFORCED_GLASS = Ic2rItems.register("reinforced_glass", new ItemBlockIc2r(Ic2rBlocks.REINFORCED_GLASS.get(), new Properties()));
	public static final Item REINFORCED_DOOR = Ic2rItems.register("reinforced_door", new DoubleHighBlockItem(Ic2rBlocks.REINFORCED_DOOR.get(), new Properties()));
	public static final Item FOAM = Ic2rItems.register("foam", new ItemBlockIc2r(Ic2rBlocks.FOAM.get(), new Properties()));
	public static final Item WHITE_WALL = Ic2rItems.register("white_wall", new ItemBlockIc2r(Ic2rBlocks.WHITE_WALL.get(), new Properties()));
	public static final Item ORANGE_WALL = Ic2rItems.register("orange_wall", new ItemBlockIc2r(Ic2rBlocks.ORANGE_WALL.get(), new Properties()));
	public static final Item MAGENTA_WALL = Ic2rItems.register("magenta_wall", new ItemBlockIc2r(Ic2rBlocks.MAGENTA_WALL.get(), new Properties()));
	public static final Item LIGHT_BLUE_WALL = Ic2rItems.register("light_blue_wall", new ItemBlockIc2r(Ic2rBlocks.LIGHT_BLUE_WALL.get(), new Properties()));
	public static final Item YELLOW_WALL = Ic2rItems.register("yellow_wall", new ItemBlockIc2r(Ic2rBlocks.YELLOW_WALL.get(), new Properties()));
	public static final Item LIME_WALL = Ic2rItems.register("lime_wall", new ItemBlockIc2r(Ic2rBlocks.LIME_WALL.get(), new Properties()));
	public static final Item PINK_WALL = Ic2rItems.register("pink_wall", new ItemBlockIc2r(Ic2rBlocks.PINK_WALL.get(), new Properties()));
	public static final Item GRAY_WALL = Ic2rItems.register("gray_wall", new ItemBlockIc2r(Ic2rBlocks.GRAY_WALL.get(), new Properties()));
	public static final Item LIGHT_GRAY_WALL = Ic2rItems.register("light_gray_wall", new ItemBlockIc2r(Ic2rBlocks.LIGHT_GRAY_WALL.get(), new Properties()));
	public static final Item CYAN_WALL = Ic2rItems.register("cyan_wall", new ItemBlockIc2r(Ic2rBlocks.CYAN_WALL.get(), new Properties()));
	public static final Item PURPLE_WALL = Ic2rItems.register("purple_wall", new ItemBlockIc2r(Ic2rBlocks.PURPLE_WALL.get(), new Properties()));
	public static final Item BLUE_WALL = Ic2rItems.register("blue_wall", new ItemBlockIc2r(Ic2rBlocks.BLUE_WALL.get(), new Properties()));
	public static final Item BROWN_WALL = Ic2rItems.register("brown_wall", new ItemBlockIc2r(Ic2rBlocks.BROWN_WALL.get(), new Properties()));
	public static final Item GREEN_WALL = Ic2rItems.register("green_wall", new ItemBlockIc2r(Ic2rBlocks.GREEN_WALL.get(), new Properties()));
	public static final Item RED_WALL = Ic2rItems.register("red_wall", new ItemBlockIc2r(Ic2rBlocks.RED_WALL.get(), new Properties()));
	public static final Item BLACK_WALL = Ic2rItems.register("black_wall", new ItemBlockIc2r(Ic2rBlocks.BLACK_WALL.get(), new Properties()));
	public static final Item ITNT = Ic2rItems.register("itnt", new ItemBlockIc2r(Ic2rBlocks.ITNT.get(), new Properties()));
	public static final Item NUKE = Ic2rItems.register("nuke", new ItemBlockIc2r(Ic2rBlocks.NUKE.get(), new Properties().rarity(Rarity.UNCOMMON)));
	public static final Item DYNAMITE = Ic2rItems.register("dynamite", new ItemDynamite(new Properties(), false));
	public static final Item DYNAMITE_STICKY = Ic2rItems.register("dynamite_sticky", new ItemDynamite(new Properties(), true));
	public static final Item COPPER_CABLE = Ic2rItems.register("copper_cable", new ItemCable(Ic2rBlocks.COPPER_CABLE.get(), new Properties()));
	public static final Item INSULATED_COPPER_CABLE = Ic2rItems.register("insulated_copper_cable", new ItemCable(Ic2rBlocks.INSULATED_COPPER_CABLE.get(), new Properties()));
	public static final Item GLASS_FIBRE_CABLE = Ic2rItems.register("glass_fibre_cable", new ItemCable(Ic2rBlocks.GLASS_FIBRE_CABLE.get(), new Properties()));
	public static final Item GOLD_CABLE = Ic2rItems.register("gold_cable", new ItemCable(Ic2rBlocks.GOLD_CABLE.get(), new Properties()));
	public static final Item INSULATED_GOLD_CABLE = Ic2rItems.register("insulated_gold_cable", new ItemCable(Ic2rBlocks.INSULATED_GOLD_CABLE.get(), new Properties()));
	public static final Item DOUBLE_INSULATED_GOLD_CABLE = Ic2rItems.register("double_insulated_gold_cable", new ItemCable(Ic2rBlocks.DOUBLE_INSULATED_GOLD_CABLE.get(), new Properties()));
	public static final Item IRON_CABLE = Ic2rItems.register("iron_cable", new ItemCable(Ic2rBlocks.IRON_CABLE.get(), new Properties()));
	public static final Item INSULATED_IRON_CABLE = Ic2rItems.register("insulated_iron_cable", new ItemCable(Ic2rBlocks.INSULATED_IRON_CABLE.get(), new Properties()));
	public static final Item DOUBLE_INSULATED_IRON_CABLE = Ic2rItems.register("double_insulated_iron_cable", new ItemCable(Ic2rBlocks.DOUBLE_INSULATED_IRON_CABLE.get(), new Properties()));
	public static final Item TRIPLE_INSULATED_IRON_CABLE = Ic2rItems.register("triple_insulated_iron_cable", new ItemCable(Ic2rBlocks.TRIPLE_INSULATED_IRON_CABLE.get(), new Properties()));
	public static final Item TIN_CABLE = Ic2rItems.register("tin_cable", new ItemCable(Ic2rBlocks.TIN_CABLE.get(), new Properties()));
	public static final Item INSULATED_TIN_CABLE = Ic2rItems.register("insulated_tin_cable", new ItemCable(Ic2rBlocks.INSULATED_TIN_CABLE.get(), new Properties()));
	public static final Item DETECTOR_CABLE = Ic2rItems.register("detector_cable", new ItemCable(Ic2rBlocks.DETECTOR_CABLE.get(), new Properties()));
	public static final Item SPLITTER_CABLE = Ic2rItems.register("splitter_cable", new ItemCable(Ic2rBlocks.SPLITTER_CABLE.get(), new Properties()));
	public static final Item BATBOX_CHARGEPAD = Ic2rItems.register("batbox_chargepad", new BlockItemEnergyStorage(Ic2rBlocks.BATBOX_CHARGEPAD.get(), new Properties(), 40000));
	public static final Item CESU_CHARGEPAD = Ic2rItems.register("cesu_chargepad", new BlockItemEnergyStorage(Ic2rBlocks.CESU_CHARGEPAD.get(), new Properties(), 300000));
	public static final Item MFE_CHARGEPAD = Ic2rItems.register("mfe_chargepad", new BlockItemEnergyStorage(Ic2rBlocks.MFE_CHARGEPAD.get(), new Properties(), 4000000));
	public static final Item MFSU_CHARGEPAD = Ic2rItems.register("mfsu_chargepad", new BlockItemEnergyStorage(Ic2rBlocks.MFSU_CHARGEPAD.get(), new Properties().rarity(Rarity.UNCOMMON), 40000000));
	public static final Item BATBOX = Ic2rItems.register("batbox", new BlockItemEnergyStorage(Ic2rBlocks.BATBOX.get(), new Properties(), 40000));
	public static final Item CESU = Ic2rItems.register("cesu", new BlockItemEnergyStorage(Ic2rBlocks.CESU.get(), new Properties(), 300000));
	public static final Item MFE = Ic2rItems.register("mfe", new BlockItemEnergyStorage(Ic2rBlocks.MFE.get(), new Properties(), 4000000));
	public static final Item MFSU = Ic2rItems.register("mfsu", new BlockItemEnergyStorage(Ic2rBlocks.MFSU.get(), new Properties().rarity(Rarity.UNCOMMON), 40000000));
	public static final Item LV_TRANSFORMER = Ic2rItems.register("lv_transformer", new ItemBlockIc2r(Ic2rBlocks.LV_TRANSFORMER.get(), new Properties()));
	public static final Item MV_TRANSFORMER = Ic2rItems.register("mv_transformer", new ItemBlockIc2r(Ic2rBlocks.MV_TRANSFORMER.get(), new Properties()));
	public static final Item HV_TRANSFORMER = Ic2rItems.register("hv_transformer", new ItemBlockIc2r(Ic2rBlocks.HV_TRANSFORMER.get(), new Properties().rarity(Rarity.UNCOMMON)));
	public static final Item EV_TRANSFORMER = Ic2rItems.register("ev_transformer", new ItemBlockIc2r(Ic2rBlocks.EV_TRANSFORMER.get(), new Properties().rarity(Rarity.UNCOMMON)));
	public static final Item TANK = Ic2rItems.register("tank", new ItemBlockIc2r(Ic2rBlocks.TANK.get(), new Properties()));
	public static final Item STEAM_REPRESSURIZER = Ic2rItems.register("steam_repressurizer", new ItemBlockIc2r(Ic2rBlocks.STEAM_REPRESSURIZER.get(), new Properties()));
	public static final Item WEIGHTED_FLUID_DISTRIBUTOR = Ic2rItems.register("weighted_fluid_distributor", new ItemBlockIc2r(Ic2rBlocks.WEIGHTED_FLUID_DISTRIBUTOR.get(), new Properties()));
	public static final Item WEIGHTED_ITEM_DISTRIBUTOR = Ic2rItems.register("weighted_item_distributor", new ItemBlockIc2r(Ic2rBlocks.WEIGHTED_ITEM_DISTRIBUTOR.get(), new Properties()));
	public static final Item RCI_RSH = Ic2rItems.register("rci_rsh", new ItemBlockIc2r(Ic2rBlocks.RCI_RSH.get(), new Properties()));
	public static final Item RCI_LZH = Ic2rItems.register("rci_lzh", new ItemBlockIc2r(Ic2rBlocks.RCI_LZH.get(), new Properties()));
	public static final Item INDUSTRIAL_WORKBENCH = Ic2rItems.register("industrial_workbench", new ItemBlockIc2r(Ic2rBlocks.INDUSTRIAL_WORKBENCH.get(), new Properties()));
	public static final Item BATCH_CRAFTER = Ic2rItems.register("batch_crafter", new ItemBlockIc2r(Ic2rBlocks.BATCH_CRAFTER.get(), new Properties().rarity(Rarity.UNCOMMON)));
	public static final Item WOODEN_STORAGE_BOX = Ic2rItems.register("wooden_storage_box", new ItemBlockIc2r(Ic2rBlocks.WOODEN_STORAGE_BOX.get(), new Properties()));
	public static final Item IRON_STORAGE_BOX = Ic2rItems.register("iron_storage_box", new ItemBlockIc2r(Ic2rBlocks.IRON_STORAGE_BOX.get(), new Properties()));
	public static final Item BRONZE_STORAGE_BOX = Ic2rItems.register("bronze_storage_box", new ItemBlockIc2r(Ic2rBlocks.BRONZE_STORAGE_BOX.get(), new Properties()));
	public static final Item STEEL_STORAGE_BOX = Ic2rItems.register("steel_storage_box", new ItemBlockIc2r(Ic2rBlocks.STEEL_STORAGE_BOX.get(), new Properties().rarity(Rarity.UNCOMMON)));
	public static final Item IRIDIUM_STORAGE_BOX = Ic2rItems.register("iridium_storage_box", new ItemBlockIc2r(Ic2rBlocks.IRIDIUM_STORAGE_BOX.get(), new Properties().rarity(Rarity.RARE)));
	public static final Item BRONZE_TANK = Ic2rItems.register("bronze_tank", new ItemBlockIc2r(Ic2rBlocks.BRONZE_TANK.get(), new Properties()));
	public static final Item IRON_TANK = Ic2rItems.register("iron_tank", new ItemBlockIc2r(Ic2rBlocks.IRON_TANK.get(), new Properties()));
	public static final Item STEEL_TANK = Ic2rItems.register("steel_tank", new ItemBlockIc2r(Ic2rBlocks.STEEL_TANK.get(), new Properties().rarity(Rarity.UNCOMMON)));
	public static final Item IRIDIUM_TANK = Ic2rItems.register("iridium_tank", new ItemBlockIc2r(Ic2rBlocks.IRIDIUM_TANK.get(), new Properties().rarity(Rarity.RARE)));
	public static final Item COKE_KILN = Ic2rItems.register("coke_kiln", new ItemBlockIc2r(Ic2rBlocks.COKE_KILN.get(), new Properties()));
	public static final Item COKE_KILN_HATCH = Ic2rItems.register("coke_kiln_hatch", new ItemBlockIc2r(Ic2rBlocks.COKE_KILN_HATCH.get(), new Properties()));
	public static final Item COKE_KILN_GRATE = Ic2rItems.register("coke_kiln_grate", new ItemBlockIc2r(Ic2rBlocks.COKE_KILN_GRATE.get(), new Properties()));
	public static final Item GENERATOR = Ic2rItems.register("generator", new ItemBlockIc2r(Ic2rBlocks.GENERATOR.get(), new Properties()));
	public static final Item GEO_GENERATOR = Ic2rItems.register("geo_generator", new ItemBlockIc2r(Ic2rBlocks.GEO_GENERATOR.get(), new Properties()));
	public static final Item KINETIC_GENERATOR = Ic2rItems.register("kinetic_generator", new ItemBlockIc2r(Ic2rBlocks.KINETIC_GENERATOR.get(), new Properties()));
	public static final Item RT_GENERATOR = Ic2rItems.register("rt_generator", new ItemBlockIc2r(Ic2rBlocks.RT_GENERATOR.get(), new Properties()));
	public static final Item SEMIFLUID_GENERATOR = Ic2rItems.register("semifluid_generator", new ItemBlockIc2r(Ic2rBlocks.SEMIFLUID_GENERATOR.get(), new Properties()));
	public static final Item SOLAR_GENERATOR = Ic2rItems.register("solar_generator", new ItemBlockIc2r(Ic2rBlocks.SOLAR_GENERATOR.get(), new Properties()));
	public static final Item STIRLING_GENERATOR = Ic2rItems.register("stirling_generator", new ItemBlockIc2r(Ic2rBlocks.STIRLING_GENERATOR.get(), new Properties()));
	public static final Item WATER_GENERATOR = Ic2rItems.register("water_generator", new ItemBlockIc2r(Ic2rBlocks.WATER_GENERATOR.get(), new Properties()));
	public static final Item WIND_GENERATOR = Ic2rItems.register("wind_generator", new ItemBlockIc2r(Ic2rBlocks.WIND_GENERATOR.get(), new Properties()));
	public static final Item CREATIVE_GENERATOR = Ic2rItems.register("creative_generator", new ItemBlockIc2r(Ic2rBlocks.CREATIVE_GENERATOR.get(), new Properties()));
	public static final Item ELECTRIC_HEAT_GENERATOR = Ic2rItems.register("electric_heat_generator", new ItemBlockIc2r(Ic2rBlocks.ELECTRIC_HEAT_GENERATOR.get(), new Properties()));
	public static final Item FLUID_HEAT_GENERATOR = Ic2rItems.register("fluid_heat_generator", new ItemBlockIc2r(Ic2rBlocks.FLUID_HEAT_GENERATOR.get(), new Properties()));
	public static final Item RT_HEAT_GENERATOR = Ic2rItems.register("rt_heat_generator", new ItemBlockIc2r(Ic2rBlocks.RT_HEAT_GENERATOR.get(), new Properties()));
	public static final Item SOLID_HEAT_GENERATOR = Ic2rItems.register("solid_heat_generator", new ItemBlockIc2r(Ic2rBlocks.SOLID_HEAT_GENERATOR.get(), new Properties()));
	public static final Item ELECTRIC_KINETIC_GENERATOR = Ic2rItems.register("electric_kinetic_generator", new ItemBlockIc2r(Ic2rBlocks.ELECTRIC_KINETIC_GENERATOR.get(), new Properties()));
	public static final Item MANUAL_KINETIC_GENERATOR = Ic2rItems.register("manual_kinetic_generator", new ItemBlockIc2r(Ic2rBlocks.MANUAL_KINETIC_GENERATOR.get(), new Properties()));
	public static final Item STEAM_KINETIC_GENERATOR = Ic2rItems.register("steam_kinetic_generator", new ItemBlockIc2r(Ic2rBlocks.STEAM_KINETIC_GENERATOR.get(), new Properties()));
	public static final Item STIRLING_KINETIC_GENERATOR = Ic2rItems.register("stirling_kinetic_generator", new ItemBlockIc2r(Ic2rBlocks.STIRLING_KINETIC_GENERATOR.get(), new Properties()));
	public static final Item WATER_KINETIC_GENERATOR = Ic2rItems.register("water_kinetic_generator", new ItemBlockIc2r(Ic2rBlocks.WATER_KINETIC_GENERATOR.get(), new Properties()));
	public static final Item WIND_KINETIC_GENERATOR = Ic2rItems.register("wind_kinetic_generator", new ItemBlockIc2r(Ic2rBlocks.WIND_KINETIC_GENERATOR.get(), new Properties()));
	public static final Item NUCLEAR_REACTOR = Ic2rItems.register("nuclear_reactor", new ItemBlockIc2r(Ic2rBlocks.NUCLEAR_REACTOR.get(), new Properties().rarity(Rarity.UNCOMMON)));
	public static final Item REACTOR_ACCESS_HATCH = Ic2rItems.register("reactor_access_hatch", new ItemBlockIc2r(Ic2rBlocks.REACTOR_ACCESS_HATCH.get(), new Properties().rarity(Rarity.UNCOMMON)));
	public static final Item REACTOR_CHAMBER = Ic2rItems.register("reactor_chamber", new ItemBlockIc2r(Ic2rBlocks.REACTOR_CHAMBER.get(), new Properties().rarity(Rarity.UNCOMMON)));
	public static final Item REACTOR_FLUID_PORT = Ic2rItems.register("reactor_fluid_port", new ItemBlockIc2r(Ic2rBlocks.REACTOR_FLUID_PORT.get(), new Properties().rarity(Rarity.UNCOMMON)));
	public static final Item REACTOR_REDSTONE_PORT = Ic2rItems.register("reactor_redstone_port", new ItemBlockIc2r(Ic2rBlocks.REACTOR_REDSTONE_PORT.get(), new Properties().rarity(Rarity.UNCOMMON)));
	public static final Item CONDENSER = Ic2rItems.register("condenser", new ItemBlockIc2r(Ic2rBlocks.CONDENSER.get(), new Properties()));
	public static final Item FLUID_BOTTLER = Ic2rItems.register("fluid_bottler", new ItemBlockIc2r(Ic2rBlocks.FLUID_BOTTLER.get(), new Properties()));
	public static final Item FLUID_DISTRIBUTOR = Ic2rItems.register("fluid_distributor", new ItemBlockIc2r(Ic2rBlocks.FLUID_DISTRIBUTOR.get(), new Properties()));
	public static final Item FLUID_REGULATOR = Ic2rItems.register("fluid_regulator", new ItemBlockIc2r(Ic2rBlocks.FLUID_REGULATOR.get(), new Properties()));
	public static final Item LIQUID_HEAT_EXCHANGER = Ic2rItems.register("liquid_heat_exchanger", new ItemBlockIc2r(Ic2rBlocks.LIQUID_HEAT_EXCHANGER.get(), new Properties()));
	public static final Item PUMP = Ic2rItems.register("pump", new ItemBlockIc2r(Ic2rBlocks.PUMP.get(), new Properties()));
	public static final Item SOLAR_DISTILLER = Ic2rItems.register("solar_distiller", new ItemBlockIc2r(Ic2rBlocks.SOLAR_DISTILLER.get(), new Properties()));
	public static final Item STEAM_GENERATOR = Ic2rItems.register("steam_generator", new ItemBlockIc2r(Ic2rBlocks.STEAM_GENERATOR.get(), new Properties()));
	public static final Item ITEM_BUFFER = Ic2rItems.register("item_buffer", new ItemBlockIc2r(Ic2rBlocks.ITEM_BUFFER.get(), new Properties()));
	public static final Item MAGNETIZER = Ic2rItems.register("magnetizer", new ItemBlockIc2r(Ic2rBlocks.MAGNETIZER.get(), new Properties()));
	public static final Item SORTING_MACHINE = Ic2rItems.register("sorting_machine", new ItemBlockIc2r(Ic2rBlocks.SORTING_MACHINE.get(), new Properties()));
	public static final Item TELEPORTER = Ic2rItems.register("teleporter", new ItemBlockIc2r(Ic2rBlocks.TELEPORTER.get(), new Properties().rarity(Rarity.RARE)));
	public static final Item TERRAFORMER = Ic2rItems.register("terraformer", new ItemBlockIc2r(Ic2rBlocks.TERRAFORMER.get(), new Properties().rarity(Rarity.UNCOMMON)));
	public static final Item TESLA_COIL = Ic2rItems.register("tesla_coil", new ItemBlockIc2r(Ic2rBlocks.TESLA_COIL.get(), new Properties()));
	public static final Item LUMINATOR_FLAT = Ic2rItems.register("luminator", new ItemBlockIc2r(Ic2rBlocks.LUMINATOR_FLAT.get(), new Properties()));
	public static final Item ELECTROLYZER = Ic2rItems.register("electrolyzer", new ItemBlockIc2r(Ic2rBlocks.ELECTROLYZER.get(), new Properties()));
	public static final Item CHUNK_LOADER = Ic2rItems.register("chunk_loader", new ItemBlockIc2r(Ic2rBlocks.CHUNK_LOADER.get(), new Properties().rarity(Rarity.UNCOMMON)));
	public static final Item CANNER = Ic2rItems.register("canner", new ItemBlockIc2r(Ic2rBlocks.CANNER.get(), new Properties()));
	public static final Item COMPRESSOR = Ic2rItems.register("compressor", new ItemBlockIc2r(Ic2rBlocks.COMPRESSOR.get(), new Properties()));
	public static final Item ELECTRIC_FURNACE = Ic2rItems.register("electric_furnace", new ItemBlockIc2r(Ic2rBlocks.ELECTRIC_FURNACE.get(), new Properties()));
	public static final Item EXTRACTOR = Ic2rItems.register("extractor", new ItemBlockIc2r(Ic2rBlocks.EXTRACTOR.get(), new Properties()));
	public static final Item IRON_FURNACE = Ic2rItems.register("iron_furnace", new ItemBlockIc2r(Ic2rBlocks.IRON_FURNACE.get(), new Properties()));
	public static final Item MACERATOR = Ic2rItems.register("macerator", new ItemBlockIc2r(Ic2rBlocks.MACERATOR.get(), new Properties()));
	public static final Item RECYCLER = Ic2rItems.register("recycler", new ItemBlockIc2r(Ic2rBlocks.RECYCLER.get(), new Properties()));
	public static final Item SOLID_CANNER = Ic2rItems.register("solid_canner", new ItemBlockIc2r(Ic2rBlocks.SOLID_CANNER.get(), new Properties()));
	public static final Item BLAST_FURNACE = Ic2rItems.register("blast_furnace", new ItemBlockIc2r(Ic2rBlocks.BLAST_FURNACE.get(), new Properties()));
	public static final Item BLOCK_CUTTER = Ic2rItems.register("block_cutter", new ItemBlockIc2r(Ic2rBlocks.BLOCK_CUTTER.get(), new Properties()));
	public static final Item CENTRIFUGE = Ic2rItems.register("centrifuge", new ItemBlockIc2r(Ic2rBlocks.CENTRIFUGE.get(), new Properties()));
	public static final Item FERMENTER = Ic2rItems.register("fermenter", new ItemBlockIc2r(Ic2rBlocks.FERMENTER.get(), new Properties()));
	public static final Item INDUCTION_FURNACE = Ic2rItems.register("induction_furnace", new ItemBlockIc2r(Ic2rBlocks.INDUCTION_FURNACE.get(), new Properties().rarity(Rarity.UNCOMMON)));
	public static final Item METAL_FORMER = Ic2rItems.register("metal_former", new ItemBlockIc2r(Ic2rBlocks.METAL_FORMER.get(), new Properties()));
	public static final Item ORE_WASHING_PLANT = Ic2rItems.register("ore_washing_plant", new ItemBlockIc2r(Ic2rBlocks.ORE_WASHING_PLANT.get(), new Properties()));
	public static final Item ADVANCED_MINER = Ic2rItems.register("advanced_miner", new ItemBlockIc2r(Ic2rBlocks.ADVANCED_MINER.get(), new Properties()));
	public static final Item CROP_HARVESTER = Ic2rItems.register("crop_harvester", new ItemBlockIc2r(Ic2rBlocks.CROP_HARVESTER.get(), new Properties()));
	public static final Item CROPMATRON = Ic2rItems.register("cropmatron", new ItemBlockIc2r(Ic2rBlocks.CROPMATRON.get(), new Properties()));
	public static final Item MINER = Ic2rItems.register("miner", new ItemBlockIc2r(Ic2rBlocks.MINER.get(), new Properties()));
	public static final Item MATTER_GENERATOR = Ic2rItems.register("matter_generator", new ItemBlockIc2r(Ic2rBlocks.MATTER_GENERATOR.get(), new Properties().rarity(Rarity.RARE)));
	public static final Item PATTERN_STORAGE = Ic2rItems.register("pattern_storage", new ItemBlockIc2r(Ic2rBlocks.PATTERN_STORAGE.get(), new Properties()));
	public static final Item REPLICATOR = Ic2rItems.register("replicator", new ItemBlockIc2r(Ic2rBlocks.REPLICATOR.get(), new Properties().rarity(Rarity.UNCOMMON)));
	public static final Item UU_SCANNER = Ic2rItems.register("uu_scanner", new ItemBlockIc2r(Ic2rBlocks.UU_SCANNER.get(), new Properties().rarity(Rarity.UNCOMMON)));
	public static final Item ENERGY_O_MAT = Ic2rItems.register("energy_o_mat", new ItemBlockIc2r(Ic2rBlocks.ENERGY_O_MAT.get(), new Properties()));
	public static final Item PERSONAL_CHEST = Ic2rItems.register("personal_chest", new ItemBlockIc2r(Ic2rBlocks.PERSONAL_CHEST.get(), new Properties().rarity(Rarity.UNCOMMON)));
	public static final Item TRADE_O_MAT = Ic2rItems.register("trade_o_mat", new ItemBlockIc2r(Ic2rBlocks.TRADE_O_MAT.get(), new Properties()));
}
