package me.halfcooler.ic2r.core.ref;

import me.halfcooler.ic2r.core.IC2R;
import me.halfcooler.ic2r.core.Ic2rItemGroupType;
import me.halfcooler.ic2r.core.block.BehaviorDynamiteDispense;
import me.halfcooler.ic2r.core.ref.items.Ic2rItemsArmor;
import me.halfcooler.ic2r.core.ref.items.Ic2rItemsBlockItems;
import me.halfcooler.ic2r.core.ref.items.Ic2rItemsCells;
import me.halfcooler.ic2r.core.ref.items.Ic2rItemsFarming;
import me.halfcooler.ic2r.core.ref.items.Ic2rItemsMaterials;
import me.halfcooler.ic2r.core.ref.items.Ic2rItemsReactor;
import me.halfcooler.ic2r.core.ref.items.Ic2rItemsTools;
import me.halfcooler.ic2r.core.ref.items.Ic2rItemsUpgrades;

import java.util.ArrayList;
import java.util.EnumMap;
import java.util.List;
import java.util.function.Supplier;

import net.minecraft.world.item.Item;
import net.minecraft.world.item.Items;

/**
 * Item registration facade. Domain implementations live under {@code ref.items}.
 * External code should keep using {@code Ic2rItems.XXX} field access.
 */
public final class Ic2rItems
{
	private Ic2rItems()
	{
	}

	public static final Item LEAD_ORE = Ic2rItemsBlockItems.LEAD_ORE;
	public static final Item TIN_ORE = Ic2rItemsBlockItems.TIN_ORE;
	public static final Item URANIUM_ORE = Ic2rItemsBlockItems.URANIUM_ORE;
	public static final Item DEEPSLATE_URANIUM_ORE = Ic2rItemsBlockItems.DEEPSLATE_URANIUM_ORE;
	public static final Item DEEPSLATE_TIN_ORE = Ic2rItemsBlockItems.DEEPSLATE_TIN_ORE;
	public static final Item DEEPSLATE_LEAD_ORE = Ic2rItemsBlockItems.DEEPSLATE_LEAD_ORE;
	public static final Item RAW_LEAD_BLOCK = Ic2rItemsBlockItems.RAW_LEAD_BLOCK;
	public static final Item RAW_TIN_BLOCK = Ic2rItemsBlockItems.RAW_TIN_BLOCK;
	public static final Item RAW_URANIUM_BLOCK = Ic2rItemsBlockItems.RAW_URANIUM_BLOCK;
	public static final Item BRONZE_BLOCK = Ic2rItemsBlockItems.BRONZE_BLOCK;
	public static final Item LEAD_BLOCK = Ic2rItemsBlockItems.LEAD_BLOCK;
	public static final Item STEEL_BLOCK = Ic2rItemsBlockItems.STEEL_BLOCK;
	public static final Item TIN_BLOCK = Ic2rItemsBlockItems.TIN_BLOCK;
	public static final Item URANIUM_BLOCK = Ic2rItemsBlockItems.URANIUM_BLOCK;
	public static final Item REINFORCED_STONE = Ic2rItemsBlockItems.REINFORCED_STONE;
	public static final Item REFRACTORY_BRICKS = Ic2rItemsBlockItems.REFRACTORY_BRICKS;
	public static final Item MACHINE = Ic2rItemsBlockItems.MACHINE;
	public static final Item ADVANCED_MACHINE = Ic2rItemsBlockItems.ADVANCED_MACHINE;
	public static final Item SILVER_BLOCK = Ic2rItemsBlockItems.SILVER_BLOCK;
	public static final Item RUBBER_LEAVES = Ic2rItemsBlockItems.RUBBER_LEAVES;
	public static final Item RUBBER_LOG = Ic2rItemsBlockItems.RUBBER_LOG;
	public static final Item STRIPPED_RUBBER_LOG = Ic2rItemsBlockItems.STRIPPED_RUBBER_LOG;
	public static final Item RUBBER_WOOD = Ic2rItemsBlockItems.RUBBER_WOOD;
	public static final Item STRIPPED_RUBBER_WOOD = Ic2rItemsBlockItems.STRIPPED_RUBBER_WOOD;
	public static final Item RUBBER_PLANKS = Ic2rItemsBlockItems.RUBBER_PLANKS;
	public static final Item RUBBER_SAPLING = Ic2rItemsBlockItems.RUBBER_SAPLING;
	public static final Item RUBBER_BUTTON = Ic2rItemsBlockItems.RUBBER_BUTTON;
	public static final Item RUBBER_DOOR = Ic2rItemsBlockItems.RUBBER_DOOR;
	public static final Item RUBBER_FENCE = Ic2rItemsBlockItems.RUBBER_FENCE;
	public static final Item RUBBER_FENCE_GATE = Ic2rItemsBlockItems.RUBBER_FENCE_GATE;
	public static final Item RUBBER_PRESSURE_PLATE = Ic2rItemsBlockItems.RUBBER_PRESSURE_PLATE;
	public static final Item RUBBER_SIGN = Ic2rItemsBlockItems.RUBBER_SIGN;
	public static final Item RUBBER_SLAB = Ic2rItemsBlockItems.RUBBER_SLAB;
	public static final Item RUBBER_STAIRS = Ic2rItemsBlockItems.RUBBER_STAIRS;
	public static final Item RUBBER_TRAPDOOR = Ic2rItemsBlockItems.RUBBER_TRAPDOOR;
	public static final Item MINING_PIPE = Ic2rItemsBlockItems.MINING_PIPE;
	public static final Item IRON_FENCE = Ic2rItemsBlockItems.IRON_FENCE;
	public static final Item RESIN_SHEET = Ic2rItemsBlockItems.RESIN_SHEET;
	public static final Item RUBBER_SHEET = Ic2rItemsBlockItems.RUBBER_SHEET;
	public static final Item WOOL_SHEET = Ic2rItemsBlockItems.WOOL_SHEET;
	public static final Item REINFORCED_GLASS = Ic2rItemsBlockItems.REINFORCED_GLASS;
	public static final Item REINFORCED_DOOR = Ic2rItemsBlockItems.REINFORCED_DOOR;
	public static final Item FOAM = Ic2rItemsBlockItems.FOAM;
	public static final Item WHITE_WALL = Ic2rItemsBlockItems.WHITE_WALL;
	public static final Item ORANGE_WALL = Ic2rItemsBlockItems.ORANGE_WALL;
	public static final Item MAGENTA_WALL = Ic2rItemsBlockItems.MAGENTA_WALL;
	public static final Item LIGHT_BLUE_WALL = Ic2rItemsBlockItems.LIGHT_BLUE_WALL;
	public static final Item YELLOW_WALL = Ic2rItemsBlockItems.YELLOW_WALL;
	public static final Item LIME_WALL = Ic2rItemsBlockItems.LIME_WALL;
	public static final Item PINK_WALL = Ic2rItemsBlockItems.PINK_WALL;
	public static final Item GRAY_WALL = Ic2rItemsBlockItems.GRAY_WALL;
	public static final Item LIGHT_GRAY_WALL = Ic2rItemsBlockItems.LIGHT_GRAY_WALL;
	public static final Item CYAN_WALL = Ic2rItemsBlockItems.CYAN_WALL;
	public static final Item PURPLE_WALL = Ic2rItemsBlockItems.PURPLE_WALL;
	public static final Item BLUE_WALL = Ic2rItemsBlockItems.BLUE_WALL;
	public static final Item BROWN_WALL = Ic2rItemsBlockItems.BROWN_WALL;
	public static final Item GREEN_WALL = Ic2rItemsBlockItems.GREEN_WALL;
	public static final Item RED_WALL = Ic2rItemsBlockItems.RED_WALL;
	public static final Item BLACK_WALL = Ic2rItemsBlockItems.BLACK_WALL;
	public static final Item ITNT = Ic2rItemsBlockItems.ITNT;
	public static final Item NUKE = Ic2rItemsBlockItems.NUKE;
	public static final Item DYNAMITE = Ic2rItemsBlockItems.DYNAMITE;
	public static final Item DYNAMITE_STICKY = Ic2rItemsBlockItems.DYNAMITE_STICKY;
	public static final Item COPPER_CABLE = Ic2rItemsBlockItems.COPPER_CABLE;
	public static final Item INSULATED_COPPER_CABLE = Ic2rItemsBlockItems.INSULATED_COPPER_CABLE;
	public static final Item GLASS_FIBRE_CABLE = Ic2rItemsBlockItems.GLASS_FIBRE_CABLE;
	public static final Item GOLD_CABLE = Ic2rItemsBlockItems.GOLD_CABLE;
	public static final Item INSULATED_GOLD_CABLE = Ic2rItemsBlockItems.INSULATED_GOLD_CABLE;
	public static final Item DOUBLE_INSULATED_GOLD_CABLE = Ic2rItemsBlockItems.DOUBLE_INSULATED_GOLD_CABLE;
	public static final Item IRON_CABLE = Ic2rItemsBlockItems.IRON_CABLE;
	public static final Item INSULATED_IRON_CABLE = Ic2rItemsBlockItems.INSULATED_IRON_CABLE;
	public static final Item DOUBLE_INSULATED_IRON_CABLE = Ic2rItemsBlockItems.DOUBLE_INSULATED_IRON_CABLE;
	public static final Item TRIPLE_INSULATED_IRON_CABLE = Ic2rItemsBlockItems.TRIPLE_INSULATED_IRON_CABLE;
	public static final Item TIN_CABLE = Ic2rItemsBlockItems.TIN_CABLE;
	public static final Item INSULATED_TIN_CABLE = Ic2rItemsBlockItems.INSULATED_TIN_CABLE;
	public static final Item DETECTOR_CABLE = Ic2rItemsBlockItems.DETECTOR_CABLE;
	public static final Item SPLITTER_CABLE = Ic2rItemsBlockItems.SPLITTER_CABLE;
	public static final Item BATBOX_CHARGEPAD = Ic2rItemsBlockItems.BATBOX_CHARGEPAD;
	public static final Item CESU_CHARGEPAD = Ic2rItemsBlockItems.CESU_CHARGEPAD;
	public static final Item MFE_CHARGEPAD = Ic2rItemsBlockItems.MFE_CHARGEPAD;
	public static final Item MFSU_CHARGEPAD = Ic2rItemsBlockItems.MFSU_CHARGEPAD;
	public static final Item BATBOX = Ic2rItemsBlockItems.BATBOX;
	public static final Item CESU = Ic2rItemsBlockItems.CESU;
	public static final Item MFE = Ic2rItemsBlockItems.MFE;
	public static final Item MFSU = Ic2rItemsBlockItems.MFSU;
	public static final Item LV_TRANSFORMER = Ic2rItemsBlockItems.LV_TRANSFORMER;
	public static final Item MV_TRANSFORMER = Ic2rItemsBlockItems.MV_TRANSFORMER;
	public static final Item HV_TRANSFORMER = Ic2rItemsBlockItems.HV_TRANSFORMER;
	public static final Item EV_TRANSFORMER = Ic2rItemsBlockItems.EV_TRANSFORMER;
	public static final Item TANK = Ic2rItemsBlockItems.TANK;
	public static final Item STEAM_REPRESSURIZER = Ic2rItemsBlockItems.STEAM_REPRESSURIZER;
	public static final Item WEIGHTED_FLUID_DISTRIBUTOR = Ic2rItemsBlockItems.WEIGHTED_FLUID_DISTRIBUTOR;
	public static final Item WEIGHTED_ITEM_DISTRIBUTOR = Ic2rItemsBlockItems.WEIGHTED_ITEM_DISTRIBUTOR;
	public static final Item RCI_RSH = Ic2rItemsBlockItems.RCI_RSH;
	public static final Item RCI_LZH = Ic2rItemsBlockItems.RCI_LZH;
	public static final Item INDUSTRIAL_WORKBENCH = Ic2rItemsBlockItems.INDUSTRIAL_WORKBENCH;
	public static final Item BATCH_CRAFTER = Ic2rItemsBlockItems.BATCH_CRAFTER;
	public static final Item WOODEN_STORAGE_BOX = Ic2rItemsBlockItems.WOODEN_STORAGE_BOX;
	public static final Item IRON_STORAGE_BOX = Ic2rItemsBlockItems.IRON_STORAGE_BOX;
	public static final Item BRONZE_STORAGE_BOX = Ic2rItemsBlockItems.BRONZE_STORAGE_BOX;
	public static final Item STEEL_STORAGE_BOX = Ic2rItemsBlockItems.STEEL_STORAGE_BOX;
	public static final Item IRIDIUM_STORAGE_BOX = Ic2rItemsBlockItems.IRIDIUM_STORAGE_BOX;
	public static final Item BRONZE_TANK = Ic2rItemsBlockItems.BRONZE_TANK;
	public static final Item IRON_TANK = Ic2rItemsBlockItems.IRON_TANK;
	public static final Item STEEL_TANK = Ic2rItemsBlockItems.STEEL_TANK;
	public static final Item IRIDIUM_TANK = Ic2rItemsBlockItems.IRIDIUM_TANK;
	public static final Item COKE_KILN = Ic2rItemsBlockItems.COKE_KILN;
	public static final Item COKE_KILN_HATCH = Ic2rItemsBlockItems.COKE_KILN_HATCH;
	public static final Item COKE_KILN_GRATE = Ic2rItemsBlockItems.COKE_KILN_GRATE;
	public static final Item GENERATOR = Ic2rItemsBlockItems.GENERATOR;
	public static final Item GEO_GENERATOR = Ic2rItemsBlockItems.GEO_GENERATOR;
	public static final Item KINETIC_GENERATOR = Ic2rItemsBlockItems.KINETIC_GENERATOR;
	public static final Item RT_GENERATOR = Ic2rItemsBlockItems.RT_GENERATOR;
	public static final Item SEMIFLUID_GENERATOR = Ic2rItemsBlockItems.SEMIFLUID_GENERATOR;
	public static final Item SOLAR_GENERATOR = Ic2rItemsBlockItems.SOLAR_GENERATOR;
	public static final Item STIRLING_GENERATOR = Ic2rItemsBlockItems.STIRLING_GENERATOR;
	public static final Item WATER_GENERATOR = Ic2rItemsBlockItems.WATER_GENERATOR;
	public static final Item WIND_GENERATOR = Ic2rItemsBlockItems.WIND_GENERATOR;
	public static final Item CREATIVE_GENERATOR = Ic2rItemsBlockItems.CREATIVE_GENERATOR;
	public static final Item ELECTRIC_HEAT_GENERATOR = Ic2rItemsBlockItems.ELECTRIC_HEAT_GENERATOR;
	public static final Item FLUID_HEAT_GENERATOR = Ic2rItemsBlockItems.FLUID_HEAT_GENERATOR;
	public static final Item RT_HEAT_GENERATOR = Ic2rItemsBlockItems.RT_HEAT_GENERATOR;
	public static final Item SOLID_HEAT_GENERATOR = Ic2rItemsBlockItems.SOLID_HEAT_GENERATOR;
	public static final Item ELECTRIC_KINETIC_GENERATOR = Ic2rItemsBlockItems.ELECTRIC_KINETIC_GENERATOR;
	public static final Item MANUAL_KINETIC_GENERATOR = Ic2rItemsBlockItems.MANUAL_KINETIC_GENERATOR;
	public static final Item STEAM_KINETIC_GENERATOR = Ic2rItemsBlockItems.STEAM_KINETIC_GENERATOR;
	public static final Item STIRLING_KINETIC_GENERATOR = Ic2rItemsBlockItems.STIRLING_KINETIC_GENERATOR;
	public static final Item WATER_KINETIC_GENERATOR = Ic2rItemsBlockItems.WATER_KINETIC_GENERATOR;
	public static final Item WIND_KINETIC_GENERATOR = Ic2rItemsBlockItems.WIND_KINETIC_GENERATOR;
	public static final Item NUCLEAR_REACTOR = Ic2rItemsBlockItems.NUCLEAR_REACTOR;
	public static final Item REACTOR_ACCESS_HATCH = Ic2rItemsBlockItems.REACTOR_ACCESS_HATCH;
	public static final Item REACTOR_CHAMBER = Ic2rItemsBlockItems.REACTOR_CHAMBER;
	public static final Item REACTOR_FLUID_PORT = Ic2rItemsBlockItems.REACTOR_FLUID_PORT;
	public static final Item REACTOR_REDSTONE_PORT = Ic2rItemsBlockItems.REACTOR_REDSTONE_PORT;
	public static final Item CONDENSER = Ic2rItemsBlockItems.CONDENSER;
	public static final Item FLUID_BOTTLER = Ic2rItemsBlockItems.FLUID_BOTTLER;
	public static final Item FLUID_DISTRIBUTOR = Ic2rItemsBlockItems.FLUID_DISTRIBUTOR;
	public static final Item FLUID_REGULATOR = Ic2rItemsBlockItems.FLUID_REGULATOR;
	public static final Item LIQUID_HEAT_EXCHANGER = Ic2rItemsBlockItems.LIQUID_HEAT_EXCHANGER;
	public static final Item PUMP = Ic2rItemsBlockItems.PUMP;
	public static final Item SOLAR_DISTILLER = Ic2rItemsBlockItems.SOLAR_DISTILLER;
	public static final Item STEAM_GENERATOR = Ic2rItemsBlockItems.STEAM_GENERATOR;
	public static final Item ITEM_BUFFER = Ic2rItemsBlockItems.ITEM_BUFFER;
	public static final Item MAGNETIZER = Ic2rItemsBlockItems.MAGNETIZER;
	public static final Item SORTING_MACHINE = Ic2rItemsBlockItems.SORTING_MACHINE;
	public static final Item TELEPORTER = Ic2rItemsBlockItems.TELEPORTER;
	public static final Item TERRAFORMER = Ic2rItemsBlockItems.TERRAFORMER;
	public static final Item TESLA_COIL = Ic2rItemsBlockItems.TESLA_COIL;
	public static final Item LUMINATOR_FLAT = Ic2rItemsBlockItems.LUMINATOR_FLAT;
	public static final Item ELECTROLYZER = Ic2rItemsBlockItems.ELECTROLYZER;
	public static final Item CHUNK_LOADER = Ic2rItemsBlockItems.CHUNK_LOADER;
	public static final Item CANNER = Ic2rItemsBlockItems.CANNER;
	public static final Item COMPRESSOR = Ic2rItemsBlockItems.COMPRESSOR;
	public static final Item ELECTRIC_FURNACE = Ic2rItemsBlockItems.ELECTRIC_FURNACE;
	public static final Item EXTRACTOR = Ic2rItemsBlockItems.EXTRACTOR;
	public static final Item IRON_FURNACE = Ic2rItemsBlockItems.IRON_FURNACE;
	public static final Item MACERATOR = Ic2rItemsBlockItems.MACERATOR;
	public static final Item RECYCLER = Ic2rItemsBlockItems.RECYCLER;
	public static final Item SOLID_CANNER = Ic2rItemsBlockItems.SOLID_CANNER;
	public static final Item BLAST_FURNACE = Ic2rItemsBlockItems.BLAST_FURNACE;
	public static final Item BLOCK_CUTTER = Ic2rItemsBlockItems.BLOCK_CUTTER;
	public static final Item CENTRIFUGE = Ic2rItemsBlockItems.CENTRIFUGE;
	public static final Item FERMENTER = Ic2rItemsBlockItems.FERMENTER;
	public static final Item INDUCTION_FURNACE = Ic2rItemsBlockItems.INDUCTION_FURNACE;
	public static final Item METAL_FORMER = Ic2rItemsBlockItems.METAL_FORMER;
	public static final Item ORE_WASHING_PLANT = Ic2rItemsBlockItems.ORE_WASHING_PLANT;
	public static final Item ADVANCED_MINER = Ic2rItemsBlockItems.ADVANCED_MINER;
	public static final Item CROP_HARVESTER = Ic2rItemsBlockItems.CROP_HARVESTER;
	public static final Item CROPMATRON = Ic2rItemsBlockItems.CROPMATRON;
	public static final Item MINER = Ic2rItemsBlockItems.MINER;
	public static final Item MATTER_GENERATOR = Ic2rItemsBlockItems.MATTER_GENERATOR;
	public static final Item PATTERN_STORAGE = Ic2rItemsBlockItems.PATTERN_STORAGE;
	public static final Item REPLICATOR = Ic2rItemsBlockItems.REPLICATOR;
	public static final Item UU_SCANNER = Ic2rItemsBlockItems.UU_SCANNER;
	public static final Item ENERGY_O_MAT = Ic2rItemsBlockItems.ENERGY_O_MAT;
	public static final Item PERSONAL_CHEST = Ic2rItemsBlockItems.PERSONAL_CHEST;
	public static final Item TRADE_O_MAT = Ic2rItemsBlockItems.TRADE_O_MAT;
	public static final Item RAW_LEAD = Ic2rItemsMaterials.RAW_LEAD;
	public static final Item RAW_TIN = Ic2rItemsMaterials.RAW_TIN;
	public static final Item RAW_URANIUM = Ic2rItemsMaterials.RAW_URANIUM;
	public static final Item CRUSHED_COPPER = Ic2rItemsMaterials.CRUSHED_COPPER;
	public static final Item CRUSHED_GOLD = Ic2rItemsMaterials.CRUSHED_GOLD;
	public static final Item CRUSHED_IRON = Ic2rItemsMaterials.CRUSHED_IRON;
	public static final Item CRUSHED_LEAD = Ic2rItemsMaterials.CRUSHED_LEAD;
	public static final Item CRUSHED_SILVER = Ic2rItemsMaterials.CRUSHED_SILVER;
	public static final Item CRUSHED_TIN = Ic2rItemsMaterials.CRUSHED_TIN;
	public static final Item CRUSHED_URANIUM = Ic2rItemsMaterials.CRUSHED_URANIUM;
	public static final Item PURIFIED_COPPER = Ic2rItemsMaterials.PURIFIED_COPPER;
	public static final Item PURIFIED_GOLD = Ic2rItemsMaterials.PURIFIED_GOLD;
	public static final Item PURIFIED_IRON = Ic2rItemsMaterials.PURIFIED_IRON;
	public static final Item PURIFIED_LEAD = Ic2rItemsMaterials.PURIFIED_LEAD;
	public static final Item PURIFIED_SILVER = Ic2rItemsMaterials.PURIFIED_SILVER;
	public static final Item PURIFIED_TIN = Ic2rItemsMaterials.PURIFIED_TIN;
	public static final Item PURIFIED_URANIUM = Ic2rItemsMaterials.PURIFIED_URANIUM;
	public static final Item BRONZE_DUST = Ic2rItemsMaterials.BRONZE_DUST;
	public static final Item CLAY_DUST = Ic2rItemsMaterials.CLAY_DUST;
	public static final Item COAL_DUST = Ic2rItemsMaterials.COAL_DUST;
	public static final Item COAL_FUEL_DUST = Ic2rItemsMaterials.COAL_FUEL_DUST;
	public static final Item COPPER_DUST = Ic2rItemsMaterials.COPPER_DUST;
	public static final Item DIAMOND_DUST = Ic2rItemsMaterials.DIAMOND_DUST;
	public static final Item ENERGIUM_DUST = Ic2rItemsMaterials.ENERGIUM_DUST;
	public static final Item GOLD_DUST = Ic2rItemsMaterials.GOLD_DUST;
	public static final Item IRON_DUST = Ic2rItemsMaterials.IRON_DUST;
	public static final Item LAPIS_DUST = Ic2rItemsMaterials.LAPIS_DUST;
	public static final Item LEAD_DUST = Ic2rItemsMaterials.LEAD_DUST;
	public static final Item LITHIUM_DUST = Ic2rItemsMaterials.LITHIUM_DUST;
	public static final Item OBSIDIAN_DUST = Ic2rItemsMaterials.OBSIDIAN_DUST;
	public static final Item SILICON_DIOXIDE_DUST = Ic2rItemsMaterials.SILICON_DIOXIDE_DUST;
	public static final Item SILVER_DUST = Ic2rItemsMaterials.SILVER_DUST;
	public static final Item STONE_DUST = Ic2rItemsMaterials.STONE_DUST;
	public static final Item SULFUR_DUST = Ic2rItemsMaterials.SULFUR_DUST;
	public static final Item TIN_DUST = Ic2rItemsMaterials.TIN_DUST;
	public static final Item SMALL_BRONZE_DUST = Ic2rItemsMaterials.SMALL_BRONZE_DUST;
	public static final Item SMALL_COPPER_DUST = Ic2rItemsMaterials.SMALL_COPPER_DUST;
	public static final Item SMALL_GOLD_DUST = Ic2rItemsMaterials.SMALL_GOLD_DUST;
	public static final Item SMALL_IRON_DUST = Ic2rItemsMaterials.SMALL_IRON_DUST;
	public static final Item SMALL_LAPIS_DUST = Ic2rItemsMaterials.SMALL_LAPIS_DUST;
	public static final Item SMALL_LEAD_DUST = Ic2rItemsMaterials.SMALL_LEAD_DUST;
	public static final Item SMALL_LITHIUM_DUST = Ic2rItemsMaterials.SMALL_LITHIUM_DUST;
	public static final Item SMALL_OBSIDIAN_DUST = Ic2rItemsMaterials.SMALL_OBSIDIAN_DUST;
	public static final Item SMALL_SILVER_DUST = Ic2rItemsMaterials.SMALL_SILVER_DUST;
	public static final Item SMALL_SULFUR_DUST = Ic2rItemsMaterials.SMALL_SULFUR_DUST;
	public static final Item SMALL_TIN_DUST = Ic2rItemsMaterials.SMALL_TIN_DUST;
	public static final Item HYDRATED_TIN_DUST = Ic2rItemsMaterials.HYDRATED_TIN_DUST;
	public static final Item NETHERRACK_DUST = Ic2rItemsMaterials.NETHERRACK_DUST;
	public static final Item MIXED_METAL_INGOT = Ic2rItemsMaterials.MIXED_METAL_INGOT;
	public static final Item BRONZE_INGOT = Ic2rItemsMaterials.BRONZE_INGOT;
	public static final Item LEAD_INGOT = Ic2rItemsMaterials.LEAD_INGOT;
	public static final Item SILVER_INGOT = Ic2rItemsMaterials.SILVER_INGOT;
	public static final Item STEEL_INGOT = Ic2rItemsMaterials.STEEL_INGOT;
	public static final Item TIN_INGOT = Ic2rItemsMaterials.TIN_INGOT;
	public static final Item URANIUM_INGOT = Ic2rItemsMaterials.URANIUM_INGOT;
	public static final Item BRONZE_PLATE = Ic2rItemsMaterials.BRONZE_PLATE;
	public static final Item COPPER_PLATE = Ic2rItemsMaterials.COPPER_PLATE;
	public static final Item GOLD_PLATE = Ic2rItemsMaterials.GOLD_PLATE;
	public static final Item IRON_PLATE = Ic2rItemsMaterials.IRON_PLATE;
	public static final Item LAPIS_PLATE = Ic2rItemsMaterials.LAPIS_PLATE;
	public static final Item LEAD_PLATE = Ic2rItemsMaterials.LEAD_PLATE;
	public static final Item OBSIDIAN_PLATE = Ic2rItemsMaterials.OBSIDIAN_PLATE;
	public static final Item STEEL_PLATE = Ic2rItemsMaterials.STEEL_PLATE;
	public static final Item TIN_PLATE = Ic2rItemsMaterials.TIN_PLATE;
	public static final Item DENSE_BRONZE_PLATE = Ic2rItemsMaterials.DENSE_BRONZE_PLATE;
	public static final Item DENSE_COPPER_PLATE = Ic2rItemsMaterials.DENSE_COPPER_PLATE;
	public static final Item DENSE_GOLD_PLATE = Ic2rItemsMaterials.DENSE_GOLD_PLATE;
	public static final Item DENSE_IRON_PLATE = Ic2rItemsMaterials.DENSE_IRON_PLATE;
	public static final Item DENSE_LAPIS_PLATE = Ic2rItemsMaterials.DENSE_LAPIS_PLATE;
	public static final Item DENSE_LEAD_PLATE = Ic2rItemsMaterials.DENSE_LEAD_PLATE;
	public static final Item DENSE_OBSIDIAN_PLATE = Ic2rItemsMaterials.DENSE_OBSIDIAN_PLATE;
	public static final Item DENSE_STEEL_PLATE = Ic2rItemsMaterials.DENSE_STEEL_PLATE;
	public static final Item DENSE_TIN_PLATE = Ic2rItemsMaterials.DENSE_TIN_PLATE;
	public static final Item BRONZE_CASING = Ic2rItemsMaterials.BRONZE_CASING;
	public static final Item COPPER_CASING = Ic2rItemsMaterials.COPPER_CASING;
	public static final Item GOLD_CASING = Ic2rItemsMaterials.GOLD_CASING;
	public static final Item IRON_CASING = Ic2rItemsMaterials.IRON_CASING;
	public static final Item LEAD_CASING = Ic2rItemsMaterials.LEAD_CASING;
	public static final Item STEEL_CASING = Ic2rItemsMaterials.STEEL_CASING;
	public static final Item TIN_CASING = Ic2rItemsMaterials.TIN_CASING;
	public static final Item URANIUM = Ic2rItemsMaterials.URANIUM;
	public static final Item URANIUM_235 = Ic2rItemsMaterials.URANIUM_235;
	public static final Item URANIUM_238 = Ic2rItemsMaterials.URANIUM_238;
	public static final Item PLUTONIUM = Ic2rItemsMaterials.PLUTONIUM;
	public static final Item MOX = Ic2rItemsMaterials.MOX;
	public static final Item SMALL_URANIUM_235 = Ic2rItemsMaterials.SMALL_URANIUM_235;
	public static final Item SMALL_URANIUM_238 = Ic2rItemsMaterials.SMALL_URANIUM_238;
	public static final Item SMALL_PLUTONIUM = Ic2rItemsMaterials.SMALL_PLUTONIUM;
	public static final Item URANIUM_PELLET = Ic2rItemsMaterials.URANIUM_PELLET;
	public static final Item RTG_PELLET = Ic2rItemsMaterials.RTG_PELLET;
	public static final Item DEPLETED_URANIUM_FUEL_ROD = Ic2rItemsMaterials.DEPLETED_URANIUM_FUEL_ROD;
	public static final Item DEPLETED_DUAL_URANIUM_FUEL_ROD = Ic2rItemsMaterials.DEPLETED_DUAL_URANIUM_FUEL_ROD;
	public static final Item DEPLETED_QUAD_URANIUM_FUEL_ROD = Ic2rItemsMaterials.DEPLETED_QUAD_URANIUM_FUEL_ROD;
	public static final Item DEPLETED_MOX_FUEL_ROD = Ic2rItemsMaterials.DEPLETED_MOX_FUEL_ROD;
	public static final Item DEPLETED_DUAL_MOX_FUEL_ROD = Ic2rItemsMaterials.DEPLETED_DUAL_MOX_FUEL_ROD;
	public static final Item DEPLETED_QUAD_MOX_FUEL_ROD = Ic2rItemsMaterials.DEPLETED_QUAD_MOX_FUEL_ROD;
	public static final Item NEAR_DEPLETED_URANIUM = Ic2rItemsMaterials.NEAR_DEPLETED_URANIUM;
	public static final Item RE_ENRICHED_URANIUM = Ic2rItemsMaterials.RE_ENRICHED_URANIUM;
	public static final Item ASHES = Ic2rItemsMaterials.ASHES;
	public static final Item IRIDIUM_ORE = Ic2rItemsMaterials.IRIDIUM_ORE;
	public static final Item IRIDIUM_SHARD = Ic2rItemsMaterials.IRIDIUM_SHARD;
	public static final Item RESIN = Ic2rItemsMaterials.RESIN;
	public static final Item SLAG = Ic2rItemsMaterials.SLAG;
	public static final Item COKE = Ic2rItemsMaterials.COKE;
	public static final Item IODINE = Ic2rItemsMaterials.IODINE;
	public static final Item WATER_SHEET = Ic2rItemsMaterials.WATER_SHEET;
	public static final Item LAVA_SHEET = Ic2rItemsMaterials.LAVA_SHEET;
	public static final Item RUBBER = Ic2rItemsMaterials.RUBBER;
	public static final Item CIRCUIT = Ic2rItemsMaterials.CIRCUIT;
	public static final Item ADVANCED_CIRCUIT = Ic2rItemsMaterials.ADVANCED_CIRCUIT;
	public static final Item ALLOY = Ic2rItemsMaterials.ALLOY;
	public static final Item IRIDIUM = Ic2rItemsMaterials.IRIDIUM;
	public static final Item COIL = Ic2rItemsMaterials.COIL;
	public static final Item ELECTRIC_MOTOR = Ic2rItemsMaterials.ELECTRIC_MOTOR;
	public static final Item HEAT_CONDUCTOR = Ic2rItemsMaterials.HEAT_CONDUCTOR;
	public static final Item COPPER_BOILER = Ic2rItemsMaterials.COPPER_BOILER;
	public static final Item FUEL_ROD = Ic2rItemsMaterials.FUEL_ROD;
	public static final Item TIN_CAN = Ic2rItemsMaterials.TIN_CAN;
	public static final Item IRON_CUTTING_BLADE = Ic2rItemsMaterials.IRON_CUTTING_BLADE;
	public static final Item DIAMOND_CUTTING_BLADE = Ic2rItemsMaterials.DIAMOND_CUTTING_BLADE;
	public static final Item STEEL_CUTTING_BLADE = Ic2rItemsMaterials.STEEL_CUTTING_BLADE;
	public static final Item SMALL_POWER_UNIT = Ic2rItemsMaterials.SMALL_POWER_UNIT;
	public static final Item POWER_UNIT = Ic2rItemsMaterials.POWER_UNIT;
	public static final Item CARBON_FIBRE = Ic2rItemsMaterials.CARBON_FIBRE;
	public static final Item CARBON_MESH = Ic2rItemsMaterials.CARBON_MESH;
	public static final Item CARBON_PLATE = Ic2rItemsMaterials.CARBON_PLATE;
	public static final Item COAL_BALL = Ic2rItemsMaterials.COAL_BALL;
	public static final Item COAL_BLOCK = Ic2rItemsMaterials.COAL_BLOCK;
	public static final Item COAL_CHUNK = Ic2rItemsMaterials.COAL_CHUNK;
	public static final Item INDUTRIAL_DIAMOND = Ic2rItemsMaterials.INDUTRIAL_DIAMOND;
	public static final Item PLANT_BALL = Ic2rItemsMaterials.PLANT_BALL;
	public static final Item BIO_CHAFF = Ic2rItemsMaterials.BIO_CHAFF;
	public static final Item SCRAP = Ic2rItemsMaterials.SCRAP;
	public static final Item SCRAP_BOX = Ic2rItemsMaterials.SCRAP_BOX;
	public static final Item CF_POWDER = Ic2rItemsMaterials.CF_POWDER;
	public static final Item PELLET = Ic2rItemsMaterials.PELLET;
	public static final Item RAW_CRYSTAL_MEMORY = Ic2rItemsMaterials.RAW_CRYSTAL_MEMORY;
	public static final Item CRYSTAL_MEMORY = Ic2rItemsMaterials.CRYSTAL_MEMORY;
	public static final Item IRON_SHAFT = Ic2rItemsMaterials.IRON_SHAFT;
	public static final Item STEEL_SHAFT = Ic2rItemsMaterials.STEEL_SHAFT;
	public static final Item WOODEN_ROTOR_BLADE = Ic2rItemsMaterials.WOODEN_ROTOR_BLADE;
	public static final Item IRON_ROTOR_BLADE = Ic2rItemsMaterials.IRON_ROTOR_BLADE;
	public static final Item STEEL_ROTOR_BLADE = Ic2rItemsMaterials.STEEL_ROTOR_BLADE;
	public static final Item CARBON_ROTOR_BLADE = Ic2rItemsMaterials.CARBON_ROTOR_BLADE;
	public static final Item STEAM_TURBINE_BLADE = Ic2rItemsMaterials.STEAM_TURBINE_BLADE;
	public static final Item STEAM_TURBINE = Ic2rItemsMaterials.STEAM_TURBINE;
	public static final Item JETPACK_ATTACHMENT_PLATE = Ic2rItemsMaterials.JETPACK_ATTACHMENT_PLATE;
	public static final Item COIN = Ic2rItemsMaterials.COIN;
	public static final Item BRONZE_ROTOR_BLADE = Ic2rItemsMaterials.BRONZE_ROTOR_BLADE;
	public static final Item BRONZE_SHAFT = Ic2rItemsMaterials.BRONZE_SHAFT;
	public static final Item REACTOR_COOLANT_CELL = Ic2rItemsReactor.REACTOR_COOLANT_CELL;
	public static final Item TRIPLE_REACTOR_COOLANT_CELL = Ic2rItemsReactor.TRIPLE_REACTOR_COOLANT_CELL;
	public static final Item SEXTUPLE_REACTOR_COOLANT_CELL = Ic2rItemsReactor.SEXTUPLE_REACTOR_COOLANT_CELL;
	public static final Item REACTOR_PLATING = Ic2rItemsReactor.REACTOR_PLATING;
	public static final Item REACTOR_HEAT_PLATING = Ic2rItemsReactor.REACTOR_HEAT_PLATING;
	public static final Item CONTAINMENT_REACTOR_PLATING = Ic2rItemsReactor.CONTAINMENT_REACTOR_PLATING;
	public static final Item HEAT_EXCHANGER = Ic2rItemsReactor.HEAT_EXCHANGER;
	public static final Item REACTOR_HEAT_EXCHANGER = Ic2rItemsReactor.REACTOR_HEAT_EXCHANGER;
	public static final Item COMPONENT_HEAT_EXCHANGER = Ic2rItemsReactor.COMPONENT_HEAT_EXCHANGER;
	public static final Item ADVANCED_HEAT_EXCHANGER = Ic2rItemsReactor.ADVANCED_HEAT_EXCHANGER;
	public static final Item HEAT_VENT = Ic2rItemsReactor.HEAT_VENT;
	public static final Item REACTOR_HEAT_VENT = Ic2rItemsReactor.REACTOR_HEAT_VENT;
	public static final Item OVERCLOCKED_HEAT_VENT = Ic2rItemsReactor.OVERCLOCKED_HEAT_VENT;
	public static final Item COMPONENT_HEAT_VENT = Ic2rItemsReactor.COMPONENT_HEAT_VENT;
	public static final Item ADVANCED_HEAT_VENT = Ic2rItemsReactor.ADVANCED_HEAT_VENT;
	public static final Item NEUTRON_REFLECTOR = Ic2rItemsReactor.NEUTRON_REFLECTOR;
	public static final Item THICK_NEUTRON_REFLECTOR = Ic2rItemsReactor.THICK_NEUTRON_REFLECTOR;
	public static final Item IRIDIUM_NEUTRON_REFLECTOR = Ic2rItemsReactor.IRIDIUM_NEUTRON_REFLECTOR;
	public static final Item RSH_CONDENSATOR = Ic2rItemsReactor.RSH_CONDENSATOR;
	public static final Item LZH_CONDENSATOR = Ic2rItemsReactor.LZH_CONDENSATOR;
	public static final Item HEATPACK = Ic2rItemsReactor.HEATPACK;
	public static final Item REACTOR_VESSEL = Ic2rItemsReactor.REACTOR_VESSEL;
	public static final Item URANIUM_FUEL_ROD = Ic2rItemsReactor.URANIUM_FUEL_ROD;
	public static final Item DUAL_URANIUM_FUEL_ROD = Ic2rItemsReactor.DUAL_URANIUM_FUEL_ROD;
	public static final Item QUAD_URANIUM_FUEL_ROD = Ic2rItemsReactor.QUAD_URANIUM_FUEL_ROD;
	public static final Item MOX_FUEL_ROD = Ic2rItemsReactor.MOX_FUEL_ROD;
	public static final Item DUAL_MOX_FUEL_ROD = Ic2rItemsReactor.DUAL_MOX_FUEL_ROD;
	public static final Item QUAD_MOX_FUEL_ROD = Ic2rItemsReactor.QUAD_MOX_FUEL_ROD;
	public static final Item LITHIUM_FUEL_ROD = Ic2rItemsReactor.LITHIUM_FUEL_ROD;
	public static final Item TRITIUM_FUEL_ROD = Ic2rItemsReactor.TRITIUM_FUEL_ROD;
	public static final Item DEPLETED_ISOTOPE_FUEL_ROD = Ic2rItemsReactor.DEPLETED_ISOTOPE_FUEL_ROD;
	public static final Item EMPTY_MUG = Ic2rItemsFarming.EMPTY_MUG;
	public static final Item COFFEE_MUG = Ic2rItemsFarming.COFFEE_MUG;
	public static final Item COLD_COFFEE_MUG = Ic2rItemsFarming.COLD_COFFEE_MUG;
	public static final Item DARK_COFFEE_MUG = Ic2rItemsFarming.DARK_COFFEE_MUG;
	public static final Item CROP_STICK = Ic2rItemsFarming.CROP_STICK;
	public static final Item CROP_SEED_BACK = Ic2rItemsFarming.CROP_SEED_BACK;
	public static final Item CROPNALYZER = Ic2rItemsFarming.CROPNALYZER;
	public static final Item WEEDING_TROWEL = Ic2rItemsFarming.WEEDING_TROWEL;
	public static final Item COFFEE_BEANS = Ic2rItemsFarming.COFFEE_BEANS;
	public static final Item COFFEE_POWDER = Ic2rItemsFarming.COFFEE_POWDER;
	public static final Item FERTILIZER = Ic2rItemsFarming.FERTILIZER;
	public static final Item GRIN_POWDER = Ic2rItemsFarming.GRIN_POWDER;
	public static final Item HOPS = Ic2rItemsFarming.HOPS;
	public static final Item WEED = Ic2rItemsFarming.WEED;
	public static final Item BOBS_YER_UNCLE_RANKS_BERRY = Ic2rItemsFarming.BOBS_YER_UNCLE_RANKS_BERRY;
	public static final Item OIL_BERRY = Ic2rItemsFarming.OIL_BERRY;
	public static final Item MILK_WART = Ic2rItemsFarming.MILK_WART;
	public static final Item SMALL_DIAMOND_DUST = Ic2rItemsFarming.SMALL_DIAMOND_DUST;
	public static final Item ENDER_PEARL_DUST = Ic2rItemsFarming.ENDER_PEARL_DUST;
	public static final Item TERRA_WART = Ic2rItemsFarming.TERRA_WART;
	public static final Item CUTTER = Ic2rItemsTools.CUTTER;
	public static final Item DEBUG_ITEM = Ic2rItemsTools.DEBUG_ITEM;
	public static final Item FORGE_HAMMER = Ic2rItemsTools.FORGE_HAMMER;
	public static final Item TOOL_BOX = Ic2rItemsTools.TOOL_BOX;
	public static final Item CONTAINMENT_BOX = Ic2rItemsTools.CONTAINMENT_BOX;
	public static final Item METER = Ic2rItemsTools.METER;
	public static final Item TREETAP = Ic2rItemsTools.TREETAP;
	public static final Item WRENCH = Ic2rItemsTools.WRENCH;
	public static final Item BRONZE_AXE = Ic2rItemsTools.BRONZE_AXE;
	public static final Item BRONZE_HOE = Ic2rItemsTools.BRONZE_HOE;
	public static final Item BRONZE_SWORD = Ic2rItemsTools.BRONZE_SWORD;
	public static final Item BRONZE_SHOVEL = Ic2rItemsTools.BRONZE_SHOVEL;
	public static final Item BRONZE_PICKAXE = Ic2rItemsTools.BRONZE_PICKAXE;
	public static final Item FREQUENCY_TRANSMITTER = Ic2rItemsTools.FREQUENCY_TRANSMITTER;
	public static final Item REMOTE = Ic2rItemsTools.REMOTE;
	public static final Item MINING_FILTER_CARD = Ic2rItemsTools.MINING_FILTER_CARD;
	public static final Item CROWBAR = Ic2rItemsTools.CROWBAR;
	public static final Item ADVANCED_SCANNER = Ic2rItemsTools.ADVANCED_SCANNER;
	public static final Item CHAINSAW = Ic2rItemsTools.CHAINSAW;
	public static final Item DIAMOND_DRILL = Ic2rItemsTools.DIAMOND_DRILL;
	public static final Item DRILL = Ic2rItemsTools.DRILL;
	public static final Item MINING_LASER = Ic2rItemsTools.MINING_LASER;
	public static final Item ELECTRIC_TREETAP = Ic2rItemsTools.ELECTRIC_TREETAP;
	public static final Item ELECTRIC_WRENCH = Ic2rItemsTools.ELECTRIC_WRENCH;
	public static final Item IRIDIUM_DRILL = Ic2rItemsTools.IRIDIUM_DRILL;
	public static final Item OBSCURATOR = Ic2rItemsTools.OBSCURATOR;
	public static final Item SCANNER = Ic2rItemsTools.SCANNER;
	public static final Item WIND_METER = Ic2rItemsTools.WIND_METER;
	public static final Item PAINTER = Ic2rItemsTools.PAINTER;
	public static final Item BLACK_PAINTER = Ic2rItemsTools.BLACK_PAINTER;
	public static final Item BLUE_PAINTER = Ic2rItemsTools.BLUE_PAINTER;
	public static final Item BROWN_PAINTER = Ic2rItemsTools.BROWN_PAINTER;
	public static final Item CYAN_PAINTER = Ic2rItemsTools.CYAN_PAINTER;
	public static final Item GRAY_PAINTER = Ic2rItemsTools.GRAY_PAINTER;
	public static final Item GREEN_PAINTER = Ic2rItemsTools.GREEN_PAINTER;
	public static final Item LIGHT_BLUE_PAINTER = Ic2rItemsTools.LIGHT_BLUE_PAINTER;
	public static final Item LIGHT_GRAY_PAINTER = Ic2rItemsTools.LIGHT_GRAY_PAINTER;
	public static final Item LIME_PAINTER = Ic2rItemsTools.LIME_PAINTER;
	public static final Item MAGENTA_PAINTER = Ic2rItemsTools.MAGENTA_PAINTER;
	public static final Item ORANGE_PAINTER = Ic2rItemsTools.ORANGE_PAINTER;
	public static final Item PINK_PAINTER = Ic2rItemsTools.PINK_PAINTER;
	public static final Item PURPLE_PAINTER = Ic2rItemsTools.PURPLE_PAINTER;
	public static final Item RED_PAINTER = Ic2rItemsTools.RED_PAINTER;
	public static final Item WHITE_PAINTER = Ic2rItemsTools.WHITE_PAINTER;
	public static final Item YELLOW_PAINTER = Ic2rItemsTools.YELLOW_PAINTER;
	public static final Item BROKEN_RUBBER_BOAT = Ic2rItemsTools.BROKEN_RUBBER_BOAT;
	public static final Item RUBBER_BOAT = Ic2rItemsTools.RUBBER_BOAT;
	public static final Item ELECTRIC_BOAT = Ic2rItemsTools.ELECTRIC_BOAT;
	public static final Item CARBON_BOAT = Ic2rItemsTools.CARBON_BOAT;
	public static final Item RE_BATTERY = Ic2rItemsTools.RE_BATTERY;
	public static final Item ADVANCED_RE_BATTERY = Ic2rItemsTools.ADVANCED_RE_BATTERY;
	public static final Item ENERGY_CRYSTAL = Ic2rItemsTools.ENERGY_CRYSTAL;
	public static final Item LAPOTRON_CRYSTAL = Ic2rItemsTools.LAPOTRON_CRYSTAL;
	public static final Item SINGLE_USE_BATTERY = Ic2rItemsTools.SINGLE_USE_BATTERY;
	public static final Item CHARGING_RE_BATTERY = Ic2rItemsTools.CHARGING_RE_BATTERY;
	public static final Item ADVANCED_CHARGING_RE_BATTERY = Ic2rItemsTools.ADVANCED_CHARGING_RE_BATTERY;
	public static final Item CHARGING_ENERGY_CRYSTAL = Ic2rItemsTools.CHARGING_ENERGY_CRYSTAL;
	public static final Item CHARGING_LAPOTRON_CRYSTAL = Ic2rItemsTools.CHARGING_LAPOTRON_CRYSTAL;
	public static final Item WOODEN_ROTOR = Ic2rItemsTools.WOODEN_ROTOR;
	public static final Item BRONZE_ROTOR = Ic2rItemsTools.BRONZE_ROTOR;
	public static final Item IRON_ROTOR = Ic2rItemsTools.IRON_ROTOR;
	public static final Item STEEL_ROTOR = Ic2rItemsTools.STEEL_ROTOR;
	public static final Item CARBON_ROTOR = Ic2rItemsTools.CARBON_ROTOR;
	public static final Item FACADE_CELL = Ic2rItemsCells.FACADE_CELL;
	public static final Item WATER_CELL = Ic2rItemsCells.WATER_CELL;
	public static final Item LAVA_CELL = Ic2rItemsCells.LAVA_CELL;
	public static final Item AIR_CELL = Ic2rItemsCells.AIR_CELL;
	public static final Item ELECTROLYZED_WATER_CELL = Ic2rItemsCells.ELECTROLYZED_WATER_CELL;
	public static final Item WEED_EX_CELL = Ic2rItemsCells.WEED_EX_CELL;
	public static final Item HYDRATION_CELL = Ic2rItemsCells.HYDRATION_CELL;
	public static final Item UU_MATTER_CELL = Ic2rItemsCells.UU_MATTER_CELL;
	public static final Item CONSTRUCTION_FOAM_CELL = Ic2rItemsCells.CONSTRUCTION_FOAM_CELL;
	public static final Item COOLANT_CELL = Ic2rItemsCells.COOLANT_CELL;
	public static final Item CREOSOTE_CELL = Ic2rItemsCells.CREOSOTE_CELL;
	public static final Item HOT_COOLANT_CELL = Ic2rItemsCells.HOT_COOLANT_CELL;
	public static final Item PAHOEHOE_LAVA_CELL = Ic2rItemsCells.PAHOEHOE_LAVA_CELL;
	public static final Item BIOMASS_CELL = Ic2rItemsCells.BIOMASS_CELL;
	public static final Item BIOGAS_CELL = Ic2rItemsCells.BIOGAS_CELL;
	public static final Item DISTILLED_WATER_CELL = Ic2rItemsCells.DISTILLED_WATER_CELL;
	public static final Item SUPERHEATED_STEAM_CELL = Ic2rItemsCells.SUPERHEATED_STEAM_CELL;
	public static final Item STEAM_CELL = Ic2rItemsCells.STEAM_CELL;
	public static final Item HOT_WATER_CELL = Ic2rItemsCells.HOT_WATER_CELL;
	public static final Item HYDROGEN_CELL = Ic2rItemsCells.HYDROGEN_CELL;
	public static final Item OXYGEN_CELL = Ic2rItemsCells.OXYGEN_CELL;
	public static final Item HEAVY_WATER_CELL = Ic2rItemsCells.HEAVY_WATER_CELL;
	public static final Item OVERCLOCKER_UPGRADE = Ic2rItemsUpgrades.OVERCLOCKER_UPGRADE;
	public static final Item TRANSFORMER_UPGRADE = Ic2rItemsUpgrades.TRANSFORMER_UPGRADE;
	public static final Item ENERGY_STORAGE_UPGRADE = Ic2rItemsUpgrades.ENERGY_STORAGE_UPGRADE;
	public static final Item REDSTONE_INVERTER_UPGRADE = Ic2rItemsUpgrades.REDSTONE_INVERTER_UPGRADE;
	public static final Item EJECTOR_UPGRADE = Ic2rItemsUpgrades.EJECTOR_UPGRADE;
	public static final Item ADVANCED_EJECTOR_UPGRADE = Ic2rItemsUpgrades.ADVANCED_EJECTOR_UPGRADE;
	public static final Item PULLING_UPGRADE = Ic2rItemsUpgrades.PULLING_UPGRADE;
	public static final Item ADVANCED_PULLING_UPGRADE = Ic2rItemsUpgrades.ADVANCED_PULLING_UPGRADE;
	public static final Item FLUID_EJECTOR_UPGRADE = Ic2rItemsUpgrades.FLUID_EJECTOR_UPGRADE;
	public static final Item FLUID_PULLING_UPGRADE = Ic2rItemsUpgrades.FLUID_PULLING_UPGRADE;
	public static final Item REMOTE_INTERFACE_UPGRADE = Ic2rItemsUpgrades.REMOTE_INTERFACE_UPGRADE;
	public static final Item FILLED_TIN_CAN = Ic2rItemsUpgrades.FILLED_TIN_CAN;
	public static final Item BLANK_TFBP = Ic2rItemsUpgrades.BLANK_TFBP;
	public static final Item CHILLING_TFBP = Ic2rItemsUpgrades.CHILLING_TFBP;
	public static final Item CULTIVATION_TFBP = Ic2rItemsUpgrades.CULTIVATION_TFBP;
	public static final Item DESERTIFICATION_TFBP = Ic2rItemsUpgrades.DESERTIFICATION_TFBP;
	public static final Item FLATIFICATION_TFBP = Ic2rItemsUpgrades.FLATIFICATION_TFBP;
	public static final Item IRRIGATION_TFBP = Ic2rItemsUpgrades.IRRIGATION_TFBP;
	public static final Item MUSHROOM_TFBP = Ic2rItemsUpgrades.MUSHROOM_TFBP;
	public static final Item NANO_SABER = Ic2rItemsArmor.NANO_SABER;
	public static final Item ALLOY_CHESTPLATE = Ic2rItemsArmor.ALLOY_CHESTPLATE;
	public static final Item BRONZE_BOOTS = Ic2rItemsArmor.BRONZE_BOOTS;
	public static final Item BRONZE_CHESTPLATE = Ic2rItemsArmor.BRONZE_CHESTPLATE;
	public static final Item BRONZE_HELMET = Ic2rItemsArmor.BRONZE_HELMET;
	public static final Item BRONZE_LEGGINGS = Ic2rItemsArmor.BRONZE_LEGGINGS;
	public static final Item CF_PACK = Ic2rItemsArmor.CF_PACK;
	public static final Item FOAM_SPRAYER = Ic2rItemsArmor.FOAM_SPRAYER;
	public static final Item HAZMAT_CHESTPLATE = Ic2rItemsArmor.HAZMAT_CHESTPLATE;
	public static final Item HAZMAT_HELMET = Ic2rItemsArmor.HAZMAT_HELMET;
	public static final Item HAZMAT_LEGGINGS = Ic2rItemsArmor.HAZMAT_LEGGINGS;
	public static final Item JETPACK = Ic2rItemsArmor.JETPACK;
	public static final Item JETPACK_ELECTRIC = Ic2rItemsArmor.JETPACK_ELECTRIC;
	public static final Item BATPACK = Ic2rItemsArmor.BATPACK;
	public static final Item ADVANCED_BATPACK = Ic2rItemsArmor.ADVANCED_BATPACK;
	public static final Item ENERGY_PACK = Ic2rItemsArmor.ENERGY_PACK;
	public static final Item LAPPACK = Ic2rItemsArmor.LAPPACK;
	public static final Item NANO_BOOTS = Ic2rItemsArmor.NANO_BOOTS;
	public static final Item NANO_CHESTPLATE = Ic2rItemsArmor.NANO_CHESTPLATE;
	public static final Item NANO_HELMET = Ic2rItemsArmor.NANO_HELMET;
	public static final Item NANO_LEGGINGS = Ic2rItemsArmor.NANO_LEGGINGS;
	public static final Item QUANTUM_BOOTS = Ic2rItemsArmor.QUANTUM_BOOTS;
	public static final Item QUANTUM_CHESTPLATE = Ic2rItemsArmor.QUANTUM_CHESTPLATE;
	public static final Item QUANTUM_HELMET = Ic2rItemsArmor.QUANTUM_HELMET;
	public static final Item QUANTUM_LEGGINGS = Ic2rItemsArmor.QUANTUM_LEGGINGS;
	public static final Item RUBBER_BOOTS = Ic2rItemsArmor.RUBBER_BOOTS;
	public static final Item NIGHT_VISION_GOGGLES = Ic2rItemsArmor.NIGHT_VISION_GOGGLES;
	public static final Item SOLAR_HELMET = Ic2rItemsArmor.SOLAR_HELMET;
	public static final Item STATIC_BOOTS = Ic2rItemsArmor.STATIC_BOOTS;

	public static final EnumMap<Ic2rItemGroupType, List<Supplier<Item>>> CREATIVE_TAB_ITEMS = new EnumMap<>(Ic2rItemGroupType.class);

	static
	{
		for (Ic2rItemGroupType type : Ic2rItemGroupType.values())
		{
			CREATIVE_TAB_ITEMS.put(type, new ArrayList<>());
		}
		addToCreativeTab(Ic2rItemGroupType.COMBAT, () -> ALLOY_CHESTPLATE);
		addToCreativeTab(Ic2rItemGroupType.COMBAT, () -> BRONZE_BOOTS);
		addToCreativeTab(Ic2rItemGroupType.COMBAT, () -> BRONZE_CHESTPLATE);
		addToCreativeTab(Ic2rItemGroupType.COMBAT, () -> BRONZE_HELMET);
		addToCreativeTab(Ic2rItemGroupType.COMBAT, () -> BRONZE_LEGGINGS);
		addToCreativeTab(Ic2rItemGroupType.COMBAT, () -> CF_PACK);
		addToCreativeTab(Ic2rItemGroupType.COMBAT, () -> HAZMAT_CHESTPLATE);
		addToCreativeTab(Ic2rItemGroupType.COMBAT, () -> HAZMAT_HELMET);
		addToCreativeTab(Ic2rItemGroupType.COMBAT, () -> HAZMAT_LEGGINGS);
		addToCreativeTab(Ic2rItemGroupType.COMBAT, () -> ITNT);
		addToCreativeTab(Ic2rItemGroupType.COMBAT, () -> DYNAMITE);
		addToCreativeTab(Ic2rItemGroupType.COMBAT, () -> DYNAMITE_STICKY);
		addToCreativeTab(Ic2rItemGroupType.COMBAT, () -> REMOTE);
		addToCreativeTab(Ic2rItemGroupType.COMBAT, () -> JETPACK);
		addToCreativeTab(Ic2rItemGroupType.COMBAT, () -> JETPACK_ELECTRIC);
		addToCreativeTab(Ic2rItemGroupType.COMBAT, () -> BATPACK);
		addToCreativeTab(Ic2rItemGroupType.COMBAT, () -> ADVANCED_BATPACK);
		addToCreativeTab(Ic2rItemGroupType.COMBAT, () -> ENERGY_PACK);
		addToCreativeTab(Ic2rItemGroupType.COMBAT, () -> LAPPACK);
		addToCreativeTab(Ic2rItemGroupType.COMBAT, () -> NANO_BOOTS);
		addToCreativeTab(Ic2rItemGroupType.COMBAT, () -> NANO_CHESTPLATE);
		addToCreativeTab(Ic2rItemGroupType.COMBAT, () -> NANO_HELMET);
		addToCreativeTab(Ic2rItemGroupType.COMBAT, () -> NANO_LEGGINGS);
		addToCreativeTab(Ic2rItemGroupType.COMBAT, () -> NANO_SABER);
		addToCreativeTab(Ic2rItemGroupType.COMBAT, () -> NIGHT_VISION_GOGGLES);
		addToCreativeTab(Ic2rItemGroupType.COMBAT, () -> SOLAR_HELMET);
		addToCreativeTab(Ic2rItemGroupType.COMBAT, () -> STATIC_BOOTS);
		addToCreativeTab(Ic2rItemGroupType.COMBAT, () -> NUKE);
		addToCreativeTab(Ic2rItemGroupType.COMBAT, () -> QUANTUM_BOOTS);
		addToCreativeTab(Ic2rItemGroupType.COMBAT, () -> QUANTUM_CHESTPLATE);
		addToCreativeTab(Ic2rItemGroupType.COMBAT, () -> QUANTUM_HELMET);
		addToCreativeTab(Ic2rItemGroupType.COMBAT, () -> QUANTUM_LEGGINGS);
		addToCreativeTab(Ic2rItemGroupType.COMBAT, () -> RUBBER_BOOTS);
		addToCreativeTab(Ic2rItemGroupType.FARMING, () -> COFFEE_BEANS);
		addToCreativeTab(Ic2rItemGroupType.FARMING, () -> COFFEE_MUG);
		addToCreativeTab(Ic2rItemGroupType.FARMING, () -> COFFEE_POWDER);
		addToCreativeTab(Ic2rItemGroupType.FARMING, () -> COLD_COFFEE_MUG);
		addToCreativeTab(Ic2rItemGroupType.FARMING, () -> CROP_SEED_BACK);
		addToCreativeTab(Ic2rItemGroupType.FARMING, () -> CROP_STICK);
		addToCreativeTab(Ic2rItemGroupType.FARMING, () -> DARK_COFFEE_MUG);
		addToCreativeTab(Ic2rItemGroupType.FARMING, () -> EMPTY_MUG);
		addToCreativeTab(Ic2rItemGroupType.FARMING, () -> FERTILIZER);
		addToCreativeTab(Ic2rItemGroupType.FARMING, () -> GRIN_POWDER);
		addToCreativeTab(Ic2rItemGroupType.FARMING, () -> HOPS);
		addToCreativeTab(Ic2rItemGroupType.FARMING, () -> RUBBER_SAPLING);
		addToCreativeTab(Ic2rItemGroupType.FARMING, () -> TERRA_WART);
		addToCreativeTab(Ic2rItemGroupType.FARMING, () -> WEED);
		addToCreativeTab(Ic2rItemGroupType.FARMING, () -> WEEDING_TROWEL);
		addToCreativeTab(Ic2rItemGroupType.FARMING, () -> BOBS_YER_UNCLE_RANKS_BERRY);
		addToCreativeTab(Ic2rItemGroupType.FARMING, () -> OIL_BERRY);
		addToCreativeTab(Ic2rItemGroupType.FARMING, () -> MILK_WART);
		addToCreativeTab(Ic2rItemGroupType.GENERAL, () -> ADVANCED_MACHINE);
		addToCreativeTab(Ic2rItemGroupType.GENERAL, () -> BLACK_WALL);
		addToCreativeTab(Ic2rItemGroupType.GENERAL, () -> BLUE_WALL);
		addToCreativeTab(Ic2rItemGroupType.GENERAL, () -> BRONZE_BLOCK);
		addToCreativeTab(Ic2rItemGroupType.GENERAL, () -> BRONZE_STORAGE_BOX);
		addToCreativeTab(Ic2rItemGroupType.GENERAL, () -> BRONZE_TANK);
		addToCreativeTab(Ic2rItemGroupType.GENERAL, () -> BROWN_WALL);
		addToCreativeTab(Ic2rItemGroupType.GENERAL, () -> CYAN_WALL);
		addToCreativeTab(Ic2rItemGroupType.GENERAL, () -> DEEPSLATE_LEAD_ORE);
		addToCreativeTab(Ic2rItemGroupType.GENERAL, () -> DEEPSLATE_TIN_ORE);
		addToCreativeTab(Ic2rItemGroupType.GENERAL, () -> DEEPSLATE_URANIUM_ORE);
		addToCreativeTab(Ic2rItemGroupType.GENERAL, () -> FOAM);
		addToCreativeTab(Ic2rItemGroupType.GENERAL, () -> GRAY_WALL);
		addToCreativeTab(Ic2rItemGroupType.GENERAL, () -> GREEN_WALL);
		addToCreativeTab(Ic2rItemGroupType.GENERAL, () -> IRIDIUM_STORAGE_BOX);
		addToCreativeTab(Ic2rItemGroupType.GENERAL, () -> IRIDIUM_TANK);
		addToCreativeTab(Ic2rItemGroupType.GENERAL, () -> IRON_FENCE);
		addToCreativeTab(Ic2rItemGroupType.GENERAL, () -> IRON_STORAGE_BOX);
		addToCreativeTab(Ic2rItemGroupType.GENERAL, () -> IRON_TANK);
		addToCreativeTab(Ic2rItemGroupType.GENERAL, () -> LEAD_BLOCK);
		addToCreativeTab(Ic2rItemGroupType.GENERAL, () -> LEAD_ORE);
		addToCreativeTab(Ic2rItemGroupType.GENERAL, () -> LIGHT_BLUE_WALL);
		addToCreativeTab(Ic2rItemGroupType.GENERAL, () -> LIGHT_GRAY_WALL);
		addToCreativeTab(Ic2rItemGroupType.GENERAL, () -> LIME_WALL);
		addToCreativeTab(Ic2rItemGroupType.GENERAL, () -> MACHINE);
		addToCreativeTab(Ic2rItemGroupType.GENERAL, () -> MAGENTA_WALL);
		addToCreativeTab(Ic2rItemGroupType.GENERAL, () -> ORANGE_WALL);
		addToCreativeTab(Ic2rItemGroupType.GENERAL, () -> PINK_WALL);
		addToCreativeTab(Ic2rItemGroupType.GENERAL, () -> PURPLE_WALL);
		addToCreativeTab(Ic2rItemGroupType.GENERAL, () -> RAW_LEAD_BLOCK);
		addToCreativeTab(Ic2rItemGroupType.GENERAL, () -> RAW_TIN_BLOCK);
		addToCreativeTab(Ic2rItemGroupType.GENERAL, () -> RAW_URANIUM_BLOCK);
		addToCreativeTab(Ic2rItemGroupType.GENERAL, () -> RED_WALL);
		addToCreativeTab(Ic2rItemGroupType.GENERAL, () -> REINFORCED_DOOR);
		addToCreativeTab(Ic2rItemGroupType.GENERAL, () -> REINFORCED_GLASS);
		addToCreativeTab(Ic2rItemGroupType.GENERAL, () -> REINFORCED_STONE);
		addToCreativeTab(Ic2rItemGroupType.GENERAL, () -> RESIN_SHEET);
		addToCreativeTab(Ic2rItemGroupType.GENERAL, () -> RUBBER_BUTTON);
		addToCreativeTab(Ic2rItemGroupType.GENERAL, () -> RUBBER_DOOR);
		addToCreativeTab(Ic2rItemGroupType.GENERAL, () -> RUBBER_FENCE);
		addToCreativeTab(Ic2rItemGroupType.GENERAL, () -> RUBBER_FENCE_GATE);
		addToCreativeTab(Ic2rItemGroupType.GENERAL, () -> RUBBER_LEAVES);
		addToCreativeTab(Ic2rItemGroupType.GENERAL, () -> RUBBER_LOG);
		addToCreativeTab(Ic2rItemGroupType.GENERAL, () -> RUBBER_PLANKS);
		addToCreativeTab(Ic2rItemGroupType.GENERAL, () -> RUBBER_PRESSURE_PLATE);
		addToCreativeTab(Ic2rItemGroupType.GENERAL, () -> RUBBER_SHEET);
		addToCreativeTab(Ic2rItemGroupType.GENERAL, () -> RUBBER_SIGN);
		addToCreativeTab(Ic2rItemGroupType.GENERAL, () -> RUBBER_SLAB);
		addToCreativeTab(Ic2rItemGroupType.GENERAL, () -> RUBBER_STAIRS);
		addToCreativeTab(Ic2rItemGroupType.GENERAL, () -> RUBBER_TRAPDOOR);
		addToCreativeTab(Ic2rItemGroupType.GENERAL, () -> RUBBER_WOOD);
		addToCreativeTab(Ic2rItemGroupType.GENERAL, () -> SILVER_BLOCK);
		addToCreativeTab(Ic2rItemGroupType.GENERAL, () -> STEEL_BLOCK);
		addToCreativeTab(Ic2rItemGroupType.GENERAL, () -> STEEL_STORAGE_BOX);
		addToCreativeTab(Ic2rItemGroupType.GENERAL, () -> STEEL_TANK);
		addToCreativeTab(Ic2rItemGroupType.GENERAL, () -> STRIPPED_RUBBER_LOG);
		addToCreativeTab(Ic2rItemGroupType.GENERAL, () -> STRIPPED_RUBBER_WOOD);
		addToCreativeTab(Ic2rItemGroupType.GENERAL, () -> TANK);
		addToCreativeTab(Ic2rItemGroupType.GENERAL, () -> TIN_BLOCK);
		addToCreativeTab(Ic2rItemGroupType.GENERAL, () -> TIN_ORE);
		addToCreativeTab(Ic2rItemGroupType.GENERAL, () -> URANIUM_BLOCK);
		addToCreativeTab(Ic2rItemGroupType.GENERAL, () -> URANIUM_ORE);
		addToCreativeTab(Ic2rItemGroupType.GENERAL, () -> WHITE_WALL);
		addToCreativeTab(Ic2rItemGroupType.GENERAL, () -> WOODEN_STORAGE_BOX);
		addToCreativeTab(Ic2rItemGroupType.GENERAL, () -> WOOL_SHEET);
		addToCreativeTab(Ic2rItemGroupType.GENERAL, () -> YELLOW_WALL);
		addToCreativeTab(Ic2rItemGroupType.GENERATORS_AND_WIRING, () -> BATBOX);
		addToCreativeTab(Ic2rItemGroupType.GENERATORS_AND_WIRING, () -> BATBOX_CHARGEPAD);
		addToCreativeTab(Ic2rItemGroupType.GENERATORS_AND_WIRING, () -> CESU);
		addToCreativeTab(Ic2rItemGroupType.GENERATORS_AND_WIRING, () -> CESU_CHARGEPAD);
		addToCreativeTab(Ic2rItemGroupType.GENERATORS_AND_WIRING, () -> COPPER_CABLE);
		addToCreativeTab(Ic2rItemGroupType.GENERATORS_AND_WIRING, () -> CREATIVE_GENERATOR);
		addToCreativeTab(Ic2rItemGroupType.GENERATORS_AND_WIRING, () -> DETECTOR_CABLE);
		addToCreativeTab(Ic2rItemGroupType.GENERATORS_AND_WIRING, () -> DOUBLE_INSULATED_GOLD_CABLE);
		addToCreativeTab(Ic2rItemGroupType.GENERATORS_AND_WIRING, () -> DOUBLE_INSULATED_IRON_CABLE);
		addToCreativeTab(Ic2rItemGroupType.GENERATORS_AND_WIRING, () -> ELECTRIC_HEAT_GENERATOR);
		addToCreativeTab(Ic2rItemGroupType.GENERATORS_AND_WIRING, () -> ELECTRIC_KINETIC_GENERATOR);
		addToCreativeTab(Ic2rItemGroupType.GENERATORS_AND_WIRING, () -> EV_TRANSFORMER);
		addToCreativeTab(Ic2rItemGroupType.GENERATORS_AND_WIRING, () -> FLUID_HEAT_GENERATOR);
		addToCreativeTab(Ic2rItemGroupType.GENERATORS_AND_WIRING, () -> GENERATOR);
		addToCreativeTab(Ic2rItemGroupType.GENERATORS_AND_WIRING, () -> GEO_GENERATOR);
		addToCreativeTab(Ic2rItemGroupType.GENERATORS_AND_WIRING, () -> GLASS_FIBRE_CABLE);
		addToCreativeTab(Ic2rItemGroupType.GENERATORS_AND_WIRING, () -> GOLD_CABLE);
		addToCreativeTab(Ic2rItemGroupType.GENERATORS_AND_WIRING, () -> HV_TRANSFORMER);
		addToCreativeTab(Ic2rItemGroupType.GENERATORS_AND_WIRING, () -> INSULATED_COPPER_CABLE);
		addToCreativeTab(Ic2rItemGroupType.GENERATORS_AND_WIRING, () -> INSULATED_GOLD_CABLE);
		addToCreativeTab(Ic2rItemGroupType.GENERATORS_AND_WIRING, () -> INSULATED_IRON_CABLE);
		addToCreativeTab(Ic2rItemGroupType.GENERATORS_AND_WIRING, () -> INSULATED_TIN_CABLE);
		addToCreativeTab(Ic2rItemGroupType.GENERATORS_AND_WIRING, () -> IRON_CABLE);
		addToCreativeTab(Ic2rItemGroupType.GENERATORS_AND_WIRING, () -> KINETIC_GENERATOR);
		addToCreativeTab(Ic2rItemGroupType.GENERATORS_AND_WIRING, () -> LV_TRANSFORMER);
		addToCreativeTab(Ic2rItemGroupType.GENERATORS_AND_WIRING, () -> MANUAL_KINETIC_GENERATOR);
		addToCreativeTab(Ic2rItemGroupType.GENERATORS_AND_WIRING, () -> MFE);
		addToCreativeTab(Ic2rItemGroupType.GENERATORS_AND_WIRING, () -> MFE_CHARGEPAD);
		addToCreativeTab(Ic2rItemGroupType.GENERATORS_AND_WIRING, () -> MFSU);
		addToCreativeTab(Ic2rItemGroupType.GENERATORS_AND_WIRING, () -> MFSU_CHARGEPAD);
		addToCreativeTab(Ic2rItemGroupType.GENERATORS_AND_WIRING, () -> MV_TRANSFORMER);
		addToCreativeTab(Ic2rItemGroupType.GENERATORS_AND_WIRING, () -> RT_GENERATOR);
		addToCreativeTab(Ic2rItemGroupType.GENERATORS_AND_WIRING, () -> RT_HEAT_GENERATOR);
		addToCreativeTab(Ic2rItemGroupType.GENERATORS_AND_WIRING, () -> SEMIFLUID_GENERATOR);
		addToCreativeTab(Ic2rItemGroupType.GENERATORS_AND_WIRING, () -> SOLAR_GENERATOR);
		addToCreativeTab(Ic2rItemGroupType.GENERATORS_AND_WIRING, () -> SOLID_HEAT_GENERATOR);
		addToCreativeTab(Ic2rItemGroupType.GENERATORS_AND_WIRING, () -> SPLITTER_CABLE);
		addToCreativeTab(Ic2rItemGroupType.GENERATORS_AND_WIRING, () -> STEAM_KINETIC_GENERATOR);
		addToCreativeTab(Ic2rItemGroupType.GENERATORS_AND_WIRING, () -> STIRLING_GENERATOR);
		addToCreativeTab(Ic2rItemGroupType.GENERATORS_AND_WIRING, () -> STIRLING_KINETIC_GENERATOR);
		addToCreativeTab(Ic2rItemGroupType.GENERATORS_AND_WIRING, () -> TIN_CABLE);
		addToCreativeTab(Ic2rItemGroupType.GENERATORS_AND_WIRING, () -> TRIPLE_INSULATED_IRON_CABLE);
		addToCreativeTab(Ic2rItemGroupType.GENERATORS_AND_WIRING, () -> WATER_GENERATOR);
		addToCreativeTab(Ic2rItemGroupType.GENERATORS_AND_WIRING, () -> WATER_KINETIC_GENERATOR);
		addToCreativeTab(Ic2rItemGroupType.GENERATORS_AND_WIRING, () -> WIND_GENERATOR);
		addToCreativeTab(Ic2rItemGroupType.GENERATORS_AND_WIRING, () -> WIND_KINETIC_GENERATOR);
		addToCreativeTab(Ic2rItemGroupType.MACHINES, () -> ADVANCED_MINER);
		addToCreativeTab(Ic2rItemGroupType.MACHINES, () -> BATCH_CRAFTER);
		addToCreativeTab(Ic2rItemGroupType.MACHINES, () -> BLAST_FURNACE);
		addToCreativeTab(Ic2rItemGroupType.MACHINES, () -> BLOCK_CUTTER);
		addToCreativeTab(Ic2rItemGroupType.MACHINES, () -> CANNER);
		addToCreativeTab(Ic2rItemGroupType.MACHINES, () -> CENTRIFUGE);
		addToCreativeTab(Ic2rItemGroupType.MACHINES, () -> CHUNK_LOADER);
		addToCreativeTab(Ic2rItemGroupType.MACHINES, () -> COMPRESSOR);
		addToCreativeTab(Ic2rItemGroupType.MACHINES, () -> CONDENSER);
		addToCreativeTab(Ic2rItemGroupType.MACHINES, () -> COKE_KILN);
		addToCreativeTab(Ic2rItemGroupType.MACHINES, () -> COKE_KILN_HATCH);
		addToCreativeTab(Ic2rItemGroupType.MACHINES, () -> COKE_KILN_GRATE);
		addToCreativeTab(Ic2rItemGroupType.MACHINES, () -> CROPMATRON);
		addToCreativeTab(Ic2rItemGroupType.MACHINES, () -> CROP_HARVESTER);
		addToCreativeTab(Ic2rItemGroupType.MACHINES, () -> ELECTRIC_FURNACE);
		addToCreativeTab(Ic2rItemGroupType.MACHINES, () -> ELECTROLYZER);
		addToCreativeTab(Ic2rItemGroupType.MACHINES, () -> ENERGY_O_MAT);
		addToCreativeTab(Ic2rItemGroupType.MACHINES, () -> EXTRACTOR);
		addToCreativeTab(Ic2rItemGroupType.MACHINES, () -> FERMENTER);
		addToCreativeTab(Ic2rItemGroupType.MACHINES, () -> FLUID_BOTTLER);
		addToCreativeTab(Ic2rItemGroupType.MACHINES, () -> FLUID_DISTRIBUTOR);
		addToCreativeTab(Ic2rItemGroupType.MACHINES, () -> FLUID_REGULATOR);
		addToCreativeTab(Ic2rItemGroupType.MACHINES, () -> INDUCTION_FURNACE);
		addToCreativeTab(Ic2rItemGroupType.MACHINES, () -> INDUSTRIAL_WORKBENCH);
		addToCreativeTab(Ic2rItemGroupType.MACHINES, () -> IRON_FURNACE);
		addToCreativeTab(Ic2rItemGroupType.MACHINES, () -> ITEM_BUFFER);
		addToCreativeTab(Ic2rItemGroupType.MACHINES, () -> LIQUID_HEAT_EXCHANGER);
		addToCreativeTab(Ic2rItemGroupType.MACHINES, () -> MACERATOR);
		addToCreativeTab(Ic2rItemGroupType.MACHINES, () -> MAGNETIZER);
		addToCreativeTab(Ic2rItemGroupType.MACHINES, () -> MATTER_GENERATOR);
		addToCreativeTab(Ic2rItemGroupType.MACHINES, () -> METAL_FORMER);
		addToCreativeTab(Ic2rItemGroupType.MACHINES, () -> MINER);
		addToCreativeTab(Ic2rItemGroupType.MACHINES, () -> ORE_WASHING_PLANT);
		addToCreativeTab(Ic2rItemGroupType.MACHINES, () -> PATTERN_STORAGE);
		addToCreativeTab(Ic2rItemGroupType.MACHINES, () -> PERSONAL_CHEST);
		addToCreativeTab(Ic2rItemGroupType.MACHINES, () -> PUMP);
		addToCreativeTab(Ic2rItemGroupType.MACHINES, () -> RECYCLER);
		addToCreativeTab(Ic2rItemGroupType.MACHINES, () -> REPLICATOR);
		addToCreativeTab(Ic2rItemGroupType.MACHINES, () -> SOLAR_DISTILLER);
		addToCreativeTab(Ic2rItemGroupType.MACHINES, () -> SOLID_CANNER);
		addToCreativeTab(Ic2rItemGroupType.MACHINES, () -> SORTING_MACHINE);
		addToCreativeTab(Ic2rItemGroupType.MACHINES, () -> STEAM_GENERATOR);
		addToCreativeTab(Ic2rItemGroupType.MACHINES, () -> STEAM_REPRESSURIZER);
		addToCreativeTab(Ic2rItemGroupType.MACHINES, () -> TELEPORTER);
		addToCreativeTab(Ic2rItemGroupType.MACHINES, () -> TERRAFORMER);
		addToCreativeTab(Ic2rItemGroupType.MACHINES, () -> TESLA_COIL);
		addToCreativeTab(Ic2rItemGroupType.MACHINES, () -> LUMINATOR_FLAT);
		addToCreativeTab(Ic2rItemGroupType.MACHINES, () -> TRADE_O_MAT);
		addToCreativeTab(Ic2rItemGroupType.MACHINES, () -> UU_SCANNER);
		addToCreativeTab(Ic2rItemGroupType.MACHINES, () -> WEIGHTED_FLUID_DISTRIBUTOR);
		addToCreativeTab(Ic2rItemGroupType.MACHINES, () -> WEIGHTED_ITEM_DISTRIBUTOR);
		addToCreativeTab(Ic2rItemGroupType.MATERIALS, () -> ADVANCED_CIRCUIT);
		addToCreativeTab(Ic2rItemGroupType.MATERIALS, () -> ALLOY);
		addToCreativeTab(Ic2rItemGroupType.MATERIALS, () -> ASHES);
		addToCreativeTab(Ic2rItemGroupType.MATERIALS, () -> BIO_CHAFF);
		addToCreativeTab(Ic2rItemGroupType.MATERIALS, () -> BRONZE_CASING);
		addToCreativeTab(Ic2rItemGroupType.MATERIALS, () -> BRONZE_DUST);
		addToCreativeTab(Ic2rItemGroupType.MATERIALS, () -> BRONZE_INGOT);
		addToCreativeTab(Ic2rItemGroupType.MATERIALS, () -> BRONZE_PLATE);
		addToCreativeTab(Ic2rItemGroupType.MATERIALS, () -> BRONZE_ROTOR_BLADE);
		addToCreativeTab(Ic2rItemGroupType.MATERIALS, () -> BRONZE_SHAFT);
		addToCreativeTab(Ic2rItemGroupType.MATERIALS, () -> CARBON_FIBRE);
		addToCreativeTab(Ic2rItemGroupType.MATERIALS, () -> CARBON_MESH);
		addToCreativeTab(Ic2rItemGroupType.MATERIALS, () -> CARBON_PLATE);
		addToCreativeTab(Ic2rItemGroupType.MATERIALS, () -> CARBON_ROTOR_BLADE);
		addToCreativeTab(Ic2rItemGroupType.MATERIALS, () -> CF_POWDER);
		addToCreativeTab(Ic2rItemGroupType.MATERIALS, () -> CIRCUIT);
		addToCreativeTab(Ic2rItemGroupType.MATERIALS, () -> CLAY_DUST);
		addToCreativeTab(Ic2rItemGroupType.MATERIALS, () -> COAL_BALL);
		addToCreativeTab(Ic2rItemGroupType.MATERIALS, () -> COAL_BLOCK);
		addToCreativeTab(Ic2rItemGroupType.MATERIALS, () -> COAL_CHUNK);
		addToCreativeTab(Ic2rItemGroupType.MATERIALS, () -> COAL_DUST);
		addToCreativeTab(Ic2rItemGroupType.MATERIALS, () -> COAL_FUEL_DUST);
		addToCreativeTab(Ic2rItemGroupType.MATERIALS, () -> COKE);
		addToCreativeTab(Ic2rItemGroupType.MATERIALS, () -> COIL);
		addToCreativeTab(Ic2rItemGroupType.MATERIALS, () -> COIN);
		addToCreativeTab(Ic2rItemGroupType.MATERIALS, () -> COPPER_BOILER);
		addToCreativeTab(Ic2rItemGroupType.MATERIALS, () -> COPPER_CASING);
		addToCreativeTab(Ic2rItemGroupType.MATERIALS, () -> COPPER_DUST);
		addToCreativeTab(Ic2rItemGroupType.MATERIALS, () -> COPPER_PLATE);
		addToCreativeTab(Ic2rItemGroupType.MATERIALS, () -> CRUSHED_COPPER);
		addToCreativeTab(Ic2rItemGroupType.MATERIALS, () -> CRUSHED_GOLD);
		addToCreativeTab(Ic2rItemGroupType.MATERIALS, () -> CRUSHED_IRON);
		addToCreativeTab(Ic2rItemGroupType.MATERIALS, () -> CRUSHED_LEAD);
		addToCreativeTab(Ic2rItemGroupType.MATERIALS, () -> CRUSHED_SILVER);
		addToCreativeTab(Ic2rItemGroupType.MATERIALS, () -> CRUSHED_TIN);
		addToCreativeTab(Ic2rItemGroupType.MATERIALS, () -> CRUSHED_URANIUM);
		addToCreativeTab(Ic2rItemGroupType.MATERIALS, () -> CRYSTAL_MEMORY);
		addToCreativeTab(Ic2rItemGroupType.MATERIALS, () -> DENSE_BRONZE_PLATE);
		addToCreativeTab(Ic2rItemGroupType.MATERIALS, () -> DENSE_COPPER_PLATE);
		addToCreativeTab(Ic2rItemGroupType.MATERIALS, () -> DENSE_GOLD_PLATE);
		addToCreativeTab(Ic2rItemGroupType.MATERIALS, () -> DENSE_IRON_PLATE);
		addToCreativeTab(Ic2rItemGroupType.MATERIALS, () -> DENSE_LAPIS_PLATE);
		addToCreativeTab(Ic2rItemGroupType.MATERIALS, () -> DENSE_LEAD_PLATE);
		addToCreativeTab(Ic2rItemGroupType.MATERIALS, () -> DENSE_OBSIDIAN_PLATE);
		addToCreativeTab(Ic2rItemGroupType.MATERIALS, () -> DENSE_STEEL_PLATE);
		addToCreativeTab(Ic2rItemGroupType.MATERIALS, () -> DENSE_TIN_PLATE);
		addToCreativeTab(Ic2rItemGroupType.MATERIALS, () -> DEPLETED_DUAL_MOX_FUEL_ROD);
		addToCreativeTab(Ic2rItemGroupType.MATERIALS, () -> DEPLETED_DUAL_URANIUM_FUEL_ROD);
		addToCreativeTab(Ic2rItemGroupType.MATERIALS, () -> DEPLETED_MOX_FUEL_ROD);
		addToCreativeTab(Ic2rItemGroupType.MATERIALS, () -> DEPLETED_QUAD_MOX_FUEL_ROD);
		addToCreativeTab(Ic2rItemGroupType.MATERIALS, () -> DEPLETED_QUAD_URANIUM_FUEL_ROD);
		addToCreativeTab(Ic2rItemGroupType.MATERIALS, () -> DEPLETED_URANIUM_FUEL_ROD);
		addToCreativeTab(Ic2rItemGroupType.MATERIALS, () -> DIAMOND_CUTTING_BLADE);
		addToCreativeTab(Ic2rItemGroupType.MATERIALS, () -> DIAMOND_DUST);
		addToCreativeTab(Ic2rItemGroupType.MATERIALS, () -> ELECTRIC_MOTOR);
		addToCreativeTab(Ic2rItemGroupType.MATERIALS, () -> ENERGIUM_DUST);
		addToCreativeTab(Ic2rItemGroupType.MATERIALS, () -> FUEL_ROD);
		addToCreativeTab(Ic2rItemGroupType.MATERIALS, () -> GOLD_CASING);
		addToCreativeTab(Ic2rItemGroupType.MATERIALS, () -> GOLD_DUST);
		addToCreativeTab(Ic2rItemGroupType.MATERIALS, () -> GOLD_PLATE);
		addToCreativeTab(Ic2rItemGroupType.MATERIALS, () -> HEAT_CONDUCTOR);
		addToCreativeTab(Ic2rItemGroupType.MATERIALS, () -> HYDRATED_TIN_DUST);
		addToCreativeTab(Ic2rItemGroupType.MATERIALS, () -> INDUTRIAL_DIAMOND);
		addToCreativeTab(Ic2rItemGroupType.MATERIALS, () -> IODINE);
		addToCreativeTab(Ic2rItemGroupType.MATERIALS, () -> IRIDIUM);
		addToCreativeTab(Ic2rItemGroupType.MATERIALS, () -> IRIDIUM_ORE);
		addToCreativeTab(Ic2rItemGroupType.MATERIALS, () -> IRIDIUM_SHARD);
		addToCreativeTab(Ic2rItemGroupType.MATERIALS, () -> IRON_CASING);
		addToCreativeTab(Ic2rItemGroupType.MATERIALS, () -> IRON_CUTTING_BLADE);
		addToCreativeTab(Ic2rItemGroupType.MATERIALS, () -> IRON_DUST);
		addToCreativeTab(Ic2rItemGroupType.MATERIALS, () -> IRON_PLATE);
		addToCreativeTab(Ic2rItemGroupType.MATERIALS, () -> IRON_ROTOR_BLADE);
		addToCreativeTab(Ic2rItemGroupType.MATERIALS, () -> IRON_SHAFT);
		addToCreativeTab(Ic2rItemGroupType.MATERIALS, () -> JETPACK_ATTACHMENT_PLATE);
		addToCreativeTab(Ic2rItemGroupType.MATERIALS, () -> LAPIS_DUST);
		addToCreativeTab(Ic2rItemGroupType.MATERIALS, () -> LAPIS_PLATE);
		addToCreativeTab(Ic2rItemGroupType.MATERIALS, () -> LAVA_SHEET);
		addToCreativeTab(Ic2rItemGroupType.MATERIALS, () -> LEAD_CASING);
		addToCreativeTab(Ic2rItemGroupType.MATERIALS, () -> LEAD_DUST);
		addToCreativeTab(Ic2rItemGroupType.MATERIALS, () -> LEAD_INGOT);
		addToCreativeTab(Ic2rItemGroupType.MATERIALS, () -> LEAD_PLATE);
		addToCreativeTab(Ic2rItemGroupType.MATERIALS, () -> LITHIUM_DUST);
		addToCreativeTab(Ic2rItemGroupType.MATERIALS, () -> MIXED_METAL_INGOT);
		addToCreativeTab(Ic2rItemGroupType.MATERIALS, () -> MOX);
		addToCreativeTab(Ic2rItemGroupType.MATERIALS, () -> NEAR_DEPLETED_URANIUM);
		addToCreativeTab(Ic2rItemGroupType.MATERIALS, () -> NETHERRACK_DUST);
		addToCreativeTab(Ic2rItemGroupType.MATERIALS, () -> OBSIDIAN_DUST);
		addToCreativeTab(Ic2rItemGroupType.MATERIALS, () -> OBSIDIAN_PLATE);
		addToCreativeTab(Ic2rItemGroupType.MATERIALS, () -> PELLET);
		addToCreativeTab(Ic2rItemGroupType.MATERIALS, () -> PLANT_BALL);
		addToCreativeTab(Ic2rItemGroupType.MATERIALS, () -> PLUTONIUM);
		addToCreativeTab(Ic2rItemGroupType.MATERIALS, () -> POWER_UNIT);
		addToCreativeTab(Ic2rItemGroupType.MATERIALS, () -> PURIFIED_COPPER);
		addToCreativeTab(Ic2rItemGroupType.MATERIALS, () -> PURIFIED_GOLD);
		addToCreativeTab(Ic2rItemGroupType.MATERIALS, () -> PURIFIED_IRON);
		addToCreativeTab(Ic2rItemGroupType.MATERIALS, () -> PURIFIED_LEAD);
		addToCreativeTab(Ic2rItemGroupType.MATERIALS, () -> PURIFIED_SILVER);
		addToCreativeTab(Ic2rItemGroupType.MATERIALS, () -> PURIFIED_TIN);
		addToCreativeTab(Ic2rItemGroupType.MATERIALS, () -> PURIFIED_URANIUM);
		addToCreativeTab(Ic2rItemGroupType.MATERIALS, () -> RAW_CRYSTAL_MEMORY);
		addToCreativeTab(Ic2rItemGroupType.MATERIALS, () -> RAW_LEAD);
		addToCreativeTab(Ic2rItemGroupType.MATERIALS, () -> RAW_TIN);
		addToCreativeTab(Ic2rItemGroupType.MATERIALS, () -> RAW_URANIUM);
		addToCreativeTab(Ic2rItemGroupType.MATERIALS, () -> RESIN);
		addToCreativeTab(Ic2rItemGroupType.MATERIALS, () -> REFRACTORY_BRICKS);
		addToCreativeTab(Ic2rItemGroupType.MATERIALS, () -> RE_ENRICHED_URANIUM);
		addToCreativeTab(Ic2rItemGroupType.MATERIALS, () -> RTG_PELLET);
		addToCreativeTab(Ic2rItemGroupType.MATERIALS, () -> RUBBER);
		addToCreativeTab(Ic2rItemGroupType.MATERIALS, () -> SCRAP);
		addToCreativeTab(Ic2rItemGroupType.MATERIALS, () -> SCRAP_BOX);
		addToCreativeTab(Ic2rItemGroupType.MATERIALS, () -> SILICON_DIOXIDE_DUST);
		addToCreativeTab(Ic2rItemGroupType.MATERIALS, () -> SILVER_DUST);
		addToCreativeTab(Ic2rItemGroupType.MATERIALS, () -> SILVER_INGOT);
		addToCreativeTab(Ic2rItemGroupType.MATERIALS, () -> SLAG);
		addToCreativeTab(Ic2rItemGroupType.MATERIALS, () -> SMALL_BRONZE_DUST);
		addToCreativeTab(Ic2rItemGroupType.MATERIALS, () -> SMALL_COPPER_DUST);
		addToCreativeTab(Ic2rItemGroupType.MATERIALS, () -> SMALL_GOLD_DUST);
		addToCreativeTab(Ic2rItemGroupType.MATERIALS, () -> SMALL_IRON_DUST);
		addToCreativeTab(Ic2rItemGroupType.MATERIALS, () -> SMALL_LAPIS_DUST);
		addToCreativeTab(Ic2rItemGroupType.MATERIALS, () -> SMALL_LEAD_DUST);
		addToCreativeTab(Ic2rItemGroupType.MATERIALS, () -> SMALL_LITHIUM_DUST);
		addToCreativeTab(Ic2rItemGroupType.MATERIALS, () -> SMALL_OBSIDIAN_DUST);
		addToCreativeTab(Ic2rItemGroupType.MATERIALS, () -> SMALL_PLUTONIUM);
		addToCreativeTab(Ic2rItemGroupType.MATERIALS, () -> SMALL_POWER_UNIT);
		addToCreativeTab(Ic2rItemGroupType.MATERIALS, () -> SMALL_SILVER_DUST);
		addToCreativeTab(Ic2rItemGroupType.MATERIALS, () -> SMALL_DIAMOND_DUST);
		addToCreativeTab(Ic2rItemGroupType.MATERIALS, () -> ENDER_PEARL_DUST);
		addToCreativeTab(Ic2rItemGroupType.MATERIALS, () -> SMALL_SULFUR_DUST);
		addToCreativeTab(Ic2rItemGroupType.MATERIALS, () -> SMALL_TIN_DUST);
		addToCreativeTab(Ic2rItemGroupType.MATERIALS, () -> SMALL_URANIUM_235);
		addToCreativeTab(Ic2rItemGroupType.MATERIALS, () -> SMALL_URANIUM_238);
		addToCreativeTab(Ic2rItemGroupType.MATERIALS, () -> STEAM_TURBINE);
		addToCreativeTab(Ic2rItemGroupType.MATERIALS, () -> STEAM_TURBINE_BLADE);
		addToCreativeTab(Ic2rItemGroupType.MATERIALS, () -> STEEL_CASING);
		addToCreativeTab(Ic2rItemGroupType.MATERIALS, () -> STEEL_CUTTING_BLADE);
		addToCreativeTab(Ic2rItemGroupType.MATERIALS, () -> STEEL_INGOT);
		addToCreativeTab(Ic2rItemGroupType.MATERIALS, () -> STEEL_PLATE);
		addToCreativeTab(Ic2rItemGroupType.MATERIALS, () -> STEEL_ROTOR_BLADE);
		addToCreativeTab(Ic2rItemGroupType.MATERIALS, () -> STEEL_SHAFT);
		addToCreativeTab(Ic2rItemGroupType.MATERIALS, () -> STONE_DUST);
		addToCreativeTab(Ic2rItemGroupType.MATERIALS, () -> SULFUR_DUST);
		addToCreativeTab(Ic2rItemGroupType.MATERIALS, () -> TIN_CAN);
		addToCreativeTab(Ic2rItemGroupType.MATERIALS, () -> TIN_CASING);
		addToCreativeTab(Ic2rItemGroupType.MATERIALS, () -> TIN_DUST);
		addToCreativeTab(Ic2rItemGroupType.MATERIALS, () -> TIN_INGOT);
		addToCreativeTab(Ic2rItemGroupType.MATERIALS, () -> TIN_PLATE);
		addToCreativeTab(Ic2rItemGroupType.MATERIALS, () -> URANIUM);
		addToCreativeTab(Ic2rItemGroupType.MATERIALS, () -> URANIUM_235);
		addToCreativeTab(Ic2rItemGroupType.MATERIALS, () -> URANIUM_238);
		addToCreativeTab(Ic2rItemGroupType.MATERIALS, () -> URANIUM_INGOT);
		addToCreativeTab(Ic2rItemGroupType.MATERIALS, () -> URANIUM_PELLET);
		addToCreativeTab(Ic2rItemGroupType.MATERIALS, () -> WATER_SHEET);
		addToCreativeTab(Ic2rItemGroupType.MATERIALS, () -> WOODEN_ROTOR_BLADE);
		addToCreativeTab(Ic2rItemGroupType.REACTOR, () -> ADVANCED_HEAT_EXCHANGER);
		addToCreativeTab(Ic2rItemGroupType.REACTOR, () -> ADVANCED_HEAT_VENT);
		addToCreativeTab(Ic2rItemGroupType.REACTOR, () -> COMPONENT_HEAT_EXCHANGER);
		addToCreativeTab(Ic2rItemGroupType.REACTOR, () -> COMPONENT_HEAT_VENT);
		addToCreativeTab(Ic2rItemGroupType.REACTOR, () -> CONTAINMENT_REACTOR_PLATING);
		addToCreativeTab(Ic2rItemGroupType.REACTOR, () -> DEPLETED_ISOTOPE_FUEL_ROD);
		addToCreativeTab(Ic2rItemGroupType.REACTOR, () -> DUAL_MOX_FUEL_ROD);
		addToCreativeTab(Ic2rItemGroupType.REACTOR, () -> DUAL_URANIUM_FUEL_ROD);
		addToCreativeTab(Ic2rItemGroupType.REACTOR, () -> HEATPACK);
		addToCreativeTab(Ic2rItemGroupType.REACTOR, () -> HEAT_EXCHANGER);
		addToCreativeTab(Ic2rItemGroupType.REACTOR, () -> HEAT_VENT);
		addToCreativeTab(Ic2rItemGroupType.REACTOR, () -> IRIDIUM_NEUTRON_REFLECTOR);
		addToCreativeTab(Ic2rItemGroupType.REACTOR, () -> LITHIUM_FUEL_ROD);
		addToCreativeTab(Ic2rItemGroupType.REACTOR, () -> LZH_CONDENSATOR);
		addToCreativeTab(Ic2rItemGroupType.REACTOR, () -> MOX_FUEL_ROD);
		addToCreativeTab(Ic2rItemGroupType.REACTOR, () -> NEUTRON_REFLECTOR);
		addToCreativeTab(Ic2rItemGroupType.REACTOR, () -> NUCLEAR_REACTOR);
		addToCreativeTab(Ic2rItemGroupType.REACTOR, () -> OVERCLOCKED_HEAT_VENT);
		addToCreativeTab(Ic2rItemGroupType.REACTOR, () -> QUAD_MOX_FUEL_ROD);
		addToCreativeTab(Ic2rItemGroupType.REACTOR, () -> QUAD_URANIUM_FUEL_ROD);
		addToCreativeTab(Ic2rItemGroupType.REACTOR, () -> RCI_LZH);
		addToCreativeTab(Ic2rItemGroupType.REACTOR, () -> RCI_RSH);
		addToCreativeTab(Ic2rItemGroupType.REACTOR, () -> REACTOR_ACCESS_HATCH);
		addToCreativeTab(Ic2rItemGroupType.REACTOR, () -> REACTOR_CHAMBER);
		addToCreativeTab(Ic2rItemGroupType.REACTOR, () -> REACTOR_COOLANT_CELL);
		addToCreativeTab(Ic2rItemGroupType.REACTOR, () -> REACTOR_FLUID_PORT);
		addToCreativeTab(Ic2rItemGroupType.REACTOR, () -> REACTOR_HEAT_EXCHANGER);
		addToCreativeTab(Ic2rItemGroupType.REACTOR, () -> REACTOR_HEAT_PLATING);
		addToCreativeTab(Ic2rItemGroupType.REACTOR, () -> REACTOR_HEAT_VENT);
		addToCreativeTab(Ic2rItemGroupType.REACTOR, () -> REACTOR_PLATING);
		addToCreativeTab(Ic2rItemGroupType.REACTOR, () -> REACTOR_REDSTONE_PORT);
		addToCreativeTab(Ic2rItemGroupType.REACTOR, () -> REACTOR_VESSEL);
		addToCreativeTab(Ic2rItemGroupType.REACTOR, () -> RSH_CONDENSATOR);
		addToCreativeTab(Ic2rItemGroupType.REACTOR, () -> SEXTUPLE_REACTOR_COOLANT_CELL);
		addToCreativeTab(Ic2rItemGroupType.REACTOR, () -> THICK_NEUTRON_REFLECTOR);
		addToCreativeTab(Ic2rItemGroupType.REACTOR, () -> TRIPLE_REACTOR_COOLANT_CELL);
		addToCreativeTab(Ic2rItemGroupType.REACTOR, () -> URANIUM_FUEL_ROD);
		addToCreativeTab(Ic2rItemGroupType.TOOLS_AND_UTILITIES, () -> ADVANCED_EJECTOR_UPGRADE);
		addToCreativeTab(Ic2rItemGroupType.TOOLS_AND_UTILITIES, () -> ADVANCED_PULLING_UPGRADE);
		addToCreativeTab(Ic2rItemGroupType.TOOLS_AND_UTILITIES, () -> ADVANCED_RE_BATTERY);
		addToCreativeTab(Ic2rItemGroupType.TOOLS_AND_UTILITIES, () -> ADVANCED_SCANNER);
		addToCreativeTab(Ic2rItemGroupType.TOOLS_AND_UTILITIES, () -> BLACK_PAINTER);
		addToCreativeTab(Ic2rItemGroupType.TOOLS_AND_UTILITIES, () -> BLANK_TFBP);
		addToCreativeTab(Ic2rItemGroupType.TOOLS_AND_UTILITIES, () -> BLUE_PAINTER);
		addToCreativeTab(Ic2rItemGroupType.TOOLS_AND_UTILITIES, () -> BROKEN_RUBBER_BOAT);
		addToCreativeTab(Ic2rItemGroupType.TOOLS_AND_UTILITIES, () -> BRONZE_AXE);
		addToCreativeTab(Ic2rItemGroupType.TOOLS_AND_UTILITIES, () -> BRONZE_HOE);
		addToCreativeTab(Ic2rItemGroupType.TOOLS_AND_UTILITIES, () -> BRONZE_PICKAXE);
		addToCreativeTab(Ic2rItemGroupType.TOOLS_AND_UTILITIES, () -> BRONZE_ROTOR);
		addToCreativeTab(Ic2rItemGroupType.TOOLS_AND_UTILITIES, () -> BRONZE_SHOVEL);
		addToCreativeTab(Ic2rItemGroupType.TOOLS_AND_UTILITIES, () -> BRONZE_SWORD);
		addToCreativeTab(Ic2rItemGroupType.TOOLS_AND_UTILITIES, () -> BROWN_PAINTER);
		addToCreativeTab(Ic2rItemGroupType.TOOLS_AND_UTILITIES, () -> CARBON_BOAT);
		addToCreativeTab(Ic2rItemGroupType.TOOLS_AND_UTILITIES, () -> CARBON_ROTOR);
		addToCreativeTab(Ic2rItemGroupType.TOOLS_AND_UTILITIES, () -> CHAINSAW);
		addToCreativeTab(Ic2rItemGroupType.TOOLS_AND_UTILITIES, () -> CHILLING_TFBP);
		addToCreativeTab(Ic2rItemGroupType.TOOLS_AND_UTILITIES, () -> CROWBAR);
		addToCreativeTab(Ic2rItemGroupType.TOOLS_AND_UTILITIES, () -> CULTIVATION_TFBP);
		addToCreativeTab(Ic2rItemGroupType.TOOLS_AND_UTILITIES, () -> CUTTER);
		addToCreativeTab(Ic2rItemGroupType.TOOLS_AND_UTILITIES, () -> CYAN_PAINTER);
		addToCreativeTab(Ic2rItemGroupType.TOOLS_AND_UTILITIES, () -> DESERTIFICATION_TFBP);
		addToCreativeTab(Ic2rItemGroupType.TOOLS_AND_UTILITIES, () -> DIAMOND_DRILL);
		addToCreativeTab(Ic2rItemGroupType.TOOLS_AND_UTILITIES, () -> DRILL);
		addToCreativeTab(Ic2rItemGroupType.TOOLS_AND_UTILITIES, () -> EJECTOR_UPGRADE);
		addToCreativeTab(Ic2rItemGroupType.TOOLS_AND_UTILITIES, () -> ELECTRIC_BOAT);
		addToCreativeTab(Ic2rItemGroupType.TOOLS_AND_UTILITIES, () -> ELECTRIC_TREETAP);
		addToCreativeTab(Ic2rItemGroupType.TOOLS_AND_UTILITIES, () -> ELECTRIC_WRENCH);
		addToCreativeTab(Ic2rItemGroupType.TOOLS_AND_UTILITIES, () -> ENERGY_CRYSTAL);
		addToCreativeTab(Ic2rItemGroupType.TOOLS_AND_UTILITIES, () -> ENERGY_STORAGE_UPGRADE);
		addToCreativeTab(Ic2rItemGroupType.TOOLS_AND_UTILITIES, () -> FILLED_TIN_CAN);
		addToCreativeTab(Ic2rItemGroupType.TOOLS_AND_UTILITIES, () -> FLATIFICATION_TFBP);
		addToCreativeTab(Ic2rItemGroupType.TOOLS_AND_UTILITIES, () -> FLUID_EJECTOR_UPGRADE);
		addToCreativeTab(Ic2rItemGroupType.TOOLS_AND_UTILITIES, () -> FLUID_PULLING_UPGRADE);
		addToCreativeTab(Ic2rItemGroupType.TOOLS_AND_UTILITIES, () -> FORGE_HAMMER);
		addToCreativeTab(Ic2rItemGroupType.TOOLS_AND_UTILITIES, () -> FOAM_SPRAYER);
		addToCreativeTab(Ic2rItemGroupType.TOOLS_AND_UTILITIES, () -> FREQUENCY_TRANSMITTER);
		addToCreativeTab(Ic2rItemGroupType.TOOLS_AND_UTILITIES, () -> GRAY_PAINTER);
		addToCreativeTab(Ic2rItemGroupType.TOOLS_AND_UTILITIES, () -> GREEN_PAINTER);
		addToCreativeTab(Ic2rItemGroupType.TOOLS_AND_UTILITIES, () -> IRIDIUM_DRILL);
		addToCreativeTab(Ic2rItemGroupType.TOOLS_AND_UTILITIES, () -> IRON_ROTOR);
		addToCreativeTab(Ic2rItemGroupType.TOOLS_AND_UTILITIES, () -> IRRIGATION_TFBP);
		addToCreativeTab(Ic2rItemGroupType.TOOLS_AND_UTILITIES, () -> LAPOTRON_CRYSTAL);
		addToCreativeTab(Ic2rItemGroupType.TOOLS_AND_UTILITIES, () -> LIGHT_BLUE_PAINTER);
		addToCreativeTab(Ic2rItemGroupType.TOOLS_AND_UTILITIES, () -> LIGHT_GRAY_PAINTER);
		addToCreativeTab(Ic2rItemGroupType.TOOLS_AND_UTILITIES, () -> LIME_PAINTER);
		addToCreativeTab(Ic2rItemGroupType.TOOLS_AND_UTILITIES, () -> MAGENTA_PAINTER);
		addToCreativeTab(Ic2rItemGroupType.TOOLS_AND_UTILITIES, () -> METER);
		addToCreativeTab(Ic2rItemGroupType.TOOLS_AND_UTILITIES, () -> MINING_FILTER_CARD);
		addToCreativeTab(Ic2rItemGroupType.TOOLS_AND_UTILITIES, () -> MINING_LASER);
		addToCreativeTab(Ic2rItemGroupType.TOOLS_AND_UTILITIES, () -> MINING_PIPE);
		addToCreativeTab(Ic2rItemGroupType.TOOLS_AND_UTILITIES, () -> MUSHROOM_TFBP);
		addToCreativeTab(Ic2rItemGroupType.TOOLS_AND_UTILITIES, () -> OBSCURATOR);
		addToCreativeTab(Ic2rItemGroupType.TOOLS_AND_UTILITIES, () -> ORANGE_PAINTER);
		addToCreativeTab(Ic2rItemGroupType.TOOLS_AND_UTILITIES, () -> OVERCLOCKER_UPGRADE);
		addToCreativeTab(Ic2rItemGroupType.TOOLS_AND_UTILITIES, () -> PAINTER);
		addToCreativeTab(Ic2rItemGroupType.TOOLS_AND_UTILITIES, () -> PINK_PAINTER);
		addToCreativeTab(Ic2rItemGroupType.TOOLS_AND_UTILITIES, () -> PULLING_UPGRADE);
		addToCreativeTab(Ic2rItemGroupType.TOOLS_AND_UTILITIES, () -> PURPLE_PAINTER);
		addToCreativeTab(Ic2rItemGroupType.TOOLS_AND_UTILITIES, () -> REDSTONE_INVERTER_UPGRADE);
		addToCreativeTab(Ic2rItemGroupType.TOOLS_AND_UTILITIES, () -> RED_PAINTER);
		addToCreativeTab(Ic2rItemGroupType.TOOLS_AND_UTILITIES, () -> REMOTE_INTERFACE_UPGRADE);
		addToCreativeTab(Ic2rItemGroupType.TOOLS_AND_UTILITIES, () -> RE_BATTERY);
		addToCreativeTab(Ic2rItemGroupType.TOOLS_AND_UTILITIES, () -> RUBBER_BOAT);
		addToCreativeTab(Ic2rItemGroupType.TOOLS_AND_UTILITIES, () -> SCANNER);
		addToCreativeTab(Ic2rItemGroupType.TOOLS_AND_UTILITIES, () -> CROPNALYZER);
		addToCreativeTab(Ic2rItemGroupType.TOOLS_AND_UTILITIES, () -> SINGLE_USE_BATTERY);
		addToCreativeTab(Ic2rItemGroupType.TOOLS_AND_UTILITIES, () -> CHARGING_RE_BATTERY);
		addToCreativeTab(Ic2rItemGroupType.TOOLS_AND_UTILITIES, () -> ADVANCED_CHARGING_RE_BATTERY);
		addToCreativeTab(Ic2rItemGroupType.TOOLS_AND_UTILITIES, () -> CHARGING_ENERGY_CRYSTAL);
		addToCreativeTab(Ic2rItemGroupType.TOOLS_AND_UTILITIES, () -> CHARGING_LAPOTRON_CRYSTAL);
		addToCreativeTab(Ic2rItemGroupType.TOOLS_AND_UTILITIES, () -> STEEL_ROTOR);
		addToCreativeTab(Ic2rItemGroupType.TOOLS_AND_UTILITIES, () -> TOOL_BOX);
		addToCreativeTab(Ic2rItemGroupType.TOOLS_AND_UTILITIES, () -> CONTAINMENT_BOX);
		addToCreativeTab(Ic2rItemGroupType.TOOLS_AND_UTILITIES, () -> TRANSFORMER_UPGRADE);
		addToCreativeTab(Ic2rItemGroupType.TOOLS_AND_UTILITIES, () -> TREETAP);
		addToCreativeTab(Ic2rItemGroupType.TOOLS_AND_UTILITIES, () -> WHITE_PAINTER);
		addToCreativeTab(Ic2rItemGroupType.TOOLS_AND_UTILITIES, () -> WIND_METER);
		addToCreativeTab(Ic2rItemGroupType.TOOLS_AND_UTILITIES, () -> WOODEN_ROTOR);
		addToCreativeTab(Ic2rItemGroupType.TOOLS_AND_UTILITIES, () -> WRENCH);
		addToCreativeTab(Ic2rItemGroupType.TOOLS_AND_UTILITIES, () -> YELLOW_PAINTER);
	}

	public static void addToCreativeTab(Ic2rItemGroupType type, Supplier<Item> itemSupplier)
	{
		CREATIVE_TAB_ITEMS.get(type).add(itemSupplier);
	}

	public static void init()
	{
		IC2R.envProxy.registerBurnTime(Items.SUGAR_CANE, 50);
		IC2R.envProxy.registerBurnTime(Items.CACTUS, 50);
		IC2R.envProxy.registerBurnTime(RUBBER_SAPLING, 80);
		IC2R.envProxy.registerBurnTime(WOODEN_STORAGE_BOX, 1200);
		IC2R.envProxy.registerBurnTime(WOODEN_ROTOR_BLADE, 300);
		IC2R.envProxy.registerBurnTime(WOODEN_ROTOR, 300);
		IC2R.envProxy.registerBurnTime(SCRAP, 350);
		IC2R.envProxy.registerBurnTime(SCRAP_BOX, 3150);
		BehaviorDynamiteDispense.register(DYNAMITE, DYNAMITE_STICKY);
	}

	public static <T extends Item> T register(String name, T item)
	{
		IC2R.envProxy.registerItem(IC2R.getIdentifier(name), item);
		return item;
	}
}
