package me.halfcooler.ic2r.core.ref.blocks;

import me.halfcooler.ic2r.core.ref.Ic2rBlocks;

import me.halfcooler.ic2r.core.IC2R;
import me.halfcooler.ic2r.core.block.generator.tileentity.TileEntityCreativeGenerator;
import me.halfcooler.ic2r.core.block.generator.tileentity.TileEntityGenerator;
import me.halfcooler.ic2r.core.block.generator.tileentity.TileEntityGeoGenerator;
import me.halfcooler.ic2r.core.block.generator.tileentity.TileEntityKineticGenerator;
import me.halfcooler.ic2r.core.block.generator.tileentity.TileEntityRTGenerator;
import me.halfcooler.ic2r.core.block.generator.tileentity.TileEntitySemifluidGenerator;
import me.halfcooler.ic2r.core.block.generator.tileentity.TileEntitySolarGenerator;
import me.halfcooler.ic2r.core.block.generator.tileentity.TileEntityStirlingGenerator;
import me.halfcooler.ic2r.core.block.generator.tileentity.TileEntityWaterGenerator;
import me.halfcooler.ic2r.core.block.generator.tileentity.TileEntityWindGenerator;
import me.halfcooler.ic2r.core.block.heatgenerator.tileentity.TileEntityElectricHeatGenerator;
import me.halfcooler.ic2r.core.block.steam.BlockRefractoryBricks;
import me.halfcooler.ic2r.core.block.steam.TileEntityCokeKiln;
import me.halfcooler.ic2r.core.block.steam.TileEntityCokeKilnGrate;
import me.halfcooler.ic2r.core.block.steam.TileEntityCokeKilnHatch;
import me.halfcooler.ic2r.core.block.heatgenerator.tileentity.TileEntityFluidHeatGenerator;
import me.halfcooler.ic2r.core.block.heatgenerator.tileentity.TileEntityRTHeatGenerator;
import me.halfcooler.ic2r.core.block.heatgenerator.tileentity.TileEntitySolidHeatGenerator;
import me.halfcooler.ic2r.core.block.inherit.Ic2rFenceBlock;
import me.halfcooler.ic2r.core.block.inherit.Ic2rGlassBlock;
import me.halfcooler.ic2r.core.block.inherit.Ic2rSheetBlock;
import me.halfcooler.ic2r.core.block.inherit.Ic2rSignBlock;
import me.halfcooler.ic2r.core.block.inherit.Ic2rWallSignBlock;
import me.halfcooler.ic2r.core.block.kineticgenerator.tileentity.TileEntityElectricKineticGenerator;
import me.halfcooler.ic2r.core.block.kineticgenerator.tileentity.TileEntityManualKineticGenerator;
import me.halfcooler.ic2r.core.block.kineticgenerator.tileentity.TileEntitySteamKineticGenerator;
import me.halfcooler.ic2r.core.block.kineticgenerator.tileentity.TileEntityStirlingKineticGenerator;
import me.halfcooler.ic2r.core.block.kineticgenerator.tileentity.TileEntityWaterKineticGenerator;
import me.halfcooler.ic2r.core.block.kineticgenerator.tileentity.TileEntityWindKineticGenerator;
import me.halfcooler.ic2r.core.block.BlockDynamite;
import me.halfcooler.ic2r.core.block.machine.MiningPipeBlock;
import me.halfcooler.ic2r.core.block.machine.tileentity.TileEntityAdvMiner;
import me.halfcooler.ic2r.core.block.machine.tileentity.TileEntityBatchCrafter;
import me.halfcooler.ic2r.core.block.machine.tileentity.TileEntityBlastFurnace;
import me.halfcooler.ic2r.core.block.machine.tileentity.TileEntityBlockCutter;
import me.halfcooler.ic2r.core.block.machine.tileentity.TileEntityCanner;
import me.halfcooler.ic2r.core.block.machine.tileentity.TileEntityCentrifuge;
import me.halfcooler.ic2r.core.block.machine.tileentity.TileEntityChunkLoader;
import me.halfcooler.ic2r.core.block.machine.tileentity.TileEntityCompressor;
import me.halfcooler.ic2r.core.block.machine.tileentity.TileEntityCondenser;
import me.halfcooler.ic2r.core.block.machine.tileentity.TileEntityCropHarvester;
import me.halfcooler.ic2r.core.block.machine.tileentity.TileEntityCropmatron;
import me.halfcooler.ic2r.core.block.machine.tileentity.TileEntityElectricFurnace;
import me.halfcooler.ic2r.core.block.machine.tileentity.TileEntityElectrolyzer;
import me.halfcooler.ic2r.core.block.machine.tileentity.TileEntityExtractor;
import me.halfcooler.ic2r.core.block.machine.tileentity.TileEntityFermenter;
import me.halfcooler.ic2r.core.block.machine.tileentity.TileEntityFluidBottler;
import me.halfcooler.ic2r.core.block.machine.tileentity.TileEntityFluidDistributor;
import me.halfcooler.ic2r.core.block.machine.tileentity.TileEntityFluidRegulator;
import me.halfcooler.ic2r.core.block.machine.tileentity.TileEntityITnt;
import me.halfcooler.ic2r.core.block.machine.tileentity.TileEntityInduction;
import me.halfcooler.ic2r.core.block.machine.tileentity.TileEntityIndustrialWorkbench;
import me.halfcooler.ic2r.core.block.machine.tileentity.TileEntityIronFurnace;
import me.halfcooler.ic2r.core.block.machine.tileentity.TileEntityItemBuffer;
import me.halfcooler.ic2r.core.block.machine.tileentity.TileEntityLiquidHeatExchanger;
import me.halfcooler.ic2r.core.block.machine.tileentity.TileEntityMacerator;
import me.halfcooler.ic2r.core.block.machine.tileentity.TileEntityMagnetizer;
import me.halfcooler.ic2r.core.block.machine.tileentity.TileEntityMatter;
import me.halfcooler.ic2r.core.block.machine.tileentity.TileEntityMetalFormer;
import me.halfcooler.ic2r.core.block.machine.tileentity.TileEntityMiner;
import me.halfcooler.ic2r.core.block.machine.tileentity.TileEntityNuke;
import me.halfcooler.ic2r.core.block.machine.tileentity.TileEntityOreWashing;
import me.halfcooler.ic2r.core.block.machine.tileentity.TileEntityPatternStorage;
import me.halfcooler.ic2r.core.block.machine.tileentity.TileEntityPump;
import me.halfcooler.ic2r.core.block.machine.tileentity.TileEntityRecycler;
import me.halfcooler.ic2r.core.block.machine.tileentity.TileEntityReplicator;
import me.halfcooler.ic2r.core.block.machine.tileentity.TileEntityScanner;
import me.halfcooler.ic2r.core.block.machine.tileentity.TileEntitySolarDistiller;
import me.halfcooler.ic2r.core.block.machine.tileentity.TileEntitySolidCanner;
import me.halfcooler.ic2r.core.block.machine.tileentity.TileEntitySortingMachine;
import me.halfcooler.ic2r.core.block.machine.tileentity.TileEntitySteamGenerator;
import me.halfcooler.ic2r.core.block.machine.tileentity.TileEntitySteamRepressurizer;
import me.halfcooler.ic2r.core.block.machine.tileentity.TileEntityTank;
import me.halfcooler.ic2r.core.block.machine.tileentity.TileEntityTeleporter;
import me.halfcooler.ic2r.core.block.machine.tileentity.TileEntityTerra;
import me.halfcooler.ic2r.core.block.machine.tileentity.TileEntityTesla;
import me.halfcooler.ic2r.core.block.machine.tileentity.TileEntityWeightedFluidDistributor;
import me.halfcooler.ic2r.core.block.machine.tileentity.TileEntityWeightedItemDistributor;
import me.halfcooler.ic2r.core.block.misc.FoamBlock;
import me.halfcooler.ic2r.core.block.misc.RubberLogBlock;
import me.halfcooler.ic2r.core.block.misc.RubberWoodBlock;
import me.halfcooler.ic2r.core.block.misc.WallBlock;
import me.halfcooler.ic2r.core.block.personal.TileEntityEnergyOMat;
import me.halfcooler.ic2r.core.block.personal.TileEntityPersonalChest;
import me.halfcooler.ic2r.core.block.personal.TileEntityTradeOMat;
import me.halfcooler.ic2r.core.block.reactor.tileentity.TileEntityNuclearReactorElectric;
import me.halfcooler.ic2r.core.block.reactor.tileentity.TileEntityRCI_LZH;
import me.halfcooler.ic2r.core.block.reactor.tileentity.TileEntityRCI_RSH;
import me.halfcooler.ic2r.core.block.reactor.tileentity.TileEntityReactorAccessHatch;
import me.halfcooler.ic2r.core.block.reactor.tileentity.TileEntityReactorChamberElectric;
import me.halfcooler.ic2r.core.block.reactor.tileentity.TileEntityReactorFluidPort;
import me.halfcooler.ic2r.core.block.reactor.tileentity.TileEntityReactorRedstonePort;
import me.halfcooler.ic2r.core.block.storage.box.TileEntityBronzeStorageBox;
import me.halfcooler.ic2r.core.block.storage.box.TileEntityIridiumStorageBox;
import me.halfcooler.ic2r.core.block.storage.box.TileEntityIronStorageBox;
import me.halfcooler.ic2r.core.block.storage.box.TileEntitySteelStorageBox;
import me.halfcooler.ic2r.core.block.storage.box.TileEntityWoodenStorageBox;
import me.halfcooler.ic2r.core.block.storage.tank.TileEntityBronzeTank;
import me.halfcooler.ic2r.core.block.storage.tank.TileEntityIridiumTank;
import me.halfcooler.ic2r.core.block.storage.tank.TileEntityIronTank;
import me.halfcooler.ic2r.core.block.storage.tank.TileEntitySteelTank;
import me.halfcooler.ic2r.core.block.tileentity.Ic2rTileEntityBlock;
import me.halfcooler.ic2r.core.block.tileentity.TileEntityWall;
import me.halfcooler.ic2r.core.block.wiring.CableBlock;
import me.halfcooler.ic2r.core.block.wiring.CableType;
import me.halfcooler.ic2r.core.block.wiring.DetectorCableBlock;
import me.halfcooler.ic2r.core.block.wiring.DetectorFoamCableBlock;
import me.halfcooler.ic2r.core.block.wiring.FoamCableBlock;
import me.halfcooler.ic2r.core.block.wiring.SplitterCableBlock;
import me.halfcooler.ic2r.core.block.wiring.SplitterFoamCableBlock;
import me.halfcooler.ic2r.core.block.wiring.tileentity.TileEntityChargePadBatBox;
import me.halfcooler.ic2r.core.block.wiring.tileentity.TileEntityLuminator;
import me.halfcooler.ic2r.core.block.wiring.tileentity.TileEntityChargePadCESU;
import me.halfcooler.ic2r.core.block.wiring.tileentity.TileEntityChargePadMFE;
import me.halfcooler.ic2r.core.block.wiring.tileentity.TileEntityChargePadMFSU;
import me.halfcooler.ic2r.core.block.wiring.tileentity.TileEntityElectricBatBox;
import me.halfcooler.ic2r.core.block.wiring.tileentity.TileEntityElectricCESU;
import me.halfcooler.ic2r.core.block.wiring.tileentity.TileEntityElectricMFE;
import me.halfcooler.ic2r.core.block.wiring.tileentity.TileEntityElectricMFSU;
import me.halfcooler.ic2r.core.block.wiring.tileentity.TileEntityTransformerEV;
import me.halfcooler.ic2r.core.block.wiring.tileentity.TileEntityTransformerHV;
import me.halfcooler.ic2r.core.block.wiring.tileentity.TileEntityTransformerLV;
import me.halfcooler.ic2r.core.block.wiring.tileentity.TileEntityTransformerMV;
import me.halfcooler.ic2r.core.crop.Ic2rCropType;
import me.halfcooler.ic2r.core.crop.TileEntityCrop;
import me.halfcooler.ic2r.core.util.Util;
import net.minecraft.core.BlockPos;

import net.minecraft.core.Direction.Axis;
import net.minecraft.util.RandomSource;
import net.minecraft.world.entity.EntityType;
import net.minecraft.world.item.DyeColor;
import net.minecraft.world.level.BlockGetter;
import net.minecraft.world.level.block.*;
import net.minecraft.world.level.block.PressurePlateBlock.Sensitivity;
import net.minecraft.world.level.block.grower.AbstractTreeGrower;
import net.minecraft.world.level.block.state.BlockState;
import net.minecraft.world.level.block.state.BlockBehaviour.Properties;
import net.minecraft.world.level.levelgen.feature.ConfiguredFeature;


import net.minecraft.world.level.material.MapColor;
import net.minecraft.core.registries.Registries;
import net.minecraft.resources.ResourceKey;
import net.minecraft.world.level.block.state.properties.BlockSetType;
import net.minecraft.world.level.block.state.properties.WoodType;
import net.minecraftforge.registries.ForgeRegistries;
import org.jetbrains.annotations.NotNull;

/** Domain block registrations: processing, fluid, logistics, personal, and utility machines */
public final class Ic2rBlocksMachines
{
	private Ic2rBlocksMachines()
	{
	}

	public static final Block CONDENSER = Ic2rBlocks.register("condenser", Ic2rTileEntityBlock.create(Properties.of().mapColor(MapColor.COLOR_LIGHT_GRAY).strength(2.0F, 10.0F).requiresCorrectToolForDrops().sound(SoundType.METAL), TileEntityCondenser.class, true, Ic2rTileEntityBlock.DefaultDrop.Machine, Util.horizontalFacings, true));
	public static final Block FLUID_BOTTLER = Ic2rBlocks.register("fluid_bottler", Ic2rTileEntityBlock.create(Properties.of().mapColor(MapColor.COLOR_LIGHT_GRAY).strength(2.0F, 10.0F).requiresCorrectToolForDrops().sound(SoundType.METAL), TileEntityFluidBottler.class, true, Ic2rTileEntityBlock.DefaultDrop.Machine, Util.horizontalFacings, true));
	public static final Block FLUID_DISTRIBUTOR = Ic2rBlocks.register("fluid_distributor", Ic2rTileEntityBlock.create(Properties.of().mapColor(MapColor.COLOR_LIGHT_GRAY).strength(2.0F, 10.0F).requiresCorrectToolForDrops().sound(SoundType.METAL), TileEntityFluidDistributor.class, true, Ic2rTileEntityBlock.DefaultDrop.Machine, Util.allFacings, true));
	public static final Block FLUID_REGULATOR = Ic2rBlocks.register("fluid_regulator", Ic2rTileEntityBlock.create(Properties.of().mapColor(MapColor.COLOR_LIGHT_GRAY).strength(2.0F, 10.0F).requiresCorrectToolForDrops().sound(SoundType.METAL), TileEntityFluidRegulator.class, true, Ic2rTileEntityBlock.DefaultDrop.Machine, Util.allFacings, true));
	public static final Block LIQUID_HEAT_EXCHANGER = Ic2rBlocks.register("liquid_heat_exchanger", Ic2rTileEntityBlock.create(Properties.of().mapColor(MapColor.COLOR_LIGHT_GRAY).strength(2.0F, 10.0F).requiresCorrectToolForDrops().sound(SoundType.METAL), TileEntityLiquidHeatExchanger.class, true, Ic2rTileEntityBlock.DefaultDrop.Machine, Util.allFacings, true));
	public static final Block PUMP = Ic2rBlocks.register("pump", Ic2rTileEntityBlock.create(Properties.of().mapColor(MapColor.COLOR_LIGHT_GRAY).strength(2.0F, 10.0F).requiresCorrectToolForDrops().sound(SoundType.METAL), TileEntityPump.class, true, Ic2rTileEntityBlock.DefaultDrop.Machine, Util.allFacings, true));
	public static final Block SOLAR_DISTILLER = Ic2rBlocks.register("solar_distiller", Ic2rTileEntityBlock.create(Properties.of().mapColor(MapColor.COLOR_LIGHT_GRAY).strength(2.0F, 10.0F).requiresCorrectToolForDrops().sound(SoundType.METAL), TileEntitySolarDistiller.class, false, Ic2rTileEntityBlock.DefaultDrop.Machine, Util.noFacings, false));
	public static final Block STEAM_GENERATOR = Ic2rBlocks.register("steam_generator", Ic2rTileEntityBlock.create(Properties.of().mapColor(MapColor.COLOR_LIGHT_GRAY).strength(2.0F, 10.0F).requiresCorrectToolForDrops().sound(SoundType.METAL), TileEntitySteamGenerator.class, true, Ic2rTileEntityBlock.DefaultDrop.Self, Util.horizontalFacings, true));
	public static final Block ITEM_BUFFER = Ic2rBlocks.register("item_buffer", Ic2rTileEntityBlock.create(Properties.of().mapColor(MapColor.COLOR_LIGHT_GRAY).strength(2.0F, 10.0F).requiresCorrectToolForDrops().sound(SoundType.METAL), TileEntityItemBuffer.class, false, Ic2rTileEntityBlock.DefaultDrop.Machine, Util.noFacings, false));
	public static final Block MAGNETIZER = Ic2rBlocks.register("magnetizer", Ic2rTileEntityBlock.create(Properties.of().mapColor(MapColor.COLOR_LIGHT_GRAY).strength(2.0F, 10.0F).requiresCorrectToolForDrops().sound(SoundType.METAL), TileEntityMagnetizer.class, false, Ic2rTileEntityBlock.DefaultDrop.Self, Util.horizontalFacings, true));
	public static final Block SORTING_MACHINE = Ic2rBlocks.register("sorting_machine", Ic2rTileEntityBlock.create(Properties.of().mapColor(MapColor.COLOR_LIGHT_GRAY).strength(2.0F, 10.0F).requiresCorrectToolForDrops().sound(SoundType.METAL), TileEntitySortingMachine.class, false, Ic2rTileEntityBlock.DefaultDrop.Machine, Util.onlyNorth, false));
	public static final Block TELEPORTER = Ic2rBlocks.register("teleporter", Ic2rTileEntityBlock.create(Properties.of().mapColor(MapColor.COLOR_LIGHT_GRAY).strength(2.0F, 10.0F).requiresCorrectToolForDrops().sound(SoundType.METAL), TileEntityTeleporter.class, true, Ic2rTileEntityBlock.DefaultDrop.AdvMachine, Util.noFacings, false));
	public static final Block TERRAFORMER = Ic2rBlocks.register("terraformer", Ic2rTileEntityBlock.create(Properties.of().mapColor(MapColor.COLOR_LIGHT_GRAY).strength(2.0F, 10.0F).requiresCorrectToolForDrops().sound(SoundType.METAL), TileEntityTerra.class, true, Ic2rTileEntityBlock.DefaultDrop.AdvMachine, Util.noFacings, false));
	public static final Block TESLA_COIL = Ic2rBlocks.register("tesla_coil", Ic2rTileEntityBlock.create(Properties.of().mapColor(MapColor.COLOR_LIGHT_GRAY).strength(2.0F, 10.0F).requiresCorrectToolForDrops().sound(SoundType.METAL), TileEntityTesla.class, false, Ic2rTileEntityBlock.DefaultDrop.Machine, Util.horizontalFacings, true));
	public static final Block CANNER = Ic2rBlocks.register("canner", Ic2rTileEntityBlock.create(Properties.of().mapColor(MapColor.COLOR_LIGHT_GRAY).strength(2.0F, 10.0F).requiresCorrectToolForDrops().sound(SoundType.METAL), TileEntityCanner.class, true, Ic2rTileEntityBlock.DefaultDrop.Machine, Util.horizontalFacings, true));
	public static final Ic2rTileEntityBlock COMPRESSOR = Ic2rBlocks.register("compressor", Ic2rTileEntityBlock.create(Properties.of().mapColor(MapColor.COLOR_LIGHT_GRAY).strength(2.0F, 10.0F).requiresCorrectToolForDrops().sound(SoundType.METAL), TileEntityCompressor.class, true, Ic2rTileEntityBlock.DefaultDrop.Machine, Util.horizontalFacings, true));
	public static final Block ELECTRIC_FURNACE = Ic2rBlocks.register("electric_furnace", Ic2rTileEntityBlock.create(Properties.of().mapColor(MapColor.COLOR_LIGHT_GRAY).strength(2.0F, 10.0F).requiresCorrectToolForDrops().sound(SoundType.METAL), TileEntityElectricFurnace.class, true, Ic2rTileEntityBlock.DefaultDrop.Self, Util.horizontalFacings, true));
	public static final Ic2rTileEntityBlock EXTRACTOR = Ic2rBlocks.register("extractor", Ic2rTileEntityBlock.create(Properties.of().mapColor(MapColor.COLOR_LIGHT_GRAY).strength(2.0F, 10.0F).requiresCorrectToolForDrops().sound(SoundType.METAL), TileEntityExtractor.class, true, Ic2rTileEntityBlock.DefaultDrop.Machine, Util.horizontalFacings, true));
	public static final Block IRON_FURNACE = Ic2rBlocks.register("iron_furnace", Ic2rTileEntityBlock.create(Properties.of().strength(5.0F, 10.0F).requiresCorrectToolForDrops().sound(SoundType.METAL), TileEntityIronFurnace.class, true, Ic2rTileEntityBlock.DefaultDrop.Self, Util.horizontalFacings, false));
	public static final Ic2rTileEntityBlock MACERATOR = Ic2rBlocks.register("macerator", Ic2rTileEntityBlock.create(Properties.of().mapColor(MapColor.COLOR_LIGHT_GRAY).strength(2.0F, 10.0F).requiresCorrectToolForDrops().sound(SoundType.METAL), TileEntityMacerator.class, true, Ic2rTileEntityBlock.DefaultDrop.Machine, Util.horizontalFacings, true));
	public static final Block RECYCLER = Ic2rBlocks.register("recycler", Ic2rTileEntityBlock.create(Properties.of().mapColor(MapColor.COLOR_LIGHT_GRAY).strength(2.0F, 10.0F).requiresCorrectToolForDrops().sound(SoundType.METAL), TileEntityRecycler.class, true, Ic2rTileEntityBlock.DefaultDrop.Machine, Util.horizontalFacings, true));
	public static final Block SOLID_CANNER = Ic2rBlocks.register("solid_canner", Ic2rTileEntityBlock.create(Properties.of().mapColor(MapColor.COLOR_LIGHT_GRAY).strength(2.0F, 10.0F).requiresCorrectToolForDrops().sound(SoundType.METAL), TileEntitySolidCanner.class, true, Ic2rTileEntityBlock.DefaultDrop.Machine, Util.horizontalFacings, true));
	public static final Ic2rTileEntityBlock BLAST_FURNACE = Ic2rBlocks.register("blast_furnace", Ic2rTileEntityBlock.create(Properties.of().mapColor(MapColor.COLOR_LIGHT_GRAY).strength(2.0F, 10.0F).requiresCorrectToolForDrops().sound(SoundType.METAL), TileEntityBlastFurnace.class, true, Ic2rTileEntityBlock.DefaultDrop.Machine, Util.allFacings, true));
	public static final Ic2rTileEntityBlock BLOCK_CUTTER = Ic2rBlocks.register("block_cutter", Ic2rTileEntityBlock.create(Properties.of().mapColor(MapColor.COLOR_LIGHT_GRAY).strength(2.0F, 10.0F).requiresCorrectToolForDrops().sound(SoundType.METAL), TileEntityBlockCutter.class, true, Ic2rTileEntityBlock.DefaultDrop.AdvMachine, Util.horizontalFacings, true));
	public static final Ic2rTileEntityBlock CENTRIFUGE = Ic2rBlocks.register("centrifuge", Ic2rTileEntityBlock.create(Properties.of().mapColor(MapColor.COLOR_LIGHT_GRAY).strength(2.0F, 10.0F).requiresCorrectToolForDrops().sound(SoundType.METAL), TileEntityCentrifuge.class, true, Ic2rTileEntityBlock.DefaultDrop.Machine, Util.horizontalFacings, true));
	public static final Block FERMENTER = Ic2rBlocks.register("fermenter", Ic2rTileEntityBlock.create(Properties.of().mapColor(MapColor.COLOR_LIGHT_GRAY).strength(2.0F, 10.0F).requiresCorrectToolForDrops().sound(SoundType.METAL), TileEntityFermenter.class, true, Ic2rTileEntityBlock.DefaultDrop.Machine, Util.allFacings, true));
	public static final Block INDUCTION_FURNACE = Ic2rBlocks.register("induction_furnace", Ic2rTileEntityBlock.create(Properties.of().mapColor(MapColor.COLOR_LIGHT_GRAY).strength(2.0F, 10.0F).requiresCorrectToolForDrops().sound(SoundType.METAL), TileEntityInduction.class, true, Ic2rTileEntityBlock.DefaultDrop.AdvMachine, Util.horizontalFacings, true));
	public static final Ic2rTileEntityBlock METAL_FORMER = Ic2rBlocks.register("metal_former", Ic2rTileEntityBlock.create(Properties.of().mapColor(MapColor.COLOR_LIGHT_GRAY).strength(2.0F, 10.0F).requiresCorrectToolForDrops().sound(SoundType.METAL), TileEntityMetalFormer.class, true, Ic2rTileEntityBlock.DefaultDrop.Machine, Util.horizontalFacings, true));
	public static final Ic2rTileEntityBlock ORE_WASHING_PLANT = Ic2rBlocks.register("ore_washing_plant", Ic2rTileEntityBlock.create(Properties.of().mapColor(MapColor.COLOR_LIGHT_GRAY).strength(2.0F, 10.0F).requiresCorrectToolForDrops().sound(SoundType.METAL), TileEntityOreWashing.class, true, Ic2rTileEntityBlock.DefaultDrop.Machine, Util.horizontalFacings, true));
	public static final Block ADVANCED_MINER = Ic2rBlocks.register("advanced_miner", Ic2rTileEntityBlock.create(Properties.of().mapColor(MapColor.COLOR_LIGHT_GRAY).strength(2.0F, 10.0F).requiresCorrectToolForDrops().sound(SoundType.METAL), TileEntityAdvMiner.class, true, Ic2rTileEntityBlock.DefaultDrop.Self, Util.horizontalFacings, true));
	public static final Block CROP_HARVESTER = Ic2rBlocks.register("crop_harvester", Ic2rTileEntityBlock.create(Properties.of().mapColor(MapColor.COLOR_LIGHT_GRAY).strength(2.0F, 10.0F).requiresCorrectToolForDrops().sound(SoundType.METAL), TileEntityCropHarvester.class, false, Ic2rTileEntityBlock.DefaultDrop.Machine, Util.horizontalFacings, true));
	public static final Block CROPMATRON = Ic2rBlocks.register("cropmatron", Ic2rTileEntityBlock.create(Properties.of().mapColor(MapColor.COLOR_LIGHT_GRAY).strength(2.0F, 10.0F).requiresCorrectToolForDrops().sound(SoundType.METAL), TileEntityCropmatron.class, true, Ic2rTileEntityBlock.DefaultDrop.Machine, Util.horizontalFacings, true));
	public static final Block MINER = Ic2rBlocks.register("miner", Ic2rTileEntityBlock.create(Properties.of().mapColor(MapColor.COLOR_LIGHT_GRAY).strength(2.0F, 10.0F).requiresCorrectToolForDrops().sound(SoundType.METAL), TileEntityMiner.class, true, Ic2rTileEntityBlock.DefaultDrop.Self, Util.horizontalFacings, true));
	public static final Block MATTER_GENERATOR = Ic2rBlocks.register("matter_generator", Ic2rTileEntityBlock.create(Properties.of().mapColor(MapColor.COLOR_LIGHT_GRAY).strength(2.0F, 10.0F).requiresCorrectToolForDrops().sound(SoundType.METAL), TileEntityMatter.class, true, Ic2rTileEntityBlock.DefaultDrop.AdvMachine, Util.horizontalFacings, true));
	public static final Block PATTERN_STORAGE = Ic2rBlocks.register("pattern_storage", Ic2rTileEntityBlock.create(Properties.of().mapColor(MapColor.COLOR_LIGHT_GRAY).strength(2.0F, 10.0F).requiresCorrectToolForDrops().sound(SoundType.METAL), TileEntityPatternStorage.class, false, Ic2rTileEntityBlock.DefaultDrop.AdvMachine, Util.horizontalFacings, true));
	public static final Block REPLICATOR = Ic2rBlocks.register("replicator", Ic2rTileEntityBlock.create(Properties.of().mapColor(MapColor.COLOR_LIGHT_GRAY).strength(2.0F, 10.0F).requiresCorrectToolForDrops().sound(SoundType.METAL), TileEntityReplicator.class, true, Ic2rTileEntityBlock.DefaultDrop.AdvMachine, Util.horizontalFacings, true));
	public static final Block UU_SCANNER = Ic2rBlocks.register("uu_scanner", Ic2rTileEntityBlock.create(Properties.of().mapColor(MapColor.COLOR_LIGHT_GRAY).strength(2.0F, 10.0F).requiresCorrectToolForDrops().sound(SoundType.METAL), TileEntityScanner.class, true, Ic2rTileEntityBlock.DefaultDrop.AdvMachine, Util.horizontalFacings, true));
	public static final Block ENERGY_O_MAT = Ic2rBlocks.register("energy_o_mat", Ic2rTileEntityBlock.create(Properties.of().mapColor(MapColor.COLOR_LIGHT_GRAY).strength(-1.0F, 3600000.0F).requiresCorrectToolForDrops().sound(SoundType.METAL), TileEntityEnergyOMat.class, false, Ic2rTileEntityBlock.DefaultDrop.Self, Util.allFacings, false));
	public static final Block PERSONAL_CHEST = Ic2rBlocks.register("personal_chest", Ic2rTileEntityBlock.create(Properties.of().mapColor(MapColor.COLOR_LIGHT_GRAY).strength(-1.0F, 3600000.0F).requiresCorrectToolForDrops().sound(SoundType.METAL), TileEntityPersonalChest.class, false, Ic2rTileEntityBlock.DefaultDrop.Self, Util.horizontalFacings, false));
	public static final Block TRADE_O_MAT = Ic2rBlocks.register("trade_o_mat", Ic2rTileEntityBlock.create(Properties.of().mapColor(MapColor.COLOR_LIGHT_GRAY).strength(-1.0F, 3600000.0F).requiresCorrectToolForDrops().sound(SoundType.METAL), TileEntityTradeOMat.class, true, Ic2rTileEntityBlock.DefaultDrop.Self, Util.horizontalFacings, false));
	public static final Block ELECTROLYZER = Ic2rBlocks.register("electrolyzer", Ic2rTileEntityBlock.create(Properties.of().mapColor(MapColor.COLOR_LIGHT_GRAY).strength(2.0F, 10.0F).requiresCorrectToolForDrops().sound(SoundType.METAL), TileEntityElectrolyzer.class, true, Ic2rTileEntityBlock.DefaultDrop.Machine, Util.horizontalFacings, true));
	public static final Block TANK = Ic2rBlocks.register("tank", Ic2rTileEntityBlock.create(Properties.of().mapColor(MapColor.COLOR_LIGHT_GRAY).strength(2.0F, 10.0F).requiresCorrectToolForDrops().sound(SoundType.METAL), TileEntityTank.class, false, Ic2rTileEntityBlock.DefaultDrop.Self, Util.horizontalFacings, true));
	public static final Block CHUNK_LOADER = Ic2rBlocks.register("chunk_loader", Ic2rTileEntityBlock.create(Properties.of().mapColor(MapColor.COLOR_LIGHT_GRAY).strength(2.0F, 10.0F).requiresCorrectToolForDrops().sound(SoundType.METAL), TileEntityChunkLoader.class, true, Ic2rTileEntityBlock.DefaultDrop.Self, Util.horizontalFacings, true));
	public static final Block STEAM_REPRESSURIZER = Ic2rBlocks.register("steam_repressurizer", Ic2rTileEntityBlock.create(Properties.of().mapColor(MapColor.COLOR_LIGHT_GRAY).strength(2.0F, 10.0F).requiresCorrectToolForDrops().sound(SoundType.METAL), TileEntitySteamRepressurizer.class, true, Ic2rTileEntityBlock.DefaultDrop.Machine, Util.noFacings, true));
	public static final Block WEIGHTED_FLUID_DISTRIBUTOR = Ic2rBlocks.register("weighted_fluid_distributor", Ic2rTileEntityBlock.create(Properties.of().mapColor(MapColor.COLOR_LIGHT_GRAY).strength(2.0F, 10.0F).requiresCorrectToolForDrops().sound(SoundType.METAL), TileEntityWeightedFluidDistributor.class, false, Ic2rTileEntityBlock.DefaultDrop.Machine, Util.allFacings, true));
	public static final Block WEIGHTED_ITEM_DISTRIBUTOR = Ic2rBlocks.register("weighted_item_distributor", Ic2rTileEntityBlock.create(Properties.of().mapColor(MapColor.COLOR_LIGHT_GRAY).strength(2.0F, 10.0F).requiresCorrectToolForDrops().sound(SoundType.METAL), TileEntityWeightedItemDistributor.class, false, Ic2rTileEntityBlock.DefaultDrop.Machine, Util.allFacings, true));
	public static final Block INDUSTRIAL_WORKBENCH = Ic2rBlocks.register("industrial_workbench", Ic2rTileEntityBlock.create(Properties.of().mapColor(MapColor.COLOR_LIGHT_GRAY).strength(2.0F, 10.0F).requiresCorrectToolForDrops().sound(SoundType.METAL), TileEntityIndustrialWorkbench.class, false, Ic2rTileEntityBlock.DefaultDrop.Self, Util.horizontalFacings, true));
	public static final Block BATCH_CRAFTER = Ic2rBlocks.register("batch_crafter", Ic2rTileEntityBlock.create(Properties.of().mapColor(MapColor.COLOR_LIGHT_GRAY).strength(2.0F, 10.0F).requiresCorrectToolForDrops().sound(SoundType.METAL), TileEntityBatchCrafter.class, true, Ic2rTileEntityBlock.DefaultDrop.AdvMachine, Util.horizontalFacings, true));
	public static final Block COKE_KILN = Ic2rBlocks.register("coke_kiln", Ic2rTileEntityBlock.create(Properties.of().mapColor(MapColor.COLOR_LIGHT_GRAY).strength(2.0F, 10.0F).requiresCorrectToolForDrops().sound(SoundType.STONE), TileEntityCokeKiln.class, true, Ic2rTileEntityBlock.DefaultDrop.Self, Util.horizontalFacings, true));
	public static final Block COKE_KILN_HATCH = Ic2rBlocks.register("coke_kiln_hatch", Ic2rTileEntityBlock.create(Properties.of().mapColor(MapColor.COLOR_LIGHT_GRAY).strength(2.0F, 10.0F).requiresCorrectToolForDrops().sound(SoundType.STONE), TileEntityCokeKilnHatch.class, false, Ic2rTileEntityBlock.DefaultDrop.Self, Util.allFacings, true));
	public static final Block COKE_KILN_GRATE = Ic2rBlocks.register("coke_kiln_grate", Ic2rTileEntityBlock.create(Properties.of().mapColor(MapColor.COLOR_LIGHT_GRAY).strength(2.0F, 10.0F).requiresCorrectToolForDrops().sound(SoundType.STONE), TileEntityCokeKilnGrate.class, false, Ic2rTileEntityBlock.DefaultDrop.Self, Util.allFacings, true));
}
