package me.halfcooler.ic2r.core.ref.blocks;

import me.halfcooler.ic2r.core.ref.Ic2rBlocks;

import me.halfcooler.ic2r.core.IC2R;
import me.halfcooler.ic2r.core.block.generator.tileentity.TileEntityCreativeGenerator;
import me.halfcooler.ic2r.core.block.generator.tileentity.TileEntityGenerator;
import me.halfcooler.ic2r.core.block.generator.tileentity.TileEntityGeoGenerator;
import me.halfcooler.ic2r.core.block.generator.tileentity.TileEntityKineticGenerator;
import me.halfcooler.ic2r.core.block.generator.tileentity.TileEntityRTGenerator;
import me.halfcooler.ic2r.core.block.generator.tileentity.TileEntitySemifluidGenerator;
import me.halfcooler.ic2r.core.block.generator.tileentity.TileEntitySolarGenerator;
import me.halfcooler.ic2r.core.block.generator.tileentity.TileEntityStirlingGenerator;
import me.halfcooler.ic2r.core.block.generator.tileentity.TileEntityWaterGenerator;
import me.halfcooler.ic2r.core.block.generator.tileentity.TileEntityWindGenerator;
import me.halfcooler.ic2r.core.block.heatgenerator.tileentity.TileEntityElectricHeatGenerator;
import me.halfcooler.ic2r.core.block.steam.BlockRefractoryBricks;
import me.halfcooler.ic2r.core.block.steam.TileEntityCokeKiln;
import me.halfcooler.ic2r.core.block.steam.TileEntityCokeKilnGrate;
import me.halfcooler.ic2r.core.block.steam.TileEntityCokeKilnHatch;
import me.halfcooler.ic2r.core.block.heatgenerator.tileentity.TileEntityFluidHeatGenerator;
import me.halfcooler.ic2r.core.block.heatgenerator.tileentity.TileEntityRTHeatGenerator;
import me.halfcooler.ic2r.core.block.heatgenerator.tileentity.TileEntitySolidHeatGenerator;
import me.halfcooler.ic2r.core.block.inherit.Ic2rFenceBlock;
import me.halfcooler.ic2r.core.block.inherit.Ic2rGlassBlock;
import me.halfcooler.ic2r.core.block.inherit.Ic2rSheetBlock;
import me.halfcooler.ic2r.core.block.inherit.Ic2rSignBlock;
import me.halfcooler.ic2r.core.block.inherit.Ic2rWallSignBlock;
import me.halfcooler.ic2r.core.block.kineticgenerator.tileentity.TileEntityElectricKineticGenerator;
import me.halfcooler.ic2r.core.block.kineticgenerator.tileentity.TileEntityManualKineticGenerator;
import me.halfcooler.ic2r.core.block.kineticgenerator.tileentity.TileEntitySteamKineticGenerator;
import me.halfcooler.ic2r.core.block.kineticgenerator.tileentity.TileEntityStirlingKineticGenerator;
import me.halfcooler.ic2r.core.block.kineticgenerator.tileentity.TileEntityWaterKineticGenerator;
import me.halfcooler.ic2r.core.block.kineticgenerator.tileentity.TileEntityWindKineticGenerator;
import me.halfcooler.ic2r.core.block.BlockDynamite;
import me.halfcooler.ic2r.core.block.machine.MiningPipeBlock;
import me.halfcooler.ic2r.core.block.machine.tileentity.TileEntityAdvMiner;
import me.halfcooler.ic2r.core.block.machine.tileentity.TileEntityBatchCrafter;
import me.halfcooler.ic2r.core.block.machine.tileentity.TileEntityBlastFurnace;
import me.halfcooler.ic2r.core.block.machine.tileentity.TileEntityBlockCutter;
import me.halfcooler.ic2r.core.block.machine.tileentity.TileEntityCanner;
import me.halfcooler.ic2r.core.block.machine.tileentity.TileEntityCentrifuge;
import me.halfcooler.ic2r.core.block.machine.tileentity.TileEntityChunkLoader;
import me.halfcooler.ic2r.core.block.machine.tileentity.TileEntityCompressor;
import me.halfcooler.ic2r.core.block.machine.tileentity.TileEntityCondenser;
import me.halfcooler.ic2r.core.block.machine.tileentity.TileEntityCropHarvester;
import me.halfcooler.ic2r.core.block.machine.tileentity.TileEntityCropmatron;
import me.halfcooler.ic2r.core.block.machine.tileentity.TileEntityElectricFurnace;
import me.halfcooler.ic2r.core.block.machine.tileentity.TileEntityElectrolyzer;
import me.halfcooler.ic2r.core.block.machine.tileentity.TileEntityExtractor;
import me.halfcooler.ic2r.core.block.machine.tileentity.TileEntityFermenter;
import me.halfcooler.ic2r.core.block.machine.tileentity.TileEntityFluidBottler;
import me.halfcooler.ic2r.core.block.machine.tileentity.TileEntityFluidDistributor;
import me.halfcooler.ic2r.core.block.machine.tileentity.TileEntityFluidRegulator;
import me.halfcooler.ic2r.core.block.machine.tileentity.TileEntityITnt;
import me.halfcooler.ic2r.core.block.machine.tileentity.TileEntityInduction;
import me.halfcooler.ic2r.core.block.machine.tileentity.TileEntityIndustrialWorkbench;
import me.halfcooler.ic2r.core.block.machine.tileentity.TileEntityIronFurnace;
import me.halfcooler.ic2r.core.block.machine.tileentity.TileEntityItemBuffer;
import me.halfcooler.ic2r.core.block.machine.tileentity.TileEntityLiquidHeatExchanger;
import me.halfcooler.ic2r.core.block.machine.tileentity.TileEntityMacerator;
import me.halfcooler.ic2r.core.block.machine.tileentity.TileEntityMagnetizer;
import me.halfcooler.ic2r.core.block.machine.tileentity.TileEntityMatter;
import me.halfcooler.ic2r.core.block.machine.tileentity.TileEntityMetalFormer;
import me.halfcooler.ic2r.core.block.machine.tileentity.TileEntityMiner;
import me.halfcooler.ic2r.core.block.machine.tileentity.TileEntityNuke;
import me.halfcooler.ic2r.core.block.machine.tileentity.TileEntityOreWashing;
import me.halfcooler.ic2r.core.block.machine.tileentity.TileEntityPatternStorage;
import me.halfcooler.ic2r.core.block.machine.tileentity.TileEntityPump;
import me.halfcooler.ic2r.core.block.machine.tileentity.TileEntityRecycler;
import me.halfcooler.ic2r.core.block.machine.tileentity.TileEntityReplicator;
import me.halfcooler.ic2r.core.block.machine.tileentity.TileEntityScanner;
import me.halfcooler.ic2r.core.block.machine.tileentity.TileEntitySolarDistiller;
import me.halfcooler.ic2r.core.block.machine.tileentity.TileEntitySolidCanner;
import me.halfcooler.ic2r.core.block.machine.tileentity.TileEntitySortingMachine;
import me.halfcooler.ic2r.core.block.machine.tileentity.TileEntitySteamGenerator;
import me.halfcooler.ic2r.core.block.machine.tileentity.TileEntitySteamRepressurizer;
import me.halfcooler.ic2r.core.block.machine.tileentity.TileEntityTank;
import me.halfcooler.ic2r.core.block.machine.tileentity.TileEntityTeleporter;
import me.halfcooler.ic2r.core.block.machine.tileentity.TileEntityTerra;
import me.halfcooler.ic2r.core.block.machine.tileentity.TileEntityTesla;
import me.halfcooler.ic2r.core.block.machine.tileentity.TileEntityWeightedFluidDistributor;
import me.halfcooler.ic2r.core.block.machine.tileentity.TileEntityWeightedItemDistributor;
import me.halfcooler.ic2r.core.block.misc.FoamBlock;
import me.halfcooler.ic2r.core.block.misc.RubberLogBlock;
import me.halfcooler.ic2r.core.block.misc.RubberWoodBlock;
import me.halfcooler.ic2r.core.block.misc.WallBlock;
import me.halfcooler.ic2r.core.block.personal.TileEntityEnergyOMat;
import me.halfcooler.ic2r.core.block.personal.TileEntityPersonalChest;
import me.halfcooler.ic2r.core.block.personal.TileEntityTradeOMat;
import me.halfcooler.ic2r.core.block.reactor.tileentity.TileEntityNuclearReactorElectric;
import me.halfcooler.ic2r.core.block.reactor.tileentity.TileEntityRCI_LZH;
import me.halfcooler.ic2r.core.block.reactor.tileentity.TileEntityRCI_RSH;
import me.halfcooler.ic2r.core.block.reactor.tileentity.TileEntityReactorAccessHatch;
import me.halfcooler.ic2r.core.block.reactor.tileentity.TileEntityReactorChamberElectric;
import me.halfcooler.ic2r.core.block.reactor.tileentity.TileEntityReactorFluidPort;
import me.halfcooler.ic2r.core.block.reactor.tileentity.TileEntityReactorRedstonePort;
import me.halfcooler.ic2r.core.block.storage.box.TileEntityBronzeStorageBox;
import me.halfcooler.ic2r.core.block.storage.box.TileEntityIridiumStorageBox;
import me.halfcooler.ic2r.core.block.storage.box.TileEntityIronStorageBox;
import me.halfcooler.ic2r.core.block.storage.box.TileEntitySteelStorageBox;
import me.halfcooler.ic2r.core.block.storage.box.TileEntityWoodenStorageBox;
import me.halfcooler.ic2r.core.block.storage.tank.TileEntityBronzeTank;
import me.halfcooler.ic2r.core.block.storage.tank.TileEntityIridiumTank;
import me.halfcooler.ic2r.core.block.storage.tank.TileEntityIronTank;
import me.halfcooler.ic2r.core.block.storage.tank.TileEntitySteelTank;
import me.halfcooler.ic2r.core.block.tileentity.Ic2rTileEntityBlock;
import me.halfcooler.ic2r.core.block.tileentity.TileEntityWall;
import me.halfcooler.ic2r.core.block.wiring.CableBlock;
import me.halfcooler.ic2r.core.block.wiring.CableType;
import me.halfcooler.ic2r.core.block.wiring.DetectorCableBlock;
import me.halfcooler.ic2r.core.block.wiring.DetectorFoamCableBlock;
import me.halfcooler.ic2r.core.block.wiring.FoamCableBlock;
import me.halfcooler.ic2r.core.block.wiring.SplitterCableBlock;
import me.halfcooler.ic2r.core.block.wiring.SplitterFoamCableBlock;
import me.halfcooler.ic2r.core.block.wiring.tileentity.TileEntityChargePadBatBox;
import me.halfcooler.ic2r.core.block.wiring.tileentity.TileEntityLuminator;
import me.halfcooler.ic2r.core.block.wiring.tileentity.TileEntityChargePadCESU;
import me.halfcooler.ic2r.core.block.wiring.tileentity.TileEntityChargePadMFE;
import me.halfcooler.ic2r.core.block.wiring.tileentity.TileEntityChargePadMFSU;
import me.halfcooler.ic2r.core.block.wiring.tileentity.TileEntityElectricBatBox;
import me.halfcooler.ic2r.core.block.wiring.tileentity.TileEntityElectricCESU;
import me.halfcooler.ic2r.core.block.wiring.tileentity.TileEntityElectricMFE;
import me.halfcooler.ic2r.core.block.wiring.tileentity.TileEntityElectricMFSU;
import me.halfcooler.ic2r.core.block.wiring.tileentity.TileEntityTransformerEV;
import me.halfcooler.ic2r.core.block.wiring.tileentity.TileEntityTransformerHV;
import me.halfcooler.ic2r.core.block.wiring.tileentity.TileEntityTransformerLV;
import me.halfcooler.ic2r.core.block.wiring.tileentity.TileEntityTransformerMV;
import me.halfcooler.ic2r.core.crop.Ic2rCropType;
import me.halfcooler.ic2r.core.crop.TileEntityCrop;
import me.halfcooler.ic2r.core.util.Util;
import net.minecraft.core.BlockPos;

import net.minecraft.core.Direction.Axis;
import net.minecraft.util.RandomSource;
import net.minecraft.world.entity.EntityType;
import net.minecraft.world.item.DyeColor;
import net.minecraft.world.level.BlockGetter;
import net.minecraft.world.level.block.*;
import net.minecraft.world.level.block.PressurePlateBlock.Sensitivity;
import net.minecraft.world.level.block.grower.AbstractTreeGrower;
import net.minecraft.world.level.block.state.BlockState;
import net.minecraft.world.level.block.state.BlockBehaviour.Properties;
import net.minecraft.world.level.levelgen.feature.ConfiguredFeature;


import net.minecraft.world.level.material.MapColor;
import net.minecraft.core.registries.Registries;
import net.minecraft.resources.ResourceKey;
import net.minecraft.world.level.block.state.properties.BlockSetType;
import net.minecraft.world.level.block.state.properties.WoodType;
import net.minecraftforge.registries.ForgeRegistries;
import org.jetbrains.annotations.NotNull;

/** Domain block registrations: crop sticks and crop blocks */
public final class Ic2rBlocksCrops
{
	private Ic2rBlocksCrops()
	{
	}

	private static final Properties cropSettings = Properties.of().strength(0.8F, 0.2F).sound(SoundType.CROP).noCollission();
	public static final Block CROP_STICK = Ic2rBlocks.register("crop_stick", Ic2rTileEntityBlock.create(cropSettings, TileEntityCrop.class, false, Ic2rTileEntityBlock.DefaultDrop.Self, Util.noFacings, false, Ic2rCropType.none));
	public static final Block WEED_CROP = Ic2rBlocks.register("weed_crop", Ic2rTileEntityBlock.create(cropSettings, TileEntityCrop.class, false, Ic2rTileEntityBlock.DefaultDrop.Self, Util.noFacings, false, Ic2rCropType.weed));
	public static final Block WHEAT_CROP = Ic2rBlocks.register("wheat_crop", Ic2rTileEntityBlock.create(cropSettings, TileEntityCrop.class, false, Ic2rTileEntityBlock.DefaultDrop.Self, Util.noFacings, false, Ic2rCropType.wheat));
	public static final Block CARROTS_CROP = Ic2rBlocks.register("carrots_crop", Ic2rTileEntityBlock.create(cropSettings, TileEntityCrop.class, false, Ic2rTileEntityBlock.DefaultDrop.Self, Util.noFacings, false, Ic2rCropType.carrots));
	public static final Block POTATO_CROP = Ic2rBlocks.register("potato_crop", Ic2rTileEntityBlock.create(cropSettings, TileEntityCrop.class, false, Ic2rTileEntityBlock.DefaultDrop.Self, Util.noFacings, false, Ic2rCropType.potato));
	public static final Block BEETROOTS_CROP = Ic2rBlocks.register("beetroots_crop", Ic2rTileEntityBlock.create(cropSettings, TileEntityCrop.class, false, Ic2rTileEntityBlock.DefaultDrop.Self, Util.noFacings, false, Ic2rCropType.beetroots));
	public static final Block PUMPKIN_CROP = Ic2rBlocks.register("pumpkin_crop", Ic2rTileEntityBlock.create(cropSettings, TileEntityCrop.class, false, Ic2rTileEntityBlock.DefaultDrop.Self, Util.noFacings, false, Ic2rCropType.pumpkin));
	public static final Block MELON_CROP = Ic2rBlocks.register("melon_crop", Ic2rTileEntityBlock.create(cropSettings, TileEntityCrop.class, false, Ic2rTileEntityBlock.DefaultDrop.Self, Util.noFacings, false, Ic2rCropType.melon));
	public static final Block DANDELION_CROP = Ic2rBlocks.register("dandelion_crop", Ic2rTileEntityBlock.create(cropSettings, TileEntityCrop.class, false, Ic2rTileEntityBlock.DefaultDrop.Self, Util.noFacings, false, Ic2rCropType.dandelion));
	public static final Block POPPY_CROP = Ic2rBlocks.register("poppy_crop", Ic2rTileEntityBlock.create(cropSettings, TileEntityCrop.class, false, Ic2rTileEntityBlock.DefaultDrop.Self, Util.noFacings, false, Ic2rCropType.poppy));
	public static final Block BLACKTHORN_CROP = Ic2rBlocks.register("blackthorn_crop", Ic2rTileEntityBlock.create(cropSettings, TileEntityCrop.class, false, Ic2rTileEntityBlock.DefaultDrop.Self, Util.noFacings, false, Ic2rCropType.blackthorn));
	public static final Block TULIP_CROP = Ic2rBlocks.register("tulip_crop", Ic2rTileEntityBlock.create(cropSettings, TileEntityCrop.class, false, Ic2rTileEntityBlock.DefaultDrop.Self, Util.noFacings, false, Ic2rCropType.tulip));
	public static final Block CYAZINT_CROP = Ic2rBlocks.register("cyazint_crop", Ic2rTileEntityBlock.create(cropSettings, TileEntityCrop.class, false, Ic2rTileEntityBlock.DefaultDrop.Self, Util.noFacings, false, Ic2rCropType.cyazint));
	public static final Block VENOMILIA_CROP = Ic2rBlocks.register("venomilia_crop", Ic2rTileEntityBlock.create(cropSettings, TileEntityCrop.class, false, Ic2rTileEntityBlock.DefaultDrop.Self, Util.noFacings, false, Ic2rCropType.venomilia));
	public static final Block REED_CROP = Ic2rBlocks.register("reed_crop", Ic2rTileEntityBlock.create(cropSettings, TileEntityCrop.class, false, Ic2rTileEntityBlock.DefaultDrop.Self, Util.noFacings, false, Ic2rCropType.reed));
	public static final Block STICKY_REED_CROP = Ic2rBlocks.register("sticky_reed_crop", Ic2rTileEntityBlock.create(cropSettings, TileEntityCrop.class, false, Ic2rTileEntityBlock.DefaultDrop.Self, Util.noFacings, false, Ic2rCropType.stickyReed));
	public static final Block COCOA_CROP = Ic2rBlocks.register("cocoa_crop", Ic2rTileEntityBlock.create(cropSettings, TileEntityCrop.class, false, Ic2rTileEntityBlock.DefaultDrop.Self, Util.noFacings, false, Ic2rCropType.cocoa));
	public static final Block FLAX_CROP = Ic2rBlocks.register("flax_crop", Ic2rTileEntityBlock.create(cropSettings, TileEntityCrop.class, false, Ic2rTileEntityBlock.DefaultDrop.Self, Util.noFacings, false, Ic2rCropType.flax));
	public static final Block RED_MUSHROOM_CROP = Ic2rBlocks.register("red_mushroom_crop", Ic2rTileEntityBlock.create(cropSettings, TileEntityCrop.class, false, Ic2rTileEntityBlock.DefaultDrop.Self, Util.noFacings, false, Ic2rCropType.redMushroom));
	public static final Block BROWN_MUSHROOM_CROP = Ic2rBlocks.register("brown_mushroom_crop", Ic2rTileEntityBlock.create(cropSettings, TileEntityCrop.class, false, Ic2rTileEntityBlock.DefaultDrop.Self, Util.noFacings, false, Ic2rCropType.brownMushroom));
	public static final Block NETHER_WART_CROP = Ic2rBlocks.register("nether_wart_crop", Ic2rTileEntityBlock.create(cropSettings, TileEntityCrop.class, false, Ic2rTileEntityBlock.DefaultDrop.Self, Util.noFacings, false, Ic2rCropType.netherWart));
	public static final Block TERRA_WART_CROP = Ic2rBlocks.register("terra_wart_crop", Ic2rTileEntityBlock.create(cropSettings, TileEntityCrop.class, false, Ic2rTileEntityBlock.DefaultDrop.Self, Util.noFacings, false, Ic2rCropType.terraWart));
	public static final Block OAK_SAPLING_CROP = Ic2rBlocks.register("oak_sapling_crop", Ic2rTileEntityBlock.create(cropSettings, TileEntityCrop.class, false, Ic2rTileEntityBlock.DefaultDrop.Self, Util.noFacings, false, Ic2rCropType.oakSapling));
	public static final Block SPRUCE_SAPLING_CROP = Ic2rBlocks.register("spruce_sapling_crop", Ic2rTileEntityBlock.create(cropSettings, TileEntityCrop.class, false, Ic2rTileEntityBlock.DefaultDrop.Self, Util.noFacings, false, Ic2rCropType.spruceSapling));
	public static final Block BIRCH_SAPLING_CROP = Ic2rBlocks.register("birch_sapling_crop", Ic2rTileEntityBlock.create(cropSettings, TileEntityCrop.class, false, Ic2rTileEntityBlock.DefaultDrop.Self, Util.noFacings, false, Ic2rCropType.birchSapling));
	public static final Block JUNGLE_SAPLING_CROP = Ic2rBlocks.register("jungle_sapling_crop", Ic2rTileEntityBlock.create(cropSettings, TileEntityCrop.class, false, Ic2rTileEntityBlock.DefaultDrop.Self, Util.noFacings, false, Ic2rCropType.jungleSapling));
	public static final Block ACACIA_SAPLING_CROP = Ic2rBlocks.register("acacia_sapling_crop", Ic2rTileEntityBlock.create(cropSettings, TileEntityCrop.class, false, Ic2rTileEntityBlock.DefaultDrop.Self, Util.noFacings, false, Ic2rCropType.acaciaSapling));
	public static final Block DARK_OAK_SAPLING_CROP = Ic2rBlocks.register("dark_oak_sapling_crop", Ic2rTileEntityBlock.create(cropSettings, TileEntityCrop.class, false, Ic2rTileEntityBlock.DefaultDrop.Self, Util.noFacings, false, Ic2rCropType.darkOakSapling));
	public static final Block FERRU_CROP = Ic2rBlocks.register("ferru_crop", Ic2rTileEntityBlock.create(cropSettings, TileEntityCrop.class, false, Ic2rTileEntityBlock.DefaultDrop.Self, Util.noFacings, false, Ic2rCropType.ferru));
	public static final Block CYPRIUM_CROP = Ic2rBlocks.register("cyprium_crop", Ic2rTileEntityBlock.create(cropSettings, TileEntityCrop.class, false, Ic2rTileEntityBlock.DefaultDrop.Self, Util.noFacings, false, Ic2rCropType.cyprium));
	public static final Block STAGNIUM_CROP = Ic2rBlocks.register("stagnium_crop", Ic2rTileEntityBlock.create(cropSettings, TileEntityCrop.class, false, Ic2rTileEntityBlock.DefaultDrop.Self, Util.noFacings, false, Ic2rCropType.stagnium));
	public static final Block PLUMBISCUS_CROP = Ic2rBlocks.register("plumbiscus_crop", Ic2rTileEntityBlock.create(cropSettings, TileEntityCrop.class, false, Ic2rTileEntityBlock.DefaultDrop.Self, Util.noFacings, false, Ic2rCropType.plumbiscus));
	public static final Block AURELIA_CROP = Ic2rBlocks.register("aurelia_crop", Ic2rTileEntityBlock.create(cropSettings, TileEntityCrop.class, false, Ic2rTileEntityBlock.DefaultDrop.Self, Util.noFacings, false, Ic2rCropType.aurelia));
	public static final Block SHINING_CROP = Ic2rBlocks.register("shining_crop", Ic2rTileEntityBlock.create(cropSettings, TileEntityCrop.class, false, Ic2rTileEntityBlock.DefaultDrop.Self, Util.noFacings, false, Ic2rCropType.shining));
	public static final Block RED_WHEAT_CROP = Ic2rBlocks.register("red_wheat_crop", Ic2rTileEntityBlock.create(cropSettings, TileEntityCrop.class, false, Ic2rTileEntityBlock.DefaultDrop.Self, Util.noFacings, false, Ic2rCropType.redWheat));
	public static final Block COFFEE_CROP = Ic2rBlocks.register("coffee_crop", Ic2rTileEntityBlock.create(cropSettings, TileEntityCrop.class, false, Ic2rTileEntityBlock.DefaultDrop.Self, Util.noFacings, false, Ic2rCropType.coffee));
	public static final Block HOPS_CROP = Ic2rBlocks.register("hops_crop", Ic2rTileEntityBlock.create(cropSettings, TileEntityCrop.class, false, Ic2rTileEntityBlock.DefaultDrop.Self, Util.noFacings, false, Ic2rCropType.hops));
	public static final Block EATING_PLANT_CROP = Ic2rBlocks.register("eating_plant_crop", Ic2rTileEntityBlock.create(cropSettings, TileEntityCrop.class, false, Ic2rTileEntityBlock.DefaultDrop.Self, Util.noFacings, false, Ic2rCropType.eatingPlant));
	public static final Block BLAZEREED_CROP = Ic2rBlocks.register("blazereed_crop", Ic2rTileEntityBlock.create(cropSettings, TileEntityCrop.class, false, Ic2rTileEntityBlock.DefaultDrop.Self, Util.noFacings, false, Ic2rCropType.blazereed));
	public static final Block BOBS_YER_UNCLE_RANKS_BERRIES_CROP = Ic2rBlocks.register("bobs_yer_uncle_ranks_berries_crop", Ic2rTileEntityBlock.create(cropSettings, TileEntityCrop.class, false, Ic2rTileEntityBlock.DefaultDrop.Self, Util.noFacings, false, Ic2rCropType.bobsYerUncleRanksBerries));
	public static final Block CORIUM_CROP = Ic2rBlocks.register("corium_crop", Ic2rTileEntityBlock.create(cropSettings, TileEntityCrop.class, false, Ic2rTileEntityBlock.DefaultDrop.Self, Util.noFacings, false, Ic2rCropType.corium));
	public static final Block CORPSE_PLANT_CROP = Ic2rBlocks.register("corpse_plant_crop", Ic2rTileEntityBlock.create(cropSettings, TileEntityCrop.class, false, Ic2rTileEntityBlock.DefaultDrop.Self, Util.noFacings, false, Ic2rCropType.corpse_plant));
	public static final Block CREEPER_WEED_CROP = Ic2rBlocks.register("creeper_weed_crop", Ic2rTileEntityBlock.create(cropSettings, TileEntityCrop.class, false, Ic2rTileEntityBlock.DefaultDrop.Self, Util.noFacings, false, Ic2rCropType.creeper_weed));
	public static final Block DIAREED_CROP = Ic2rBlocks.register("diareed_crop", Ic2rTileEntityBlock.create(cropSettings, TileEntityCrop.class, false, Ic2rTileEntityBlock.DefaultDrop.Self, Util.noFacings, false, Ic2rCropType.diareed));
	public static final Block EGG_PLANT_CROP = Ic2rBlocks.register("egg_plant_crop", Ic2rTileEntityBlock.create(cropSettings, TileEntityCrop.class, false, Ic2rTileEntityBlock.DefaultDrop.Self, Util.noFacings, false, Ic2rCropType.egg_plant));
	public static final Block ENDER_BLOSSOM_CROP = Ic2rBlocks.register("ender_blossom_crop", Ic2rTileEntityBlock.create(cropSettings, TileEntityCrop.class, false, Ic2rTileEntityBlock.DefaultDrop.Self, Util.noFacings, false, Ic2rCropType.ender_blossom));
	public static final Block MEAT_ROSE_CROP = Ic2rBlocks.register("meat_rose_crop", Ic2rTileEntityBlock.create(cropSettings, TileEntityCrop.class, false, Ic2rTileEntityBlock.DefaultDrop.Self, Util.noFacings, false, Ic2rCropType.meat_rose));
	public static final Block MILK_WART_CROP = Ic2rBlocks.register("milk_wart_crop", Ic2rTileEntityBlock.create(cropSettings, TileEntityCrop.class, false, Ic2rTileEntityBlock.DefaultDrop.Self, Util.noFacings, false, Ic2rCropType.milk_wart));
	public static final Block OIL_BERRIES_CROP = Ic2rBlocks.register("oil_berries_crop", Ic2rTileEntityBlock.create(cropSettings, TileEntityCrop.class, false, Ic2rTileEntityBlock.DefaultDrop.Self, Util.noFacings, false, Ic2rCropType.oil_berries));
	public static final Block SLIME_PLANT_CROP = Ic2rBlocks.register("slime_plant_crop", Ic2rTileEntityBlock.create(cropSettings, TileEntityCrop.class, false, Ic2rTileEntityBlock.DefaultDrop.Self, Util.noFacings, false, Ic2rCropType.slime_plant));
	public static final Block SPIDERNIP_CROP = Ic2rBlocks.register("spidernip_crop", Ic2rTileEntityBlock.create(cropSettings, TileEntityCrop.class, false, Ic2rTileEntityBlock.DefaultDrop.Self, Util.noFacings, false, Ic2rCropType.spidernip));
	public static final Block TEARSTALKS_CROP = Ic2rBlocks.register("tearstalks_crop", Ic2rTileEntityBlock.create(cropSettings, TileEntityCrop.class, false, Ic2rTileEntityBlock.DefaultDrop.Self, Util.noFacings, false, Ic2rCropType.tearstalks));
	public static final Block WITHEREED_CROP = Ic2rBlocks.register("withereed_crop", Ic2rTileEntityBlock.create(cropSettings, TileEntityCrop.class, false, Ic2rTileEntityBlock.DefaultDrop.Self, Util.noFacings, false, Ic2rCropType.withereed));
}
