modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${csas_mod_license}"

[[mods]]
modId="${csas_mod_id}"
version="${csas_mod_version}"
displayName="${csas_mod_name}"
authors="${csas_mod_authors}"
description='''
${csas_mod_description}
'''

[[dependencies.${csas_mod_id}]]
modId="forge"
mandatory=true
versionRange="${forge_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${csas_mod_id}]]
modId="minecraft"
mandatory=true
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${csas_mod_id}]]
modId="ic2"
mandatory=true
versionRange="[2.10,)"
ordering="AFTER"
side="BOTH"